### ISSUE TITLE
broadlink-rm startup failure

### ISSUE THREAD

**Issue by bebeboy** [lprhodes/homebridge-broadlink-rm#1]
I am not able to startup my broadlink plugin with the followings, any hints are welcome.

017-03-15 15:16:28	stdout	[37m[3/15/2017, 3:16:28 PM][39m [1m[31m====================[39m[22m
2017-03-15 15:16:28	stdout	    at Module._compile (module.js:556:32)[39m[22m
2017-03-15 15:16:28	stdout	    at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/ThermostatService.js:1:78)
2017-03-15 15:16:28	stdout	    at require (internal/module.js:20:19)
2017-03-15 15:16:28	stdout	    at Module.require (module.js:483:17)
2017-03-15 15:16:28	stdout	    at Function.Module._load (module.js:424:3)
2017-03-15 15:16:28	stdout	    at tryModuleLoad (module.js:432:12)
2017-03-15 15:16:28	stdout	    at Module.load (module.js:473:32)
2017-03-15 15:16:28	stdout	    at Object.Module._extensions..js (module.js:565:10)
2017-03-15 15:16:28	stdout	    at Module._compile (module.js:528:28)
2017-03-15 15:16:28	stdout	    at Object.exports.runInThisContext (vm.js:76:16)
2017-03-15 15:16:28	stdout	SyntaxError: missing ) after argument list
2017-03-15 15:16:28	stdout	                                                   ^^
2017-03-15 15:16:28	stdout	    console.log(`UDP message sent to ${host}:${PORT}`;
2017-03-15 15:16:28	stdout	[37m[3/15/2017, 3:16:28 PM][39m [1m[31m/usr/lib/node_modules/homebridge-broadlink-rm/sender.js:14
2017-03-15 15:16:28	stdout	[37m[3/15/2017, 3:16:28 PM][39m [1m[31mERROR LOADING PLUGIN homebridge-broadlink-rm:[39m[22m

**Comment by daniel4099** [comment]
I have similar problem when plugin starting:

[3/15/2017, 6:37:57 PM] ====================
[3/15/2017, 6:37:57 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[3/15/2017, 6:37:57 PM] /usr/local/lib/node_modules/homebridge-broadlink-rm/sender.js:14
    console.log(`UDP message sent to ${host}:${PORT}`;
                                                   ^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/ThermostatService.js:1:78)

**Comment by daniel4099** [comment]
I gues, the problem may be the version of RM PRO, I use RM PRO 2, not 3. Can you make it work for RM PRO 2 ?

**Comment by lprhodes** [comment]
Sorry guys, it was a stupid mistake - I've fixed within 0.2.4 and published to npm
https://github.com/lprhodes/homebridge-broadlink-rm/commit/2ec8fe562c77222812c165030b057cd45e10b7a5
