### ISSUE TITLE
homebridge stop running after scheduled auto restart with broadlink-rm installed

### ISSUE THREAD

**Issue by DJay79** [lprhodes/homebridge-broadlink-rm#111]
Hello. I'm relatively new to homebridge so please bear with me. :)
I'm running homebridge on my Pi 2 a while now. But after installing homebridge-broadlink-rm the homebridge stop working after some time. setup the config.json with two "switch-repeat", one "switch" and one "fan" type worked so they show up in my Eve and Home App to control the devices.
All works very well until out of the blue homebridge stops.
As mentioned I'm new to this but I realized that this behavior is since homebridge-broadlink-rm.
My homebridge is configured to reboot every hour and start homebridge by "forever" 
sudo npm install forever -g and a script Autostart (init.d) sudo nano /etc/init.d/homebridge

When I run in the terminal just "homebridge" to watch what is going on, it runs the whole hour.
But after auto restart, homebridge is not working anymore.

So first how can I see a log or live view what is actually happening when it stops and with what error?
And then with your help I would be great to fix it, because I wouldn't want to miss this plugin. :)

Thanks in advance for investing your time in this and for your help.

homebridge@0.4.20 | n@2.1.7 | node@7.10.0 | npm@4.6.1

**Comment by DJay79** [comment]
I'm not even sure if this the correct information, but I'll post it with the hope this could help to solve my problem.

What is strange to me that homebridge is running and also auto restart the raspberry and homebridge every hour works. It works a couple of times over the day and without touching anything with the next auto reboot homebridge is not running. Even after manual`sudo reboot`
Without the homebridge-broadlink-rm plugin, everything works good day after day. :/

I found this command in another forum `sudo cat /var/log/homebridge.err` to give me an error log. But I'm not sure is this is helpful for somebody. 

> /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:424:18)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)

**Comment by DJay79** [comment]
I discovered an old backup of homebridge and installed most thins from scratch new. This fixed it. So I close this issue here.
