### ISSUE TITLE
Plug in stop after running overnight

### ISSUE THREAD

**Issue by PParit** [lprhodes/homebridge-broadlink-rm#114]
I just try to install your plug in to my homebridge which is running on Raspberry Pi. However, after a while, home bridge just quit and show the following message:

crypto.js:160
  var ret = this._handle.final();
                         ^

Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Decipheriv.final (crypto.js:160:26)
    at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-platform/node_modules/broadlinkjs-sm/index.js:234:27)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:544:8)

Could you please help me with the issue?

**Comment by nitaybz** [comment]
are you using another broadlink plugin? I'm experiencing the same issue

**Comment by lprhodes** [comment]
The issue lies within the broadlinkjs-sm module https://github.com/smka/broadlinkjs-sm
