### ISSUE TITLE
Homebridge crash if currentTemperature > maxTemperature

### ISSUE THREAD

**Issue by donev77** [lprhodes/homebridge-broadlink-rm#145]
[2017-7-2 20:37:52] [Broadlink RM] Air Conditioner getTargetHeatingCoolingState: 0
[2017-7-2 20:37:52] [Broadlink RM] Air Conditioner getTargetTemperature: 16
[2017-7-2 20:37:52] [Broadlink RM] Air Conditioner getCurrentHeatingCoolingState: 0
/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:376
    if (state.currentTemperature > maxTemperature) throw new Error(`The current temperature (${state.currentTemperature}) must be less than the maxTemperature (${maxTemperature})`);
                                                   ^

Error: The current temperature (30.1) must be less than the maxTemperature (30)
    at AirConAccessory.processQueuedCallbacks (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:376:58)
    at device.onTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:353:12)
    at emitOne (events.js:115:13)
    at device.emit (events.js:210:7)
    at device.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:384:22)
    at emitTwo (events.js:125:13)
    at device.emit (events.js:213:7)
    at Socket.cs.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:207:18)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)

homebridge: v.4.22
homebridge-broadlink-rm: v.2.5.12

**Comment by sokompheak** [comment]
I got that problem to... I tried to set "maxTemperature":"35", but after run homebridge, My home app not working hahaha

**Comment by lprhodes** [comment]
Setting "maxTemperature":"35" should fix this...

**Comment by lprhodes** [comment]
...reopen if not
