### ISSUE TITLE
node@8.6.0 stopped broadlink-rm from working - throw Error('[PARSE-ERROR] ' + file + ' does not look like a valid storage file!')

### ISSUE THREAD

**Issue by DJay-X** [lprhodes/homebridge-broadlink-rm#197]
node@8.6.0 stopped broadlink-rm from working.

```
[2017-9-29 17:57:22] [Broadlink RM] Initializing BroadlinkRM platform...
: /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:666
: throw Error('[PARSE-ERROR] ' + file + ' does not look like a valid storage file!');
: ^
: Error: [PARSE-ERROR] /home/pi/.homebridge/plugin-persist/homebridge-broadlink-rm/c93c7e5ffdce151a64e406310c2235f8 does not look like a valid storage file!
: at LocalStorage.parseFileSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:666:19)
: at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:615:26)
: at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:142:14)
: at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/node-persist.js:37:32)
: at Object.init (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:10:15)
: at BroadlinkRMPlatform.HomebridgePlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:14:21)
: at BroadlinkRMPlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/index.js:11:1)
: at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
Sep 29 17:57:22 raspberrypi homebridge[3648]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
: at Module._compile (module.js:624:30)
: at Object.Module._extensions..js (module.js:635:10)
: at Module.load (module.js:545:32)
: at tryModuleLoad (module.js:508:12)
: at Function.Module._load (module.js:500:3)
: at Function.Module.runMain (module.js:665:10)
: at startup (bootstrap_node.js:187:16)
: at bootstrap_node.js:607:3

```

**Comment by DJay79** [comment]
Out of the blue, I have this error again.
After this I updated now to homebridge@0.4.29 | n@2.1.8 | node@8.8.0 | npm@5.5.1

Any help would be appreciated. Thanks in advance.

**Comment by acc-ua** [comment]
Looks like you have wrong cache files in ~/.homebridge/plugin-persist/homebridge-broadlink-rm folder.  try to move them into another folder and see how it goes.

**Comment by perote2000** [comment]
Is there any way to make plugin to remove that file and try to create a new one? It happens very often when PI is disconnected (and also happened me when I restarted PI properly). Perhaps an option to erase corrupt cache file when it fails.
