### ISSUE TITLE
Latest node version installed but still reading old node version

### ISSUE THREAD

**Issue by Fir3Man7** [lprhodes/homebridge-broadlink-rm#204]
Hello everyone! I am facing what I believe to be a minor issue but which i cannot fix on my own.
When starting homebridge i get the following error:

[11/7/2017, 9:48:21 PM] Error: Homebridge plugins that use the "homebridge-easy-platform" library require your node version to be at least v7.6.0. Current version: v6.11.4

But if I check my node version using node -v i get:
pi@raspberrypi:~ $ node -v
v8.9.0

I tried restarting my pi and uninstalling/reinstalling the homebridge-broadlink-rm package but i still get the same issue.
Also using the nvm list command you can see that my default version is 8.9.0.
pi@raspberrypi:~ $ nvm list
         v7.6.0
->       v8.9.0
         system
default -> 8.9.0 (-> v8.9.0)
node -> stable (-> v8.9.0) (default)
stable -> 8.9 (-> v8.9.0) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> v8.9.0)
lts/argon -> v4.8.6 (-> N/A)
lts/boron -> v6.12.0 (-> N/A)
lts/carbon -> v8.9.0

Any advice?
Thanks

**Comment by lprhodes** [comment]
Given that this was a while I hope you managed to fix this?

**Comment by lprhodes** [comment]
Please re-open if not.

**Comment by peterlbk** [comment]
I get exactly the same version..
error was triggered by this:

Error: Homebridge plugins that use the "homebridge-easy-platform" library require your node version to be at least v7.6.0. Current version: v6.12.2
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:4:48)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/index.js:1:90)
    at Module._compile (module.js:570:32)
