### ISSUE TITLE
Can't install after update.

### ISSUE THREAD

**Issue by daniel4099** [lprhodes/homebridge-broadlink-rm#21]
Hi 

I remove previously version to install the new on.
I have a problem with installation, everything was working fine during installation on previously version.

pi@raspberrypi:~ $ sudo npm install -g homebridge-broadlink-rm
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
npm WARN addRemoteGit     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
npm WARN addRemoteGit     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15)
npm WARN addRemoteGit  git+https://github.com/clkao/broadlinkjs.git#0ed810a resetting remote /root/.npm/_git-remotes/git-https-github-com-clkao-broadlinkjs-git-0ed810a-9ab06fa6 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
npm WARN addRemoteGit     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
npm WARN addRemoteGit     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:114:15) code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/clkao/broadlinkjs.git /root/.npm/_git-remotes/git-https-github-com-clkao-broadlinkjs-git-0ed810a-9ab06fa6: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/clkao/broadlinkjs.git /root/.npm/_git-remotes/git-https-github-com-clkao-broadlinkjs-git-0ed810a-9ab06fa6: undefined
npm ERR! Linux 4.4.50+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-broadlink-rm"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-03-29T19_41_54_170Z-debug.log
pi@raspberrypi:~ $ npm install -g homebridge-broadlink-rm
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror https://github.com/clkao/broadlinkjs.git /home/pi/.npm/_git-remotes/git-https-github-com-clkao-broadlinkjs-git-0ed810a-9ab06fa6: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror https://github.com/clkao/broadlinkjs.git /home/pi/.npm/_git-remotes/git-https-github-com-clkao-broadlinkjs-git-0ed810a-9ab06fa6: undefined
npm ERR! Linux 4.4.50+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-broadlink-rm"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.npm/_logs/2017-03-29T19_45_19_953Z-debug.log
pi@raspberrypi:~ $

**Comment by daniel4099** [comment]
Solved this, after the upgrade there has to be GIT installed:

sudo apt-get install git
