### ISSUE TITLE
The Homebridge would be halted sometime after update to 1.0.2

### ISSUE THREAD

**Issue by leonardolau** [lprhodes/homebridge-broadlink-rm#22]
Thanks for the new patch. I found an issue after update to 1.0.2 with the log:
[3/30/2017, 9:25:22 AM] [Broadlink RM Pro 3 MR] getSwitchState: 0
[3/30/2017, 9:25:22 AM] [Broadlink RM Pro 3 LR] getSwitchState: 0
[3/30/2017, 9:25:22 AM] [Broadlink RM Pro 3 MR] getCurrentTemperature (24.1)
[3/30/2017, 9:25:22 AM] [Broadlink RM Pro 3 LR] getCurrentTemperature (22.7)
events.js:326
        throw new TypeError('"listener" argument must be a function');
        ^

TypeError: "listener" argument must be a function
    at device.removeListener (events.js:326:15)
    at Timeout.removeTemperatureListenerTimer.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:265:14)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

 and have to re-run sometime.

**Comment by lprhodes** [comment]
Looks like one of the dependencies didn't get updated. Try this:

```
npm r broadlinkjs -g
npm i homebridge-broadlink-rm -g
```

**Comment by leonardolau** [comment]
Thanks Luke, I shall try.
Furthermore, could I disable the thermometer for RM mini device as could not get the actual temperature? Please advise.

**Comment by lprhodes** [comment]
What happens when it can't get the temperature? It logs a timeout error, right?

**Comment by leonardolau** [comment]
It always shows 12C, and sometimes timeout. I am not sure that was caused by the RM mini.

**Comment by lprhodes** [comment]
I assume the temperature isn't 12C? It's odd that any temperature would be returned.

I've just pushed 1.0.3 with a new psuedoDeviceTemperature property - check the README for info and let me know how it goes.
