### ISSUE TITLE
Error: We don't support accessories of type "switch-multi".

### ISSUE THREAD

**Issue by RickNunn** [lprhodes/homebridge-broadlink-rm#26]
Using the new Switch Multi is giving me an error (I have updated to 1.0.5)
```
/usr/local/lib/node_modules/homebridge-broadlink-rm/index.js:71
          throw new Error(`We don't support accessories of type "${accessory.type}".`);
          ^

Error: We don't support accessories of type "switch-multi".
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/index.js:71:17)
    at Array.forEach (native)
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/index.js:40:24)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:354:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:298:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Config: 

```
"accessories":[
        {
          "name":"Entertainment",
		  "type":"switch-multi",
          "interval":0.5,
          "data": [
            "260046009590…",
            "260070000001…"
          ]
        }
      ]
```

**Comment by lprhodes** [comment]
Sorry I must have previously published 1.0.5 and it failed to publish to npm without realising. I've updated it to 1.0.6
