### ISSUE TITLE
AC not responding

### ISSUE THREAD

**Issue by matosbsb** [lprhodes/homebridge-broadlink-rm#271]
Hi there,

I am new here and I am trying to make the AC work, but I had some problems.
First, when I say "hey siri turn the AC on", although she says "done", nothing happens. But when the AC is off and I say "AC off", it turns ON. Also heat and cooling are not working too.

This is my config:
I know the Json format is not valid, but it is because I've copied through Nano, so it puts $ to indicate there are more data. 

                        {
                                "name": "Air Conditioner",
                                "type": "air-conditioner",
                                "data": {
                                        "off": "260040000001248812331111111210121034111111121012101310121012111111121012101211$
                                        "on": "2600400000012488103411111111111111341012101210121012111111121012101210121112101$
                                        "temperature30": {
                                                "pseudo-mode": "heat",
                                                "data": "IMAGINE SOME HEX CODE HERE"
                                        },
                                        "temperature16": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001218b0f3610120f140e130f360f130e140f140e140e140f130e360f130$
                                        },
                                        "sendOnWhenOff": true
                                }
                        },

Thanks.

**Comment by lprhodes** [comment]
Can you send the logs please

**Comment by matosbsb** [comment]
Hi,

Thanks for helping me.... When I ask to turn on, nothing happens.

Here are the logs:

[2/28/2018, 11:50:27 PM] [Broadlink RM] Air Conditioner getCurrentTemperature (26.9)
[2/28/2018, 11:50:37 PM] [Broadlink RM] Air Conditioner getCurrentTemperature (26.9)
[2/28/2018, 11:50:45 PM] [Broadlink RM] Air Conditioner setTargetHeatingCoolingState: 3
[2/28/2018, 11:50:45 PM] [Broadlink RM] Air Conditioner Potential sendTemperature (18)
[2/28/2018, 11:50:45 PM] [Broadlink RM] Air Conditioner sendTemperature (18, cool)
[2/28/2018, 11:50:45 PM] [Broadlink RM] Air Conditioner setTargetTemperature: 18
[2/28/2018, 11:50:45 PM] [Broadlink RM] Air Conditioner setTargetTemperature: already 18 (no data sent - B)
[2/28/2018, 11:50:45 PM] [Broadlink RM] Air Conditioner sendHex (192.168.0.28; xxxxxx)
[2/28/2018, 11:50:45 PM] [Broadlink RM] Air Conditioner setCurrentHeatingCoolingState: 2
[2/28/2018, 11:50:45 PM] [Broadlink RM] Air Conditioner setTargetHeatingCoolingState: 2
[2/28/2018, 11:50:47 PM] [Broadlink RM] Air Conditioner getCurrentTemperature (26.9)
[2/28/2018, 11:50:58 PM] [Broadlink RM] Air Conditioner getCurrentTemperature (26.9)
[2/28/2018, 11:51:08 PM] [Broadlink RM] Air Conditioner getCurrentTemperature (26.9)



After that I tried to improve config.json:

{
                                "name": "Air Conditioner",
                                "host": "34:ea:34:c7:cd:f4",
                                "type": "air-conditioner",
                                "minTemperature": 16,
                                "maxTemperature": 30,
                                "disableLogs": false,
                                "autoHeatTemperature": 21,
                                "autoCoolTemperature": 28,
                                "autoMinimumDuration": 300,
                                "defaultHeatTemperature": 27,
                                "defaultCoolTemperature": 18,
                                "temperatureAdjustment": -5,
                                "heatTemperature": 27,
                                "autoMinimumDuration": 600,
                                "sendOnWhenOff": true,
                                "temperatureAdjustment": 0,
                                "allowResend": true,
                                "heatTemperature": 27,
                                "data": {
                                        "off": "260040000001208c0f360e140e140f130f350f140e140e1410350e360e140f130e140f130e140e140f140e140e140e140e140e360f130f350f140e140e150e360e00$
                                        "temperature30": {
                                                "pseudo-mode": "heat",
                                                "data": "260040000001248a0f360e140e150e140e360f130f140e140e140e150e140e140f350f130f130f140e360e360f350f350f140e360e140e140f350e140e3$
                                        },
                                        "temperature29": {
                                                "pseudo-mode": "heat",
                                                "data": "260040000001208a10350f130e140e140e360f140e140e140e140e140e140f130f350f130f140e140e370e360f360e140f130f360e140e140f360e140f3$
                                        },
                                        "temperature28": {
                                                "pseudo-mode": "heat",
                                                "data": "260040000001228b0e360e140f140e140e3610130e140e140e140e140f130f130f360e140f140f130e360f350f130f350f140e360e140e140e360e140e1$
                                        },
                                        "temperature27": {
                                                "pseudo-mode": "heat",
                                                "data": "260040000001218b0f360e140f130e140f360e140e140e140f140e140e150e140e350f140f130f140e360e360e140e140e140e360f130f140e360e140f1$
                                        },
                                        "temperature26": {
                                                "pseudo-mode": "heat",
                                                "data": "260040000001218a0e370e140e140f140e360e140e140e150e140e140f130f140e360e140e140e140f350f140e360e360e140f360e140e140e140f350e3$
                                        },
                                        "temperature25": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001228b0e360e140f130f140e350f140e140e140e140e140f130f130f350f130e140f140e360e150e360e140e140e360e140e140f130f360e3$
                                        },
                                        "temperature24": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001208b0f350f130f140e140e360e140e140e140e140f130e140f130f360e140e140f140e360e140e140f360e140e360e140e140e140f360e1$
                                        },
                                        "temperature23": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001218b0e360f140e140e140e360e140e140f130f140e140e140e140e360e140e140e140e360f140e140f130e150e360f130e140e140e370e1$
                                        },
                                        "temperature22": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001218b0e360e140e140e140e360f130f130f140e140f130f140e140e360f140e140e140e140e350f360e360e140e360f140e140f130e140e3$
                                        },
                                        "temperature21": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001208b0e370e140e140f140e360e140e140f140e140e140f130f140e360e140e140e140f130f360e360e140e140e360f140e140f130f130f3$
                                        },
                                        "temperature20": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001228a0e360f130f140e140f360e140e140f130f130f140e140e150e360e140e140e140e140e3610130e350f130f360e140f140e140e140e1$
                                        },
                                        "temperature19": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001218b0f360e140e140e140e360e140e140f130f140e140e140e140e360e140e140e140e150e360e140f130f140e360f130e140e140e140f1$
                                        },
                                        "temperature18": {
                                                "pseudo-mode": "cool",
                                                "data": "260040000001218a0f360e140e150e140e360f130f1310130e140e140f140e140f350f130f1310120f1310130e360e360e140e3610130e140f360e360f3$
                                        }
                                }
                        },


After that, when I ask for turn on I got this:

[3/1/2018, 12:03:15 AM] [Broadlink RM] Air Conditioner Potential sendTemperature (27)
[3/1/2018, 12:03:15 AM] [Broadlink RM] Air Conditioner sendTemperature (turning on before setting temperature)
[3/1/2018, 12:03:15 AM] [Broadlink RM] Air Conditioner Potential sendTemperature (27)
[3/1/2018, 12:03:15 AM] [Broadlink RM] Air Conditioner sendTemperature (turning on before setting temperature)
[3/1/2018, 12:03:15 AM] [Broadlink RM] Air Conditioner Potential sendTemperature (27)
setCharacteristicValue err RangeError: Maximum call stack size exceeded
    at Object.stringify (<anonymous>)
    at LocalStorage.stringify (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:530:29)
    at LocalStorage.persistKeySync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:471:41)
    at LocalStorage.setItemSync (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:255:14)
    at Object.save (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:28:22)
    at HomebridgeAccessory.state.addSaveProxy (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:43:25)
    at Object.set (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:9:7)
    at AirConAccessory.sendTemperature (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:255:31)
    at AirConAccessory.setTargetHeatingCoolingState (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:336:12)
    at AirConAccessory.sendTemperature (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:271:12)
[3/1/2018, 12:03:16 AM] [Broadlink RM] Air Conditioner setTargetHeatingCoolingState: 0
[3/1/2018, 12:03:16 AM] [Broadlink RM] Air Conditioner getCurrentTemperature (27.9)


Thanks again...

**Comment by lprhodes** [comment]
Hey @matosbsb can you install the latest version and let me know how you go please.

**Comment by lprhodes** [comment]
Closing unless further information is given

**Comment by matosbsb** [comment]
Hi @lprhodes 

I am using temperature in Celsius. 
If I set minTemperature on config.json to 18, the service doesn't work. If I set to 10, the service runs, but the AC still doesn't work...
I've updated to latest version and now I'm getting the following error:


/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/chai/lib/chai/assertion.js:141
      throw new AssertionError(msg, {
      ^
AssertionError: [CONFIG ERROR] minTemperature (18) must be <= 10: expected 18 to be below 11
    at AirConAccessory.setDefaults (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:95:12)
    at AirConAccessory.HomebridgeAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:39:10)

**Comment by lprhodes** [comment]
It will definitely need to be <= 10

Can you provide logs showing when the ac isn’t working please and an updated config

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lprhodes** [comment]
Closing - shall re-open if further information is provided.

**Comment by samlowry** [comment]
Hi! Have same prob with Celcius minTemperature=18. Most of ACs which I saw has 18° bottom temp, so ≤10 is a quite strange limitation.

**Comment by Dbarl** [comment]
Have same problem.
