### ISSUE TITLE
If Turn off need to press the remote control twice

### ISSUE THREAD

**Issue by EAI42** [lprhodes/homebridge-broadlink-rm#281]
Please tell me how to fix it.

	{
			"platform": "BroadlinkRM",
			"name": "Broadlink RM",
			"accessories": [{
				"name": "light",
				"type": "light",
				"data": {

					"on": "2600580040...",
					"off": ["26005800441fb...",
						   "2600580040..."
					]
				}

			}]
		}

[Broadlink RM] light setSwitchState: false
setCharacteristicValue err { AssertionError: HEX value is missing
    at module.exports (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/sendData.js:6:3)
    at SwitchAccessory.setSwitchState (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:15:18)
    at SwitchAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:118:15)
    at emitMany (events.js:127:13)
    at Characteristic.On.emit (events.js:204:7)
    at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:311:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:867:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:807:8)
    at emitMany (events.js:127:13)
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'HEX value is missing',

**Comment by phenix13** [comment]
You can use Switch or Repeat Switch  type in config.json , then change the switch to the light type in home app.
