### ISSUE TITLE
Homebridge not starting because of host value error

### ISSUE THREAD

**Issue by iandronowicz** [lprhodes/homebridge-broadlink-rm#297]
@lprhodes Since last update I get this:

Homer-MacMini:~ homer$ homebridge 
[3/14/2018, 8:36:01 PM] Loaded plugin: homebridge-broadlink-rm
[3/14/2018, 8:36:01 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[3/14/2018, 8:36:01 PM] ---
[3/14/2018, 8:36:01 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/14/2018, 8:36:01 PM] ---
[3/14/2018, 8:36:01 PM] Loading 1 platforms...
[3/14/2018, 8:36:01 PM] [Broadlink RM] Initializing BroadlinkRM platform...
[CONFIG ERROR] Numeric values should look like this: "host": 10.0.1.7 not this "host": "10.0.1.7"

I went to the config file and remove the " " from the ip numbers and got this:

Homer-MacMini:~ homer$ homebridge 
[3/14/2018, 8:32:30 PM] Loaded plugin: homebridge-broadlink-rm
[3/14/2018, 8:32:30 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[3/14/2018, 8:32:30 PM] ---
[3/14/2018, 8:32:30 PM] There was a problem reading your config.json file.
[3/14/2018, 8:32:30 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[3/14/2018, 8:32:30 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token . in JSON at position 391
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by lprhodes** [comment]
This is fixed in v3.2.3
