### ISSUE TITLE
Cannot run properly with Homebridge

### ISSUE THREAD

**Issue by leonardolau** [lprhodes/homebridge-broadlink-rm#3]
Thanks Iprhodes. I have been looking for RM plugin very long time. But after installed the plugin yesterday, the homebridge runs with following error. Any thoughts? 

[3/17/2017, 9:56:14 AM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[3/17/2017, 9:56:14 AM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)
    at Array.forEach (native)
[3/17/2017, 9:56:14 AM] ====================

**Comment by lprhodes** [comment]
Looks like you're running an old version of node

**Comment by leonardolau** [comment]
Yes, after upgraded the node to 7 and the plugin runs properly. Thanks. Though I am still struggling on the devices setup.

**Comment by lprhodes** [comment]
What're you struggling with exactly?

**Comment by leonardolau** [comment]
I have two rm pro 2 and one rm mini 3, used your sample config.json and just changed the ip address as they are, but none of them responds to the signal.

**Comment by lprhodes** [comment]
I assume you updated the hex codes to ones that work for your IR device though? (e.g.. your TV)?

Did you try the learner accessory? What was the homebridge console output?

**Comment by leonardolau** [comment]
It generates a hex automatically once the button is tapped.
