### ISSUE TITLE
checkConfig(value)

### ISSUE THREAD

**Issue by siobhanellis** [lprhodes/homebridge-broadlink-rm#306]
I've upgrade from 2.x to 3.x, and I'm now getting an error:

[16/03/2018, 3:19:10 pm] [Broadlink RM] Initializing BroadlinkRM platform...
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:63
        checkConfig(value);
       ^

ReferenceError: checkConfig is not defined
    at Object.keys.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:63:9)
    at Array.forEach (<anonymous>)
    at LightAccessory.checkConfig (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:51:25)
    at new HomebridgeAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:35:10)
    at new BroadlinkRMAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:17:5)
    at new SwitchAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:10:5)
    at new LightAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/light.js:7:1)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:75:32)
    at Array.forEach (<anonymous>)
    at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:70:24

I've gone over my config.json, and I did find that you had changed a number of things, but I've cleaned it up and still get the error.

 {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM",
      "accessories":[
        {
          "name":"LR Fan Light",
          "type":"light",
          "data":{
            "off": "2600500000012",
            "brightness25": "650a1c000b0b15160b0b150b160b15160b160b160b160b160b160b0c15000170000000000000000000000000",
            "brightness50": "650a1c000b0b15160b0b150b160b15160b160b160b160b160b160b0c15000170000000000000000000000000",
            "brightness75": "650a1c000b0b15160b0b150b160b15160b160b160b160b160b160b0c15000170000000000000000000000000",
            "brightness100": "650a1c000b0b15160b0b150b160b15160b160b160b160b160b160b0c15000170000000000000000000000000"
          }
        },
        {
          "name": "LR Fan",
          "type": "fan",
          "hideSwingMode": true,
          "hideRotationDirection": true,
          "data": {
            "on": "640b1c000b0b16160b0b150b160b16160b160b0b16160b160b160b160b00016f000000000000000000000000",
            "off": "65271c000b0c15160b0c150c160b15160b160b160b160b160b0b15160b000170000000000000000000000000",
            "fanSpeed30": "65511c000b0b15160b0b160b150b15160b160b160b0b16160b150b160b000170000000000000000000000000",
            "fanSpeed60": "640b1c000b0b16160b0b150b160b16160b160b0b16160b160b160b160b00016f000000000000000000000000",
            "fanSpeed100": "650e1c000b0b15160b0b150b150b15160b0b15160b160b160b160b160b000170000000000000000000000000"
          }
        }
      ]
    }

**Comment by lprhodes** [comment]
This was fixed previously, can you please ensure you're on the latest version.

**Comment by siobhanellis** [comment]
I'd done an update, or so I thought....

I missed the -g switch on update. :-(

Thanks.

**Comment by lprhodes** [comment]
haha, easily done. I'm glad it's sorted.
