### ISSUE TITLE
HEX value is missing error when sending multiple hex values for window covering. 

### ISSUE THREAD

**Issue by jgrantfletcher** [lprhodes/homebridge-broadlink-rm#316]
Hi Luke, 

Thanks for all of your work on this project so far, really appreciate it. 

I have all 4 of my window coverings working as individual devices (Blinds1, Blinds2, etc.). All are working and no problem there. I'm trying to consolidate the 4 individual blinds using 'Multiple HEX codes' as described in the documentation so that Homebridge sees only 1 device but activates the 4 blinds sequentially. I have followed the example on the config-sample.json and I keep getting the error messages below. I have included my config.json and copied the text of the error from the Homebridge log below.

I'm new here so it my be some silly mistake, but any help appreciated!
Grant

[2018-3-19 08:48:07] [Broadlink RM] Patio Blinds getTargetPosition: 0
[2018-3-19 08:48:07] [Broadlink RM] Patio Blinds getCurrentPosition: 0
[2018-3-19 08:48:14] [Broadlink RM] Patio Blinds setTargetPosition: 100
[2018-3-19 08:48:15] [Broadlink RM] Patio Blinds setTargetPosition: currently 0%, moving to 100%
[2018-3-19 08:48:15] [Broadlink RM] Patio Blinds setTargetPosition: 32s (32 / 100 * 100) until auto-stop 1521474495652
(node:8357) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: [ERROR]: HEX value is missing
    at module.exports (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/sendData.js:6:3)
    at WindowCoveringAccessory.openOrClose (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/windowCovering.js:109:5)
    at WindowCoveringAccessory.performSetTargetPosition (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/windowCovering.js:80:10)
    at Timeout.initialDelayTimeout.setTimeout [as _onTimeout] (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/windowCovering.js:31:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:8357) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8357) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-3-19 08:48:15] [Broadlink RM] Patio Blinds setPositionState: 1

[config_1blind.txt](https://github.com/lprhodes/homebridge-broadlink-rm/files/1825665/config_1blind.txt)

**Comment by lprhodes** [comment]
Hey @jgrantfletcher, it looks like you're not on the latest version. Can you check please?

I tried your config and all of the hex values are sent.

**Comment by jgrantfletcher** [comment]
That was it. Updated and all is working perfectly.

Thanks.
