### ISSUE TITLE
Crash homebridge.user.storagePath()

### ISSUE THREAD

**Issue by donev77** [lprhodes/homebridge-broadlink-rm#329]
macOS 10.11.6
node v9.5.0
homebridge 0.4.38
homebridge-broadlink-rm 3.4.0

[2018-3-23 13:48:28] [Broadlink RM] Initializing BroadlinkRM platform...
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:6
    homebridgeDirectory = homebridge.user.storagePath()
    ^

ReferenceError: homebridge is not defined
    at Object.init (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:6:5)
    at new HomebridgePlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:15:21)
    at new BroadlinkRMPlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:31:5)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

**Comment by lprhodes** [comment]
Sorry there was an issue with the release - fixed in 3.4.1
