### ISSUE TITLE
Stateless switch request

### ISSUE THREAD

**Issue by xdenneboom** [lprhodes/homebridge-broadlink-rm#358]
Hi @lprhodes , 

Any chance we could see something like a stateless switch, or autoOff with X duration without sending the value?

Because I'm using these switches for automation in Homekit itself, I can only choose to enable, or disable these switches in Homekit automation. This means I would never be able to run the automation twice in a row, as the switch would remain in its last set state and Homekit automation will ignore the switch when already on (or off). 

To get around this, I'm using the pingIPAddress and pingIPAddressStateOnly. I just have to make sure there's no IP being pinged, so I can get the switch back off without sending any value.

Maybe good to know: I'm using the Broadlink-RM to control my Apple TV rather than my TV itself. 

				{
					"name": "TV pause",
					"type": "switch",
					"pingIPAddress": "fakeIP",
					"pingIPAddressStateOnly": true,
					"pingFrequency": 5,
					"data": {
						"on": "HEX_PLAYPAUSE_VALUE",
						"off": "HEX_PLAYPAUSE_VALUE"
					}
				},
				{
					"name": "TV mute",
					"type": "switch",
					"pingIPAddress": "fakeIP",
					"pingIPAddressStateOnly": true,
					"pingFrequency": 5,
					"data": {
						"on": "HEX_MUTE_VALUE",
						"off": "HEX_MUTE_VALUE"
					}
				}

Also, thanks for keeping up the good work! I'm a long time user of this plugin and it's helping me with a lot of stuff in house.

**Comment by xdenneboom** [comment]
this makes sense. I'll apply this. Thanks!

**Comment by xdenneboom** [comment]
Thanks again!

**Comment by deeloke** [comment]
Yes macaddictcr is right. This example crashes homebridge Version 1.1.0:

Light toggle setSwitchState: false
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: [ERROR]: Light toggle sendData (HEX value is missing)
    at module.exports (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/sendData.js:7:3)
    at SwitchAccessory.performRepeatSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:74:7)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:55:20
    at catchDelayCancelError (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at SwitchAccessory.performSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:50:11)
    at SwitchAccessory.setSwitchState (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/switch.js:105:29)
    at SwitchAccessory.setCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/accessory.js:139:10)
    at On.emit (events.js:310:20)
    at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at On.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:356:23)
    at Switch.Service._this.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:179:43)
    at ServiceManager.setCharacteristic (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/serviceManager.js:19:18)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/switch.js:137:24
    at catchDelayCancelError (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:14)
    at SwitchAccessory.checkAutoOff (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/switch.js:127:5)
 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: [ERROR]: Light toggle sendData (HEX value is missing)
    at module.exports (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/sendData.js:7:3)
    at SwitchAccessory.performRepeatSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:74:7)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:55:20
    at catchDelayCancelError (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:20)
    at SwitchAccessory.performSend (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/accessory.js:50:11)
    at SwitchAccessory.setSwitchState (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/switch.js:105:29)
    at SwitchAccessory.setCharacteristicValue (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/homebridge-platform-helper/accessory.js:139:10)
    at On.emit (events.js:310:20)
    at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at On.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:356:23)
    at Switch.Service._this.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:179:43)
    at ServiceManager.setCharacteristic (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/serviceManager.js:19:18)
    at /usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/switch.js:137:24
    at catchDelayCancelError (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/helpers/catchDelayCancelError.js:8:14)
    at SwitchAccessory.checkAutoOff (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/accessories/switch.js:127:5)
 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '=='
}
[6/17/2020, 11:06:10 PM] Got SIGTERM, shutting down Homebridge...
