### ISSUE TITLE
"Numeric values should look like this" error after plugin upgrade

### ISSUE THREAD

**Issue by dessmith** [lprhodes/homebridge-broadlink-rm#363]
I just upgraded to v3.5.5 of homebridge-broadlink-rm coming from v2.7.something or earlier.
I'm also using version of 0.4.38 of Homebridge.

On startup I'm now getting the "Numeric values should look like this" error, however I don't know which values it's complaining about, below I have shown the error and also my config.

Can you please let me know what values I should change?

I've seen other threads on this issue and have also made changes to "defaultHeatTemperature" and other values to stop them from being strings, but I'm still running into this error.

Also on this version the error is stating "log(`\x1b[31m[CONFIG ERROR]\x1b[0m ${name}Numeric values should look like this: \x1b[32m"${key}": ${value}\x1b[0m not this \x1b[31m"${key}": "${value}"\x1b[0m`);", but previous versions like 3.5.0 shows the human readable error of "Numeric values should look like this"

Thanks.

**Error output**
`[2018-4-20 21:00:43] Loaded config.json with 0 accessories and 1 platforms.
[2018-4-20 21:00:43] ---
[2018-4-20 21:00:43] Loading 1 platforms...
[2018-4-20 21:00:43] [Broadlink RM] Initializing BroadlinkRM platform...
[2018-4-20 21:00:43] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:72
        log(`\x1b[31m[CONFIG ERROR]\x1b[0m ${name}Numeric values should look like this: \x1b[32m"${key}": ${value}\x1b[0m not this \x1b[31m"${key}": "${value}"\x1b[0m`);
        ^

ReferenceError: log is not defined
    at Object.keys.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:72:9)
    at Array.forEach (<anonymous>:null:null)
    at AirConAccessory.checkConfig (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:54:25)
    at new HomebridgeAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:35:10)
    at new BroadlinkRMAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at new AirConAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:15:5)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:65:32)
    at Array.forEach (<anonymous>:null:null)
    at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:60:24)
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:28:10)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

**Config.json**
`{
  "bridge": {
    "name": "Homebridge",
    "username": "CD:21:3D:E3:CE:31",
    "port": 51826,
    "pin": "031-45-157"
  },
  "description": "Homebridge",
  "accessories": [],
  "platforms": [
    {
      "platform": "BroadlinkRM",
      "name": "Broadlink RM",
      "hideScanFrequencyButton": true,
      "hideLearnButton": true,
      "accessories": [
        {
          "name": "Learn Code",
          "type": "learn-code",
          "host": "192.168.1.72"
        },
        {
          "name": "BedAir",
          "type": "air-conditioner",
          "host": "192.168.1.71",
          "defaultCoolTemperature": 24,
          "heatTemperature": 30,
          "data": {
            "off": "2600ca00de6e0f280f290e0d0f0d0f280f0d0e290f280f280f0d0f0c0f0d0f0d0e290f0b100d0f280f0d0f0c0e0e0f280f0d0f0c0f0d0e0d0f0d0f0d0f280f0b100d0f0d0e0e0d0e0f280f0d0f0c0f0d0f0d0e0d0f0d0f0d0e0d0f0d0e29100b0f0d0f0d0e290f00033d0f0815270f0d0e0d0f0d0f280f0d0e0d0f0d0e0e0d0e0f0d0e0d0f0d0f0d0e290e0d0f0d0f0c0f0d0f280f280f0d0f280f0d0f0d0e0d0f0d0e0d0f0d0f0d0e0d0f280f0d0f280f280f0d0f0d0e290e290f280f0d0e290f0d0e0d0f280e2a0e290e000d050000000000000000000000000000",
            "temperature19": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f0f280f290e0d0f0d0f280f0d0e290f280f280f0d0f0c0f0e0e0d0f280f0c0f0d0f280f0d0f0d0d2a0e290f0c0f0d0f0d0e290f280f0d0f0c0f0d0f0d0e0b110d0e0d0f280f0d0f0d0e0d0f0d0f0d0f0c0f0d0e0d0f280f290e0d0f0d0f0d0e290f00033d100c0f280f0d0e0d0f0d0f280f0d0e0d0f0d0f0d0e0d0f0d0e0d0f0d0f0d0e290f0c0f0d0f0d0e0d10270f290e0d0f280f0d0f0d0e0b110d0e0d0f0d0f09120d0f0d0f280f0d0e290f280f0d0e290f0d0e290e0d100c0f280f280f0d0f0d0e0d0f000d050000000000000000000000000000"
            },
            "temperature20": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f10270f290e0d100c0e290f0d0e290f280f280f0d0f0c0f0d0f0e0d290f0c100d0f270f0d0f0c0f290e290f0c100c0f0e0e0c0f0d0f28100c0f0c100c0f0d0f0c0f0d0e290f0c0f0d0f0d0e0d0f0d100b0f0d0f0d0e290f280f0d0e0d100c0f280e00033f0f0c0f280f0d0f0d0e0d10270f0d0f0e0d0d0f0d0f0c0f0d0f0d0e0d0f0d0f280f0d0e0d0f0d0f0d0e290f280f0c0f290e0d0f0d0f0c0f0b110d0e0d0f0d0f0d0e0d0f280f0d0f280f280f0d0f280f0d0f0c100c0f0d0e290f280f0d0f0c0f0d0f000d050000000000000000000000000000"
            },
            "temperature21": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f0f290e290f0d0e0d0f280f0d0f280f280f290e0d0f0d0e0d0f0d0f280f0d0f0c0f290e0d0f0d0f280f280f0d0f0c0f0d0f280f0d0f280f0d0e0d0f0d0f0c0f0d0f0d0e290f0d0e0d0f0d0e0d0f0d0f0c0f0d0f0d0e290f280f0d0e0d0f0d0f280f00033d100c0f280f0d0f0d0e0d0f280f0d0f0d0e0d0f0d0e0d0f0d0f0d0e0d0f0d0f280f0d0e0d0f0d0f0c0f290e290f0c0f290e0d0f0d0f0c0f0d0f0d0e0d0f0d0f0c0f290e290f0c0f290e290f0c0f290e0d0f0e0e280f280f280f290e0d0f0d0f0c0f000d050000000000000000000000000000"
            },
            "temperature22": {
              "pseudo-mode": "cool",
              "data": "2600ca00de6e0f280f290e0d0f0d0f280f0d0f280f280f280f0d0f0d0e0d0f0d0e29100c0e0d10270f0d0f0d0e290f280f0d0e0d0f0d0f0d0f280e290f0d0e0d0f0d0f0c0f0d0f0e0d290f0a110e0e0d0e0e0e0d0f0c0f0d0f0d0e0d0f290e0d0f0d0f0c0f280f00033e100c0e29100c0e0d0f0d0e29100c0e0d0f0e0e0b110c100c0e0e0e0d0e0d0f290e0e0f0d0f0b0f0d0e290f280f0d10270f0d0f0d0e0e0e0d0e0e0e0e0f0c0e0e0f0c0e0e0e290e0e0e0e0d29100c0f280f0c0f0d0f0d0e0d100c0f0c0f290e290f000d050000000000000000000000000000"
            },
            "temperature23": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f0f290e290f0c0f0d0f280f0d10270f2810270f0d100c0e0d0f0d0f280f0d0f0c10280e0d0f0d0f2810270f0e0e0c100c11260f280f290f0d0e0d0f0d100b0f0d0e0d0f280f0d0f0d0e0d0f0b100d0f0d100c0e0d0f0e0d290f0d0f0d0e0e0d2a0c00033f100c0f28100c0e0d0f0d0f280f0d0f0c100c0f0d0f0c0f0d0f0c0f0d0f0d0e29100b0f0e0e0e0e0d0f270f290e0d1027100d0f0c0e0d0f0e0e0d0e0d0f0d0f0d0e0e0e2810270f28100c0f280f0b112810270f0d102710270f0d0f0c0f290f280f000d050000000000000000000000000000"
            },
            "temperature24": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd700f280f280f0d0f0d0f270f0d0f280f2810280f0c0f0d0f0d0e0d0f28100c100b0f290f0c0f0d0f2810270f0e0e0d0e0e0e0d0f0c100c10270f0d0e0d100d0e0d0e0d0f280f0e0e0d0e0e0e0e0d0e0e0e0e0c0f0e0e0d0f280f0c0f0d100c0e290e00033e100c0f280f0d0e0d0f0d0e290f0d0e0d0f0d0f0c100d0e0d0e0d0f0d0f0c0f290e0d100c0f0d0e0d0f280f28100c10270f0d0f0d0e0e0f0c0e0d0f0d0f0c0f0d10270f0d0f280f0d0f28100c0e0d10270f280f0d0f280f0d0f280f0d0f280f280f000d050000000000000000000000000000"
            },
            "temperature25": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f10280f280f0c0f0e0e280f0d102710271027100d0e0d0f0d0e0e0c2a100d0c0e10270f0d0f0d0e290f280f0d0f0c0f0d0f280f0e0d0d0f28100c100d0d0e0e0d0f0c0f290f0c0f0d0f0c0f0e0e0d0e0e0e0d0f0d0e0d1027100d0d0e0d0e10270f00033e100912280f0d0d0f0c0f0d2a0f0c100d0d0e0e0e0e0d0d0f0e0d0f0d0e0e0d29100c0e0d100c0f0a11290e29100c0f280e0d100d0e0d0d0f0e0e0d0e0e0e0d0e0f280e290f0e0c0e100d0d290f0d10270f0d0c2b0e290e0d0f0d0f0e0d290f2810000d050000000000000000000000000000"
            },
            "temperature26": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f10280f280f0d0e0d10280e0d0f280f2810280e0d0f0d0e0d0f0d0f280f0d0e0d0f290f0c0f0e0e2810270f0d0f0c100c0f0d0e290e0d10280f0d0e0d0e0d0f0d0f0d0e290e0e0c100e0d0e0e0e0d0e0d100c0f0d0e0e0e280f0d0f0d0f0c0f280e00033f0f0c11270e0d100c0f0c0f29100b0f0d0e0d0f0d0f0d0e0e0e0d0e0e0e0d0f280f0d0f0d0e0d0f0d0e290f28100c0f290d0e0e0d100c0d0e0f0d0e0e0c0f0f0d0e290f280f0d0f0c0f0e0c2a100c0e290f280f0c10280f0d0e0d0f0d0e290f2810000d050000000000000000000000000000"
            },
            "temperature27": {
              "pseudo-mode": "cool",
              "data": "2600ca00de6e102710280e0d100d0d290f0d0e290f281027100c0f0d0e0d0f0d0f280f0c100c0f28100c0f0c0f290f280f0c100c0f0d0e290f28100713290f0c0f0d0f0d0e0e0c100d29100c0e0d100d0d0e0e0e0e0e0c0f0d0f0d0e0e290e0d0f0e0e0d0d2a0e00033e100c0f28100c0e0d100c0f280f0d0e0d100c0f0c0f0d0f0e0c0e0f0e0d0e0c2b0e0d0f0e0d0d0f0e0e280f290e0d0f280f0d0e0d0f0d0f0e0c0e0f0d0f0d0e0d0f280f28100c0f0d0e0d10280e0d0f28100d0e0d0d2a0e0d0f0e0e0d0e290d2a0f000d050000000000000000000000000000"
            },
            "temperature28": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f102710270f0d0f0e0d290f0c0f290e291027100b0f0d100d0d0d0f290f0c0f0d0f280f0d0f0d0c2a10280e0d0f0d100c0f0c0f0e0c2a10270f0d0f0c0f0d100c0f0c10270f0e0c100d0d0f0e0c0e100c100c0e0d0f0d0f28100c0f0d0d0f0d290d00033f0f0d0f280f0d0f0c0f0e0d29100c0f0d0d0f0e0d0e0d0f0d0f0d0e0e0c0f0e290f0d0f0c0f0d0e0d0f290e290e0d0f290e0d0f0e0d0e0e0e0e0d0e0d0f0d0e0e0e0e0d290f0d0f0d0d0e0f290d0e0e290f0e0d0d0f290f0d0e0d0e0d10280e290f000d050000000000000000000000000000"
            }
          }
        },
        {
          "name": "LRAir",
          "type": "air-conditioner",
          "host": "192.168.1.72",
          "defaultCoolTemperature": 24,
          "defaultHeatTemperature": 28,
          "data": {
            "heatTemperature": 30,
            "off": "2600ca00de6e0f280f290e0d0f0d0f280f0d0e290f280f280f0d0f0c0f0d0f0d0e290f0b100d0f280f0d0f0c0e0e0f280f0d0f0c0f0d0e0d0f0d0f0d0f280f0b100d0f0d0e0e0d0e0f280f0d0f0c0f0d0f0d0e0d0f0d0f0d0e0d0f0d0e29100b0f0d0f0d0e290f00033d0f0815270f0d0e0d0f0d0f280f0d0e0d0f0d0e0e0d0e0f0d0e0d0f0d0f0d0e290e0d0f0d0f0c0f0d0f280f280f0d0f280f0d0f0d0e0d0f0d0e0d0f0d0f0d0e0d0f280f0d0f280f280f0d0f0d0e290e290f280f0d0e290f0d0e0d0f280e2a0e290e000d050000000000000000000000000000",
            "temperature19": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f0f280f290e0d0f0d0f280f0d0e290f280f280f0d0f0c0f0e0e0d0f280f0c0f0d0f280f0d0f0d0d2a0e290f0c0f0d0f0d0e290f280f0d0f0c0f0d0f0d0e0b110d0e0d0f280f0d0f0d0e0d0f0d0f0d0f0c0f0d0e0d0f280f290e0d0f0d0f0d0e290f00033d100c0f280f0d0e0d0f0d0f280f0d0e0d0f0d0f0d0e0d0f0d0e0d0f0d0f0d0e290f0c0f0d0f0d0e0d10270f290e0d0f280f0d0f0d0e0b110d0e0d0f0d0f09120d0f0d0f280f0d0e290f280f0d0e290f0d0e290e0d100c0f280f280f0d0f0d0e0d0f000d050000000000000000000000000000"
            },
            "temperature20": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f10270f290e0d100c0e290f0d0e290f280f280f0d0f0c0f0d0f0e0d290f0c100d0f270f0d0f0c0f290e290f0c100c0f0e0e0c0f0d0f28100c0f0c100c0f0d0f0c0f0d0e290f0c0f0d0f0d0e0d0f0d100b0f0d0f0d0e290f280f0d0e0d100c0f280e00033f0f0c0f280f0d0f0d0e0d10270f0d0f0e0d0d0f0d0f0c0f0d0f0d0e0d0f0d0f280f0d0e0d0f0d0f0d0e290f280f0c0f290e0d0f0d0f0c0f0b110d0e0d0f0d0f0d0e0d0f280f0d0f280f280f0d0f280f0d0f0c100c0f0d0e290f280f0d0f0c0f0d0f000d050000000000000000000000000000"
            },
            "temperature21": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f0f290e290f0d0e0d0f280f0d0f280f280f290e0d0f0d0e0d0f0d0f280f0d0f0c0f290e0d0f0d0f280f280f0d0f0c0f0d0f280f0d0f280f0d0e0d0f0d0f0c0f0d0f0d0e290f0d0e0d0f0d0e0d0f0d0f0c0f0d0f0d0e290f280f0d0e0d0f0d0f280f00033d100c0f280f0d0f0d0e0d0f280f0d0f0d0e0d0f0d0e0d0f0d0f0d0e0d0f0d0f280f0d0e0d0f0d0f0c0f290e290f0c0f290e0d0f0d0f0c0f0d0f0d0e0d0f0d0f0c0f290e290f0c0f290e290f0c0f290e0d0f0e0e280f280f280f290e0d0f0d0f0c0f000d050000000000000000000000000000"
            },
            "temperature22": {
              "pseudo-mode": "cool",
              "data": "2600ca00de6e0f280f290e0d0f0d0f280f0d0f280f280f280f0d0f0d0e0d0f0d0e29100c0e0d10270f0d0f0d0e290f280f0d0e0d0f0d0f0d0f280e290f0d0e0d0f0d0f0c0f0d0f0e0d290f0a110e0e0d0e0e0e0d0f0c0f0d0f0d0e0d0f290e0d0f0d0f0c0f280f00033e100c0e29100c0e0d0f0d0e29100c0e0d0f0e0e0b110c100c0e0e0e0d0e0d0f290e0e0f0d0f0b0f0d0e290f280f0d10270f0d0f0d0e0e0e0d0e0e0e0e0f0c0e0e0f0c0e0e0e290e0e0e0e0d29100c0f280f0c0f0d0f0d0e0d100c0f0c0f290e290f000d050000000000000000000000000000"
            },
            "temperature23": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f0f290e290f0c0f0d0f280f0d10270f2810270f0d100c0e0d0f0d0f280f0d0f0c10280e0d0f0d0f2810270f0e0e0c100c11260f280f290f0d0e0d0f0d100b0f0d0e0d0f280f0d0f0d0e0d0f0b100d0f0d100c0e0d0f0e0d290f0d0f0d0e0e0d2a0c00033f100c0f28100c0e0d0f0d0f280f0d0f0c100c0f0d0f0c0f0d0f0c0f0d0f0d0e29100b0f0e0e0e0e0d0f270f290e0d1027100d0f0c0e0d0f0e0e0d0e0d0f0d0f0d0e0e0e2810270f28100c0f280f0b112810270f0d102710270f0d0f0c0f290f280f000d050000000000000000000000000000"
            },
            "temperature24": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd700f280f280f0d0f0d0f270f0d0f280f2810280f0c0f0d0f0d0e0d0f28100c100b0f290f0c0f0d0f2810270f0e0e0d0e0e0e0d0f0c100c10270f0d0e0d100d0e0d0e0d0f280f0e0e0d0e0e0e0e0d0e0e0e0e0c0f0e0e0d0f280f0c0f0d100c0e290e00033e100c0f280f0d0e0d0f0d0e290f0d0e0d0f0d0f0c100d0e0d0e0d0f0d0f0c0f290e0d100c0f0d0e0d0f280f28100c10270f0d0f0d0e0e0f0c0e0d0f0d0f0c0f0d10270f0d0f280f0d0f28100c0e0d10270f280f0d0f280f0d0f280f0d0f280f280f000d050000000000000000000000000000"
            },
            "temperature25": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f10280f280f0c0f0e0e280f0d102710271027100d0e0d0f0d0e0e0c2a100d0c0e10270f0d0f0d0e290f280f0d0f0c0f0d0f280f0e0d0d0f28100c100d0d0e0e0d0f0c0f290f0c0f0d0f0c0f0e0e0d0e0e0e0d0f0d0e0d1027100d0d0e0d0e10270f00033e100912280f0d0d0f0c0f0d2a0f0c100d0d0e0e0e0e0d0d0f0e0d0f0d0e0e0d29100c0e0d100c0f0a11290e29100c0f280e0d100d0e0d0d0f0e0e0d0e0e0e0d0e0f280e290f0e0c0e100d0d290f0d10270f0d0c2b0e290e0d0f0d0f0e0d290f2810000d050000000000000000000000000000"
            },
            "temperature26": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f10280f280f0d0e0d10280e0d0f280f2810280e0d0f0d0e0d0f0d0f280f0d0e0d0f290f0c0f0e0e2810270f0d0f0c100c0f0d0e290e0d10280f0d0e0d0e0d0f0d0f0d0e290e0e0c100e0d0e0e0e0d0e0d100c0f0d0e0e0e280f0d0f0d0f0c0f280e00033f0f0c11270e0d100c0f0c0f29100b0f0d0e0d0f0d0f0d0e0e0e0d0e0e0e0d0f280f0d0f0d0e0d0f0d0e290f28100c0f290d0e0e0d100c0d0e0f0d0e0e0c0f0f0d0e290f280f0d0f0c0f0e0c2a100c0e290f280f0c10280f0d0e0d0f0d0e290f2810000d050000000000000000000000000000"
            },
            "temperature27": {
              "pseudo-mode": "cool",
              "data": "2600ca00de6e102710280e0d100d0d290f0d0e290f281027100c0f0d0e0d0f0d0f280f0c100c0f28100c0f0c0f290f280f0c100c0f0d0e290f28100713290f0c0f0d0f0d0e0e0c100d29100c0e0d100d0d0e0e0e0e0e0c0f0d0f0d0e0e290e0d0f0e0e0d0d2a0e00033e100c0f28100c0e0d100c0f280f0d0e0d100c0f0c0f0d0f0e0c0e0f0e0d0e0c2b0e0d0f0e0d0d0f0e0e280f290e0d0f280f0d0e0d0f0d0f0e0c0e0f0d0f0d0e0d0f280f28100c0f0d0e0d10280e0d0f28100d0e0d0d2a0e0d0f0e0e0d0e290d2a0f000d050000000000000000000000000000"
            },
            "temperature28": {
              "pseudo-mode": "cool",
              "data": "2600ca00dd6f102710270f0d0f0e0d290f0c0f290e291027100b0f0d100d0d0d0f290f0c0f0d0f280f0d0f0d0c2a10280e0d0f0d100c0f0c0f0e0c2a10270f0d0f0c0f0d100c0f0c10270f0e0c100d0d0f0e0c0e100c100c0e0d0f0d0f28100c0f0d0d0f0d290d00033f0f0d0f280f0d0f0c0f0e0d29100c0f0d0d0f0e0d0e0d0f0d0f0d0e0e0c0f0e290f0d0f0c0f0d0e0d0f290e290e0d0f290e0d0f0e0d0e0e0e0e0d0e0d0f0d0e0e0e0e0d290f0d0f0d0d0e0f290d0e0e290f0e0d0d0f290f0d0e0d0e0d10280e290f000d050000000000000000000000000000"
            }
          }
        }
      ]
    }
  ]
}`

**Comment by dessmith** [comment]
Actually think I'm having config file issues. I'm running homebridge via command line and not the service I setup which points to a different config file 👍

**Comment by dessmith** [comment]
Thanks @cubilon turns out I was loading homebridge via command line after I upgraded and forgot that homebridge looks for a config file in ~/.homebridge/ so it was using an old version of my config.

So removing the strings from the numerical values and your change for heatTemperature done the trick 👍
