### ISSUE TITLE
Homebridge does not start anymore

### ISSUE THREAD

**Issue by felipesalomao** [lprhodes/homebridge-broadlink-rm#365]
it  was working fine on raspberry pi until 2 days ago.. But now it isnt starting anymore, see log. Any help would be welcome..

```
root@raspberrypi:~# homebridge start
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-4-26 03:52:19] Loaded plugin: homebridge-broadlink-rm
[2018-4-26 03:52:19] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2018-4-26 03:52:19] ---
[2018-4-26 03:52:19] Loaded plugin: homebridge-homeassistant
[2018-4-26 03:52:19] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2018-4-26 03:52:19] ---
[2018-4-26 03:52:20] Loaded plugin: homebridge-lgtv-2012
[2018-4-26 03:52:20] Registering accessory 'homebridge-lgtv-2012.lgtv-2012'
[2018-4-26 03:52:20] ---
[2018-4-26 03:52:20] Loaded plugin: homebridge-switcheroo
[2018-4-26 03:52:20] Registering accessory 'homebridge-switcheroo.Switcheroo'
[2018-4-26 03:52:20] ---
[2018-4-26 03:52:20] Loaded config.json with 0 accessories and 1 platforms.
[2018-4-26 03:52:20] ---
[2018-4-26 03:52:20] Loading 1 platforms...
[2018-4-26 03:52:20] [Broadlink RM] Initializing BroadlinkRM platform...
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:666
            throw Error('[PARSE-ERROR] ' + file + ' does not look like a valid storage file!');
            ^

Error: [PARSE-ERROR] /root/.homebridge/plugin-persist/homebridge-broadlink-rm/dc914ad836a7024bc1d7c33f384fa37a does not look like a valid storage file!
    at LocalStorage.parseFileSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:666:19)
    at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:615:26)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:142:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/node-persist.js:37:32)
    at Object.init (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:9:15)
    at BroadlinkRMPlatform.HomebridgePlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:15:21)
    at BroadlinkRMPlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:31:5)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

root@raspberrypi:~#
```

**Comment by felipetng** [comment]
Felipe, como consigo falar com você?

**Comment by felipesalomao** [comment]
Por aqui mesmo.. Algo específico? Consegui resolver esse issue.. Salvei meu arquivo config e deletei os arquivos temporários.

**Comment by JefersonSchramm** [comment]
Boa noite. Como resolver isso definitivamente? O meu homebridge volta e meia para e não inicia mais. Está rodando por systemd. Para voltar a funcionar, eu preciso remover os arquivos com o comando "rm -rf /var/lib/homebridge/plugin-persist/homebridge-broadlink-rm/" que ele volta a funcionar. Mas está um saco ter que toda hora fazer isso.
