### ISSUE TITLE
can't start broadlink RM plugin

### ISSUE THREAD

**Issue by tombenetin** [lprhodes/homebridge-broadlink-rm#373]
Hi, after installing homebridge i set a few plugins without problem, but after installing broadlink RM it cant start, can you help me? thanks

`[5/13/2018, 9:10:04 AM] [Broadlink RM] Initializing BroadlinkRM platform...
[5/13/2018, 9:10:04 AM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:58
        log(`\x1b[31m[CONFIG ERROR]\x1b[0m ${name}Boolean values should look like this: \x1b[32m"${key}": ${value}\x1b[0m not this \x1b[31m"${key}": "${value}"\x1b[0m`);
        ^

ReferenceError: log is not defined
    at Object.keys.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:58:9)
    at Array.forEach (native)
    at SwitchAccessory.checkConfig (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:54:25)
    at SwitchAccessory.HomebridgeAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:35:10)
    at BroadlinkRMAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at SwitchAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:10:5)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:65:32)
    at Array.forEach (native)
    at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:60:24)
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:28:10)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
`

**Comment by cubilon** [comment]
can you please post your config?

**Comment by noaht8um** [comment]
@cubilon I can; I'm having the exact same error.

**Error:**
```
[2018-6-5 21:11:04] [Broadlink RM] Initializing BroadlinkRM platform...
[2018-6-5 21:11:04] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.

/homebridge/node_modules/homebridge-platform-helper/accessory.js:58
        log(`\x1b[31m[CONFIG ERROR]\x1b[0m ${name}Boolean values should look like this: \x1b[32m"${key}": ${value}\x1b[0m not this \x1b[31m"${key}": "${value}"\x1b[0m`);
        ^
ReferenceError: log is not defined
    at Object.keys.forEach (/homebridge/node_modules/homebridge-platform-helper/accessory.js:58:9)
    at Array.forEach (<anonymous>)
    at SwitchAccessory.checkConfig (/homebridge/node_modules/homebridge-platform-helper/accessory.js:54:25)
    at new HomebridgeAccessory (/homebridge/node_modules/homebridge-platform-helper/accessory.js:35:10)
    at new BroadlinkRMAccessory (/homebridge/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at new SwitchAccessory (/homebridge/node_modules/homebridge-broadlink-rm/accessories/switch.js:10:5)
    at config.accessories.forEach (/homebridge/node_modules/homebridge-broadlink-rm/platform.js:65:32)
    at Array.forEach (<anonymous>)
    at BroadlinkRMPlatform.addAccessories (/homebridge/node_modules/homebridge-broadlink-rm/platform.js:60:24)
    at BroadlinkRMPlatform.accessories (/homebridge/node_modules/homebridge-platform-helper/platform.js:28:10)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```


**sanitized config.json:**
```
{
    "bridge": {
        "name": "HomeBridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [
        {
            "accessory": "DenonMarantzAVR",
            "name": "TV Speakers",
            "ip": "X.X.X.X",
            "defaultInput": "TV",
            "defaultVolume": 20,
            "minVolume": 0,
            "maxVolume": 75,
            "doPolling": true,
            "pollingInterval": 10
        },
        {
            "accessory": "marantz-volume",
            "name": "X Volume",
            "host": "X.X.X.X"
        }
    ],
    "platforms": [
        {
            "platform": "Hue",
            "name": "Hue",
            "users": {
                "XXXXXXXXXXXXXX": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            },
            "sensors": true,
            "excludeSensorTypes": [
                "Daylight",
                "CLIP",
                "Geofence",
                "ZLLSwitch"
            ],
            "lights": true
        },
        {
            "platform": "IFTTT",
            "name": "IFTTT",
            "makerkey": "xxxxxxxxxxxxxxxxxxxxxxxx",
            "accessories": [
                {
                    "name": "X Location",
                    "buttons": [
                        {
                            "caption": "X is home",
                            "trigger": "X_enter_home"
                        },
                        {
                            "caption": "X left home",
                            "trigger": "X_exit_home"
                        }
                    ]
                }
            ]
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": true,
            "hideLearnButton": true,
            "accessories": [
                {
                    "name": "X Power",
                    "type": "switch",
                    "disableAutomaticOff": "false",
                    "data": {
                        "on": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                        "off": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                    }
                }
            ]
        }
    ]
}
```

**Comment by cubilon** [comment]
"false" goes without quotation marks.

**Comment by noaht8um** [comment]
Ah, that makes sense.

Unfortunately, my docker host bit the dust and I didn't have a backup (won't be making that mistake again).

Once I get Homebridge up and running again, I'll report back.
