### ISSUE TITLE
turnOnWhenOff doesn't work as expected

### ISSUE THREAD

**Issue by vladasbarisas** [lprhodes/homebridge-broadlink-rm#379]
Hi all, 
I'm trying to get my AC to play nicely with this plugin, however when I try to turn the AC on using Siri this module seemingly only sends a temperature command, without first sending the "on" command. I have _turnOnWhenOff_ set to true, however it only turns the AC on in the interface without actually sending the command.

Here's what happens when I try to press "Auto" from an off state:
```
[InfraRed] Aircon setTargetHeatingCoolingState: 3
[InfraRed] Aircon Potential sendTemperature (0)
[InfraRed] Aircon sendTemperature (0, auto)
[InfraRed] Aircon setTargetTemperature: 0
[InfraRed] Aircon setTargetTemperature: already 0 (no data sent - B)
[InfraRed] Aircon sendHex (192.168.1.44; E4:87:91:6F:07:BC)
[InfraRed] Aircon setCurrentHeatingCoolingState: 2
[InfraRed] Aircon setTargetHeatingCoolingState: 3
[InfraRed] Aircon setTargetHeatingCoolingState: already 3 (no data sent - B)
```

Config file snippet:
```
{
	"platform": "BroadlinkRM",
	"name": "InfraRed",
	"hideScanFrequencyButton": false,
	"hideLearnButton": false,
	"accessories": [
	{
		"name": "Aircon",
		"type": "air-conditioner",
		"turnOnWhenOff": true,
		"defaultHeatTemperature": 2,
		"defaultColdTemperature": -2,
		"minTemperature": -7,
		"maxTemperature": 7,
		"pseudoDeviceTemperature": 0,
		"data": {
			"on": "...",
			"off": "...",
			"temperature-7": {
				"pseudo-mode": "cold",
				"data": "..."
			},
			"temperature-6": {
				"pseudo-mode": "cold",
				"data": "..."
			},
			"temperature-5": {
				"pseudo-mode": "cold",
				"data": "..."
			},
			"temperature-4": {
				"pseudo-mode": "cold",
				"data": "..."
			},
			"temperature-3": {
				"pseudo-mode": "cold",
				"data": "..."
			},
			"temperature-2": {
				"pseudo-mode": "cold",
				"data": "..."
			},
			"temperature-1": {
				"pseudo-mode": "cold",
				"data": "..."
			},
			"temperature0": {
				"pseudo-mode": "auto",
				"data": "..."
			},
			"temperature1": {
				"pseudo-mode": "heat",
				"data": "..."
			},
			"temperature2": {
				"pseudo-mode": "heat",
				"data": "..."
			},
			"temperature3": {
				"pseudo-mode": "heat",
				"data": "..."
			},
			"temperature4": {
				"pseudo-mode": "heat",
				"data": "..."
			},
			"temperature5": {
				"pseudo-mode": "heat",
				"data": "..."
			},
			"temperature6": {
				"pseudo-mode": "heat",
				"data": "..."
			},
			"temperature7": {
				"pseudo-mode": "heat",
				"data": "..."
			}
		}
	},
```

I tried using debug mode for the accessory but that doesn't work either:
```
[InfraRed] Initializing BroadlinkRM platform...
/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:8
    if (config.debug) this.debug = true
                      ^
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new BroadlinkRMAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:8:23)
    at new AirConAccessory (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:21:5)
    at config.accessories.forEach (/usr/lib/node_modules/homebridge-broadlink-rm/index.js:49:32)
    at Array.forEach (<anonymous>)
    at BroadlinkRMPlatform.addAccessories (/usr/lib/node_modules/homebridge-broadlink-rm/index.js:44:24)
    at BroadlinkRMPlatform.accessories (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:27:10)
    at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:364:20)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:308:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
```

**Comment by vladasbarisas** [comment]
Update: it works now. I'm not sure what made it work though, here's my current configuration:
```
{
	"name": "AC",
	"type": "air-conditioner",
	"defaultCoolTemperature": 22,
	"defaultHeatTemperature": 28,
	"heatTemperature": 26,
	"pseudoDeviceTemperature": 23,
	"minTemperature": 10,
	"maxTemperature": 32,
	"turnOnWhenOff": true,
	"preventResendHex": false,
	"data": {
		"on": "...",
		"auto": "...",
		"off": "...",
		"temperature32": {
			"pseudo-mode": "heat",
			"data": "..."
		},
		...
	}
}
```

Closing ticket as resolved.
