### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by bebeboy** [lprhodes/homebridge-broadlink-rm#38]
I got the following error when loading with the new npm package.  Is that something wrong with my config? 

2017-04-06 06:19:29	stdout	[37m[4/6/2017, 6:19:29 AM][39m [1m[31m====================[39m[22m
2017-04-06 06:19:29	stdout	    at Module._compile (module.js:556:32)[39m[22m
2017-04-06 06:19:29	stdout	    at Object.<anonymous> (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:1:92)
2017-04-06 06:19:29	stdout	    at require (internal/module.js:20:19)
2017-04-06 06:19:29	stdout	    at Module.require (module.js:483:17)
2017-04-06 06:19:29	stdout	    at Function.Module._load (module.js:424:3)
2017-04-06 06:19:29	stdout	    at tryModuleLoad (module.js:432:12)
2017-04-06 06:19:29	stdout	    at Module.load (module.js:473:32)
2017-04-06 06:19:29	stdout	    at Object.Module._extensions..js (module.js:565:10)
2017-04-06 06:19:29	stdout	    at Module._compile (module.js:528:28)
2017-04-06 06:19:29	stdout	    at Object.exports.runInThisContext (vm.js:76:16)
2017-04-06 06:19:29	stdout	SyntaxError: Unexpected identifier
2017-04-06 06:19:29	stdout	        ^^^^^^^^^^^^^^^^^^^^^^
2017-04-06 06:19:29	stdout	  async setCharacteristicValue (props, on, callback) {
2017-04-06 06:19:29	stdout	[37m[4/6/2017, 6:19:29 AM][39m [1m[31m/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:34
2017-04-06 06:19:29	stdout	[37m[4/6/2017, 6:19:29 AM][39m [1m[31mERROR LOADING PLUGIN homebridge-broadlink-rm:[39m[22m

**Comment by lprhodes** [comment]
Upgrade node to latest

**Comment by bebeboy** [comment]
Hi Iprhodes,

I have upgraded the node.js (tried v7.6, v7.8 and v7.9) but somehow encountered different issue.  Can you please give me some advises?
 
date	stream	content
2017-04-12 18:00:49	stdout	    at Module.load (module.js:488:32)
2017-04-12 18:00:49	stdout	    at Object.Module._extensions..js (module.js:580:10)
2017-04-12 18:00:49	stdout	    at Module._compile (module.js:571:32)
2017-04-12 18:00:49	stdout	    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
2017-04-12 18:00:49	stdout	    at require (internal/module.js:20:19)
2017-04-12 18:00:49	stdout	    at Module.require (module.js:498:17)
2017-04-12 18:00:49	stdout	    at Function.Module._load (module.js:439:3)
2017-04-12 18:00:49	stdout	    at tryModuleLoad (module.js:447:12)
2017-04-12 18:00:49	stdout	    at Module.load (module.js:488:32)
2017-04-12 18:00:49	stdout	    at Object.Module._extensions..node (module.js:598:18)
2017-04-12 18:00:49	stdout	the module (for instance, using `npm rebuild` or`npm install`).
2017-04-12 18:00:49	stdout	NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
2017-04-12 18:00:49	stdout	NODE_MODULE_VERSION 48. This version of Node.js requires
2017-04-12 18:00:49	stdout	was compiled against a different Node.js version using
2017-04-12 18:00:49	stdout	Error: The module '/usr/lib/node_modules/homebridge/node_modules/mdns/build/Release/dns_sd_bindings.node'
2017-04-12 18:00:49	stdout	
2017-04-12 18:00:49	stdout	    ^
2017-04-12 18:00:49	stdout	    throw ex;
2017-04-12 18:00:49	stdout	/usr/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
2017-04-12 18:00:38	stdout	
2017-04-12 18:00:38	stdout	  `-- [40m[33mbroadlinkjs@0.1.0[39m[49m  (git+https://github.com/lprhodes/broadlinkjs.git#a463147a6a71855722221da0f74adcba86d7bb5b)
