### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by linru2000** [lprhodes/homebridge-broadlink-rm#41]
Hi, 

I'm a beginner to homebridge. When I try to launch homebridge with Broadlink plugin, it always has error like this:

Loaded plugin: homebridge-broadlink-rm
[2017-4-9 03:39:11] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2017-4-9 03:39:11] ---
[2017-4-9 03:39:11] Loaded config.json with 0 accessories and 1 platforms.
[2017-4-9 03:39:11] ---
[2017-4-9 03:39:11] Loading 1 platforms...
[2017-4-9 03:39:11] [Broadlink RM 2] Initializing BroadlinkRM platform...
[2017-4-9 03:39:11] [Broadlink RM 2] No accessories have been added to the Broadlink RM config. Only the Learn IR accessory will be accessible on HomeKit.
[2017-4-9 03:39:11] [Broadlink RM 2] Initializing platform accessory 'Learn IR'...
[2017-4-9 03:39:11] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:`
                       
    ┌────────────┐     
    │ 031-45-xxx │     
    └────────────┘     
                       
[2017-4-9 03:39:11] Homebridge is running on port 53xxx.
Discovered Broadlink RM device at 10.0.1.xx (xx:xx:xx:xx:xx:xx)
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98
        dev.device();
            ^
TypeError: dev.device is not a function
    at module.exports.Broadlink.genDevice (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98:13)
    at Socket.cs.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:187:29)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:545:8)

And this is my config file:

{
  "bridge":{
    "name":"Homebridge",
    "username":"xx:22:xx:xx:xx:xx",
    "port":53xxx,
    "pin":"031-4x-xxx"
  },
  "description":"Homebridge",
  "accessories":[
  ],
  "platforms":[
    {
      "platform":"BroadlinkRM",
      "name":"Broadlink RM 2",
      "accessories":[
      ]
    }
  ]
}

I ran homebridge on Mac with 10.12.4, Node 7.8. I tried installing Wemo plugin and it works. Then I deleted all stuff and started to setup broadlink. However,  every time it said: TypeError: dev.device is not a function. 

Could you help me ?

Thank you.

**Comment by lprhodes** [comment]
Hey - looks like there's a device in your network that may not be fully supported. What Broadlink devices are on your network?

**Comment by linru2000** [comment]
My Device is PM Pro with lots of TC 2 switch.

**Comment by alasak1** [comment]
I have the same issue 'TypeError: dev.device is not a function'.
Besides the RM Pro, I do have an A1, SP1, S1 and TC2 devices. Turns out S1 seems to be the device causing the error. I turned off my S1 and the error goes away. It seems the S1 is not supported in broadlinkjs yet.

**Comment by linru2000** [comment]
Follow your hints, I checked my wifi and found Dooya Automated Curtains is also named as Broadlink_Dooya. 
I block it in my wifi and error goes away.  
Thank you.

**Comment by lprhodes** [comment]
I'll update the version of broadlinkjs I'm using to exclude it and other non-rm devices tomorrow
