### ISSUE TITLE
homebridge crashing when broadlnik rm module is present in config.json

### ISSUE THREAD

**Issue by sigma696** [lprhodes/homebridge-broadlink-rm#410]
Hi, whenever I add to my config file this portion to try broadlink rm the whole homebridge crashes.
I'm running Win 10 64 Pro. The other modules work fine...
The part of my config.json:

"platforms": [{
		"platform": "BroadlinkRM",
		"name": "Broadlink RM",
		"hideScanFrequencyButton": false,
		"hideLearnButton": false,
    "homebridgeDirectory": "/Users/Admin/.homebridge",
		"accessories": [{
			"name": "TV On/Off",
			"type": "switch",
			"data": {

			}
		}]
	}]

The crash log:

[2018-7-24 23:35:12] [Broadlink RM] **************************************************************************************************************
[2018-7-24 23:35:13] [Broadlink RM]
C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\ping\lib\parser\win.js:56
        this._times.push(parseFloat(match[1], 10));
                                         ^

TypeError: Cannot read property '1' of null
    at WinParser._processBody (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\ping\lib\parser\win.js:56:42)
    at WinParser.parser.eat (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\ping\lib\parser\base.js:125:14)
    at C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\underscore\underscore.js:76:21
    at Function._.each._.forEach (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\underscore\underscore.js:186:9)
    at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-broadlink-rm\node_modules\ping\lib\ping-promise.js:76:12)
    at Object.onceWrapper (events.js:272:13)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

C:\Users\Admin\AppData\Roaming\npm>

**Comment by tomdrumdrum** [comment]
Did you solve your problem and how? I have the same issue.

**Comment by sigma696** [comment]
No, I gave up on it . Reinstalled to a VM

чт, 31 янв. 2019 г. в 5:37, tomdrumdrum <notifications@github.com>:

**Comment by lprhodes** [comment]
As of 3.6.11 I'm using a new ping module, hopefully this resolves your issue.
