### ISSUE TITLE
homebridge is broken

### ISSUE THREAD

**Issue by yclai1229** [lprhodes/homebridge-broadlink-rm#430]
This error has kept my homebridge stopped,I have restart to continue...can you help me how to solve it?  

Thanks a lot!

  Error: error:0606508A:digital envelope routines:EVP_DecryptFinal_ex:data not multiple of block length
    at Decipheriv.final (internal/crypto/cipher.js:104:26)
    at Socket.socket.on (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:258:27)
    at Socket.emit (events.js:180:13)
    at UDP.onMessage (dgram.js:659:8)

**Comment by yclai1229** [comment]
please help me🙏....

**Comment by lprhodes** [comment]
As this is an old issue I'm going to close it, please re-open if you're still experiencing problems.
