### ISSUE TITLE
homebridge-platform-helper package.json does not contain the keyword 'homebridge-plugin'. - homebridge will not run.

### ISSUE THREAD

**Issue by Pensive** [lprhodes/homebridge-broadlink-rm#435]
Hi there

Homebridge fails to boot when i enable the homebridge-broadlink-rm package. I'm on node 8.11.4

I have a working installation of homebridge on a docker in synology. It's running homebridge-apple-tv, homebridge-samsung-tizen v1.0.4 and homebridge-config-ui-x plugins just fine and it "successfully" installed homebridge-broadlink-rm - however when i run it I get the following error whether i use the hosts ip settings or leave it to autodetect:

```
[2018-9-15 15:06:24] Loaded config.json with 0 accessories and 3 platforms.
[2018-9-15 15:06:24] ---
[2018-9-15 15:06:24] Plugin /homebridge/node_modules/homebridge-platform-helper package.json does not contain the keyword 'homebridge-plugin'.
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-9-15 15:06:25] Loaded plugin: homebridge-apple-tv
[2018-9-15 15:06:25] Registering platform 'homebridge-apple-tv.AppleTV'
[2018-9-15 15:06:25] ---
[2018-9-15 15:06:25] Loaded plugin: homebridge-broadlink-rm
[2018-9-15 15:06:25] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[2018-9-15 15:06:25] ---
[2018-9-15 15:06:25] Loaded plugin: homebridge-samsung-tizen
[2018-9-15 15:06:25] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[2018-9-15 15:06:25] ---
[2018-9-15 15:06:25] Loaded plugin: homebridge-config-ui-x
[2018-9-15 15:06:25] Registering platform 'homebridge-config-ui-x.config'
[2018-9-15 15:06:25] ---
[2018-9-15 15:06:25] Loading 3 platforms...
[2018-9-15 15:06:25] [Apple TV] Initializing AppleTV platform...
[2018-9-15 15:06:25] [Apple TV] [INFO] Automatically discovering Apple TV's
[2018-9-15 15:06:25] [Broadlink RM] Initializing BroadlinkRM platform...
[2018-9-15 15:06:25] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.

/homebridge/node_modules/homebridge-platform-helper/accessory.js:72
        log(`\x1b[31m[CONFIG ERROR]\x1b[0m ${name}Numeric values should look like this: \x1b[32m"${key}": ${value}\x1b[0m not this \x1b[31m"${key}": "${value}"\x1b[0m`);
        ^
ReferenceError: log is not defined
    at Object.keys.forEach (/homebridge/node_modules/homebridge-platform-helper/accessory.js:72:9)
    at Array.forEach (<anonymous>)
    at SwitchAccessory.checkConfig (/homebridge/node_modules/homebridge-platform-helper/accessory.js:54:25)
    at Object.keys.forEach (/homebridge/node_modules/homebridge-platform-helper/accessory.js:66:14)
    at Array.forEach (<anonymous>)
    at SwitchAccessory.checkConfig (/homebridge/node_modules/homebridge-platform-helper/accessory.js:54:25)
    at new HomebridgeAccessory (/homebridge/node_modules/homebridge-platform-helper/accessory.js:35:10)
    at new BroadlinkRMAccessory (/homebridge/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at new SwitchAccessory (/homebridge/node_modules/homebridge-broadlink-rm/accessories/switch.js:10:5)
    at config.accessories.forEach (/homebridge/node_modules/homebridge-broadlink-rm/platform.js:65:32)
    at Array.forEach (<anonymous>)
    at BroadlinkRMPlatform.addAccessories (/homebridge/node_modules/homebridge-broadlink-rm/platform.js:60:24)
    at BroadlinkRMPlatform.accessories (/homebridge/node_modules/homebridge-platform-helper/platform.js:28:10)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:330:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

removing the platform reference causes homebridge to go back to proper operation. Am i missing a dependency? I would have thought so but it looks like the function is required by multiple packages which is why i think there might be an error in the installation. I tried a reinstall of the plugin and it did not help.

A little perplexing.

config.json sanitised:
```
{
    "bridge": {
        "name": "NAME",
        "username": "USERNAME,
        "port": 51826,
        "pin": "XXX-XX-XXX"
    },
    "description": "DESCRIPTION",
    "accessories": [],
    "platforms": [
        {
            "platform": "AppleTV",
            "name": "Apple TV",
            "devices": [
                {
                    "id": "lounge",
                    "name": "Lounge Apple TV",
                    "credentials": "CREDENTIALS"
                }
            ],
            "accessories": [],
            "showDefaultSwitches": true
        },
        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "accessories": [
                {
                    "name": "Yamaha AVR",
                    "type": "switch",
                    "data": {
                        "on": "2600500000012",
                        "off": "2600500000012"
                    }
                }
            ]
        },
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "TV",
                    "ip": "192.168.95.95",
                    "mac": "FF:FF:FF:FF:FF:FF",
                    "switches": [
                        {
                            "name": "TV Off",
                            "command": "KEY_POWER"
                        },
                        {
                            "name": "FreeSat",
                            "command": "KEY_DTV"
                        },
                        {
                            "name": "Apple TV",
                            "command": "KEY_HDMI1",
                            "power": true
                        },
                        {
                            "name": "Blu Ray",
                            "command": "KEY_HDMI2",
                            "power": true
                        },
                        {
                            "name": "XBox",
                            "command": "KEY_HDMI3",
                            "power": true
                        },
                        {
                            "name": "AVR",
                            "command": "KEY_HDMI4",
                            "power": true
                        },
                        {
                            "name": "BBC One HD",
                            "channel": 106,
                            "power": true
                        },
                        {
                            "name": "BBC Two HD",
                            "channel": 102,
                            "power": true
                        },
                        {
                            "name": "BBC Four HD",
                            "channel": 107,
                            "power": true
                        },
                        {
                            "name": "Channel 4 SD",
                            "channel": 104,
                            "power": true
                        },
                        {
                            "name": "ITV HD",
                            "channel": 111,
                            "power": true
                        },
                        {
                            "name": "ITV 2 SD",
                            "channel": 113,
                            "power": true
                        },
                        {
                            "name": "ITV 3 SD",
                            "channel": 115,
                            "power": true
                        },
                        {
                            "name": "ITV 4 SD",
                            "channel": 117,
                            "power": true
                        },
                        {
                            "name": "Sky News",
                            "channel": 202,
                            "power": true
                        },
                        {
                            "name": "5 HD",
                            "channel": 105,
                            "power": true
                        },
                        {
                            "name": "BBC News HD",
                            "channel": 200,
                            "power": true
                        },
                        {
                            "name": "Dave SD",
                            "channel": 157,
                            "power": true
                        },
                        {
                            "name": "CBBC HD",
                            "channel": 600,
                            "power": true
                        },
                        {
                            "name": "CBeebies HD",
                            "channel": 601,
                            "power": true
                        },
                        {
                            "name": "CITV SD",
                            "channel": 602,
                            "power": true
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by Pensive** [comment]
Just tried it on a temporary homebridge install on a macbook in terminal, similar error:

```
[16/09/2018, 10:43:41] Loaded config.json with 1 accessories and 2 platforms.
[16/09/2018, 10:43:41] ---
[16/09/2018, 10:43:41] Loaded plugin: homebridge-apple-tv
[16/09/2018, 10:43:41] Registering platform 'homebridge-apple-tv.AppleTV'
[16/09/2018, 10:43:41] ---
[16/09/2018, 10:43:41] Loaded plugin: homebridge-broadlink-rm
[16/09/2018, 10:43:41] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[16/09/2018, 10:43:41] ---
[16/09/2018, 10:43:41] Loaded plugin: homebridge-dacp
[16/09/2018, 10:43:41] Registering platform 'homebridge-dacp.DACP'
[16/09/2018, 10:43:41] ---
[16/09/2018, 10:43:41] Loaded plugin: homebridge-http-irblaster
[16/09/2018, 10:43:41] Registering accessory 'homebridge-http-irblaster.http-irblaster'
[16/09/2018, 10:43:41] ---
[16/09/2018, 10:43:41] Loaded plugin: homebridge-philipshue
[16/09/2018, 10:43:41] Registering platform 'homebridge-philipshue.PhilipsHue'
[16/09/2018, 10:43:41] ---
[16/09/2018, 10:43:42] Loaded plugin: homebridge-plex
[16/09/2018, 10:43:42] Registering accessory 'homebridge-plex.Plex'
[16/09/2018, 10:43:42] ---
[16/09/2018, 10:43:42] Loaded plugin: homebridge-samsung-remote
[16/09/2018, 10:43:42] Registering accessory 'homebridge-samsung-remote.SamsungTV'
[16/09/2018, 10:43:42] ---
[16/09/2018, 10:43:42] Loading 2 platforms...
[16/09/2018, 10:43:42] [Apple TV] Initializing AppleTV platform...
[16/09/2018, 10:43:42] [Apple TV] [INFO] Automatically discovering Apple TV's
[16/09/2018, 10:43:42] [Broadlink RM] Initializing BroadlinkRM platform...
[16/09/2018, 10:43:42] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
Disconnected Apple TV's
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:72
        log(`\x1b[31m[CONFIG ERROR]\x1b[0m ${name}Numeric values should look like this: \x1b[32m"${key}": ${value}\x1b[0m not this \x1b[31m"${key}": "${value}"\x1b[0m`);
        ^

ReferenceError: log is not defined
    at Object.keys.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:72:9)
    at Array.forEach (<anonymous>:null:null)
    at SwitchAccessory.checkConfig (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:54:25)
    at Object.keys.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:66:14)
    at Array.forEach (<anonymous>:null:null)
    at SwitchAccessory.checkConfig (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:54:25)
    at new HomebridgeAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:35:10)
    at new BroadlinkRMAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at new SwitchAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:10:5)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:65:32)
    at Array.forEach (<anonymous>:null:null)
    at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:60:24)
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:28:10)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:385:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:329:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

**Comment by gid204** [comment]
After having this plugin working for many many months I needed to update it and Homebridge to fix another issue and now I am seeing this same issue.

Have you managed to solve it?

**Comment by gid204** [comment]
Fixed the issue - previously my fan accessory had "hidev1fan": "true" in the config. The new version needed me to take away the quotation marks around true.
