### ISSUE TITLE
Unhandled exception, air-con setting temperature

### ISSUE THREAD

**Issue by gchokov** [lprhodes/homebridge-broadlink-rm#467]
Air Conditioner sendTemperature (23
(node:13408) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at catchDelayCancelError (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:52:40)
    at catchDelayCancelError (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/catchDelayCancelError.js:8:20)
    at AirConAccessory.performSend (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:50:11)
    at AirConAccessory.sendTemperature (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:260:16)
    at <anonymous>:null:null

(node:13408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)

**Comment by lprhodes** [comment]
Hey, it looks like your config isn't set up quite right. Comment with your config and re-open if you're still facing issues.
