### ISSUE TITLE
Homebridge stop running after update

### ISSUE THREAD

**Issue by SzilagyiR** [lprhodes/homebridge-broadlink-rm#478]
Hi!

I use this plugin for years, without probelm, but yesterday itt stopped working, after I update my Pi.

The error massage:
[3/4/2019, 2:05:08 PM] [Broadlink RM] Initializing BroadlinkRM platform...
/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:647
            throw Error('[PARSE-ERROR] ' + file + ' does not look like a valid storage file!');
            ^
Error: [PARSE-ERROR] /root/.homebridge/plugin-persist/homebridge-broadlink-rm/33d6be66cf217ee1928d22ae1d245ca3 does not look like a valid storage file!
    at LocalStorage.parseFileSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:647:19)
    at LocalStorage.parseStorageDirSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:596:26)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/local-storage.js:141:14)
    at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/node-persist/src/node-persist.js:37:32)
    at Object.init (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/helpers/persistentState.js:10:15)
    at BroadlinkRMPlatform.HomebridgePlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/platform.js:14:21)
    at BroadlinkRMPlatform (/usr/local/lib/node_modules/homebridge-broadlink-rm/index.js:11:1)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:296:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)

Can anyone help me?

Thanks!

**Comment by natis97** [comment]
Had the same problem two days ago. **Hard but working**: Remove your Homebridge (= all devices too) from HomeKit and restart both systems. After adding the devices again all works fine. Did you also experience that Siri will perform commands related to Homebridge successfully, but tell you there was an error anyways? Greetings from Germany, may it help others :-)

**Comment by SzilagyiR** [comment]
Hi!

Thanks for the hint, but not working for me.
I put back my backup, than update again, and everything works fine!

Greetings from Hungary :)
