### ISSUE TITLE
unknow device RM pro plus, device type code: "27c3"

### ISSUE THREAD

**Issue by sfeng717** [lprhodes/homebridge-broadlink-rm#485]
We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "27c3".

**Comment by lprhodes** [comment]
Hey @sfeng717, this is now supported in the latest version.

**Comment by Snoomy** [comment]
doesn't seem so...
[1/16/2020, 2:46:27 AM] [Broadlink RM] 
[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "27c3". The device is connected to your network with the IP address "10.0.0.33".

[1/16/2020, 2:46:28 AM] [Broadlink RM] 
[1/16/2020, 2:46:28 AM] [Broadlink RM] **************************************************************************************************************
[1/16/2020, 2:46:28 AM] [Broadlink RM] ** Welcome to version 3.6.18 of the Homebridge Broadlink RM Plugin!

**Comment by lprhodes** [comment]
Can you confirm which Broadlink device it is please?

**Comment by Snoomy** [comment]
it's RM Pro+ (supporting both IR and RF)

**Comment by lprhodes** [comment]
Support added in 3.6.20

**Comment by Snoomy** [comment]
any ideas on what could it be with 3.6.20? in case I rollback to 3.6.18 it could at least start fine...

tired to reinstall all of them: homebridge, helper and plugin - doesn't help...

[1/16/2020, 9:30:33 PM] Loaded config.json with 0 accessories and 1 platform.
[1/16/2020, 9:30:33 PM] ---
[1/16/2020, 9:30:33 PM] Plugin /usr/local/lib/node_modules/homebridge-platform-helper package.json does not contain the keyword 'homebridge-plugin'.
[1/16/2020, 9:30:33 PM] Loaded plugin: homebridge-broadlink-rm
[1/16/2020, 9:30:33 PM] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
[1/16/2020, 9:30:33 PM] [Broadlink RM] Initializing BroadlinkRM platform...
[1/16/2020, 9:30:33 PM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
[1/16/2020, 9:30:33 PM] Loading 0 accessories...
(node:82907) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
(node:82907) UnhandledPromiseRejectionWarning: TypeError: this.setupServiceManager is not a function
    at new HomebridgeAccessory (/usr/local/lib/node_modules/homebridge-platform-helper/accessory.js:35:10)
    at new BroadlinkRMAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at new LearnIRAccessory (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/learnCode.js:17:5)
    at BroadlinkRMPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js:52:36)
    at BroadlinkRMPlatform.accessories (/usr/local/lib/node_modules/homebridge-platform-helper/platform.js:28:16)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:403:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:341:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

(node:82907) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82907) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/16/2020, 9:30:33 PM] [Broadlink RM] [INFO] Discovered Broadlink RM3 Pro (27c3) at 10.0.0.33 (77:0f:78:4d:f8:70)
[1/16/2020, 9:30:35 PM] [Broadlink RM] 
[1/16/2020, 9:30:35 PM] [Broadlink RM] **************************************************************************************************************
[1/16/2020, 9:30:35 PM] [Broadlink RM] ** Welcome to version 3.6.20 of the Homebridge Broadlink RM Plugin!

**Comment by lprhodes** [comment]
@Snoomy sorry I was coding a bit too late and missed something. 3.6.21 should fix it

**Comment by Snoomy** [comment]
maybe I'm doing something wrong?...

[1/16/2020, 11:20:42 PM] [Broadlink RM] Initializing BroadlinkRM platform...
[1/16/2020, 11:20:42 PM] [Broadlink RM] [INFO] Automatically discovering Broadlink RM devices.
[1/16/2020, 11:20:42 PM] Loading 0 accessories...
(node:1632) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
(node:1632) UnhandledPromiseRejectionWarning: ReferenceError: ervice is not defined
at serviceType (/Users/Snoomy/node_modules/homebridge-broadlink-rm/accessories/windowCovering.js:9:20)
at WindowCoveringAccessory.createServiceManager (/Users/Snoomy/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js:53:51)
at new HomebridgeAccessory (/Users/Snoomy/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js:42:36)
at new BroadlinkRMAccessory (/Users/Snoomy/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
at new WindowCoveringAccessory (/Users/Snoomy/node_modules/homebridge-broadlink-rm/accessories/windowCovering.js:7:1)
at config.accessories.forEach (/Users/Snoomy/node_modules/homebridge-broadlink-rm/platform.js:71:32)
at Array.forEach (:null:null)
at BroadlinkRMPlatform.addAccessories (/Users/Snoomy/node_modules/homebridge-broadlink-rm/platform.js:63:24)
at BroadlinkRMPlatform.accessories (/Users/Snoomy/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/platform.js:28:20)
at Server._loadPlatformAccessories (/Users/Snoomy/node_modules/homebridge/lib/server.js:403:20)
at Server._loadPlatforms (/Users/Snoomy/node_modules/homebridge/lib/server.js:341:16)
at Server.run (/Users/Snoomy/node_modules/homebridge/lib/server.js:90:36)
at module.exports (/Users/Snoomy/node_modules/homebridge/lib/cli.js:59:10)
at Object. (/Users/Snoomy/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
at startup (internal/bootstrap/node.js:282:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

(node:1632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/16/2020, 11:20:42 PM] [Broadlink RM] [INFO] Discovered Broadlink RM3 Pro (27c3) at 10.0.0.33 (77:0f:78:4d:f8:70)
[1/16/2020, 11:20:43 PM] [Broadlink RM]
[1/16/2020, 11:20:43 PM] [Broadlink RM] **************************************************************************************************************
[1/16/2020, 11:20:43 PM] [Broadlink RM] ** Welcome to version 3.6.21 of the Homebridge Broadlink RM Plugin!
[1/16/2020, 11:20:43 PM] [Broadlink RM] **

**Comment by Snoomy** [comment]
unistalling homebridge-platform-helper and reinstalling homebridge-broadlink-rm after also didn't help...

**Comment by lprhodes** [comment]
It's a different error.

Try 3.6.22, I didn't get the chance to test out the Window Covering sorry. The intention is that over the next week or so the code shall be in much better shape (and I shall be less tired :P)

**Comment by lprhodes** [comment]
If there are any further issues can you create a new issue with the details please

**Comment by Snoomy** [comment]
3.6.22 works fine now! thanks a lot!
