### ISSUE TITLE
Issues loading plugin with last update 

### ISSUE THREAD

**Issue by webpablo** [lprhodes/homebridge-broadlink-rm#51]
tried running install and update. Also tried uninstalling and reinstalling the plugin but all roads lead me here: 
====================
[4/19/2017, 7:59:14 AM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[4/19/2017, 7:59:14 AM] /usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:36
  async setCharacteristicValue (props, value, callback) {
        ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:1:92)
[4/19/2017, 7:59:14 AM] ====================

**Comment by lprhodes** [comment]
Update node - see README for version

**Comment by webpablo** [comment]
updated node + reinstalled home bridge and the plugin. deleted my persist folder. 
 ====================
[4/19/2017, 8:26:18 AM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[4/19/2017, 8:26:18 AM] /usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:36
  async setCharacteristicValue (props, value, callback) {
        ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:1:92)
[4/19/2017, 8:26:18 AM] ====================

**Comment by webpablo** [comment]
Just ran a clean setup on a brand new OS X install. 

installed node.js of OS X 
installed homebridge 
ran without issue 
installed broad link plugin 
 ====================
[4/19/2017, 10:09:13 AM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[4/19/2017, 10:09:13 AM] /usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:36
  async setCharacteristicValue (props, value, callback) {
        ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:1:92)
[4/19/2017, 10:09:13 AM] ====================

**Comment by lprhodes** [comment]
It's definitely the node version...check using the node -v

**Comment by webpablo** [comment]
AHHHH 
v6.10.2. 
I didn't realize there was a "for most users" and "latest" download page for node. ¯\_(ツ)_/¯ 
Sorry for the noise…
