### ISSUE TITLE
Learn RF not working

### ISSUE THREAD

**Issue by mbriney** [lprhodes/homebridge-broadlink-rm#514]
I have multiple Broadlink RM devices and the UDP doesn't seem to be working on my network so I have to use the learn-code function.  I'm trying to grab the RF codes off of my Broadcom RM3 Pro Plus.  Below is my config code.  

```
                {
                    "accessory": "Broadlink RM Learner",
                    "name": "Learn RF",
                    "type": "learn-code",
                    "scanFrequency": true,
                    "host": "192.168.7.188"
                },
```
It comes back with  showing that it found a frequency but it never prints out the results.

```
 [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
 [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
 [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
 [Broadlink RM] [INFO] Scan RF (stopped)
```
I've heard that you need to switch on the learn IR but when I have this custom learn-button it doesn't seem to provide the default buttons.  Is there a way to work around this?

**Comment by peterwooley** [comment]
Hey @mbriney! I ran into this issue just 15 hours after you reported it. I added the `learn-code` accessory after hooking up a BroadLink Pro and got the same result.

Thankfully, in #496 I found a recommendation to create a `hosts` array and set `"isRFSupported": true` to get around this issue. So, I added the array just above my `accessories` array, removed the  custom `learn-code` accessory, and was able to successfully learn an RF code by tapping the Learn accessory in the Home app.

This is what my `hosts` array looks like:
```
"hosts":[{
  "address": "xx.xx.xx.xx",
  "mac": "xx:xx:xx:xx:xx:xx",
  "isRFSupported": true
}]
```

Hope this helps!

**Comment by peterwooley** [comment]
While this is not ideal, I was able follow these steps to learn RF codes:

1. Ensure both the Scan Frequency and Learn buttons are configured to be shown in the Homebridge config file
2. Tap Scan Frequency in the Home app
3. Hold the button on my RF remote until "Scan RF (found frequency - 1 of 2)" appears in the Homebridge log
4. Tap Learn in the Home app
5. Tap and hold the button on my RF remote until "Scan RF (complete)" is shown followed by "Hex Code: ..." on the next line of the Homebridge log

**Comment by ascl00** [comment]
I see the same issue, and the above workaround stopped working after updating the firmware to v56.

**Comment by lprhodes** [comment]
@ascl00 v56 of what?

**Comment by ascl00** [comment]
Sorry, the RM Pro (device code 0x9d27) firmware.

**Comment by mbriney** [comment]
The issue here is definitely when you have multiple RM devices.  In my case, I even have multiple RM+ devices.  It would be really helpful if we could manually define the learn and scan RF codes and in each specify the IP address of the device, like in the example above.  The custom button with the scan frequency works just fine in finding the code but the lack then of the learn button makes it impossible to retrieve the code.

**Comment by lprhodes** [comment]
I'm still waiting on a new RM device to re-develop the RF learning fully but in the meantime I'll add some code that allows you to specify the IP of the RF Learn device (and more importantly, have it use it)

**Comment by lprhodes** [comment]
@mbriney This definitely works in order to choose a specific IP address for the learn device:

Add `"hideLearnButton": true` and `"hideScanFrequencyButton": true` to your config
Add accessories with the following types: `learn-ir` and `learn-code` and a `host` key with the ip-address

I've just pushed out release 3.6.17 which logs the device of the IP address Learn Code is associated with.

I _think_ I've fixed the issue with only step 1 occurring too but I can't test, can you give it a shot please?

**Comment by mbriney** [comment]
@lprhodes ok I've got 3.6.17 installed.  I can get it to target the learning on the right IP device now, it finds code 1 of 2 no problem.  But then when I click the learn it times out.  I suspect there may be an issue with the way I have configured the new button.  

Here are my two entries:

`                {
                    "accessory": "Scan RF",
                    "name": "Learn RF",
                    "type": "learn-ir",
                    "scanFrequency": true,
                    "host": "192.168.7.29"
                },
                {
                    "accessory": "Learn Code",
                    "name": "Learn Code",
                    "type": "learn-code",
                    "host": "192.168.7.29"
                }`

And above I have hideScanFrequencyButton and hideLearnButton set to true.

**Comment by lprhodes** [comment]
I don't think it should really matter but the type should be swapped for those two accessories.

Once you've done that can you try again and send me the logs please?

**Comment by mbriney** [comment]
Hmmm, here's the new accessory config:
`                {
                    "accessory": "Learn Code",
                    "name": "Learn Code",
                    "type": "learn-code",
                    "scanFrequency": true,
                    "host": "192.168.7.29"
                },
                {
                    "accessory": "Learn IR",
                    "name": "Learn IR",
                    "type": "learn-ir",
                    "host": "192.168.7.29"
                }`

It finds the code but doesn't ever seem to print to the log.
`[2020-1-7 20:25:48] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-7 20:25:48] [Broadlink RM] [INFO] Learn Code (stopped)
[2020-1-7 20:25:53] [Broadlink RM] [INFO] Learn Code initializing (192.168.7.29)
[2020-1-7 20:25:53] [Broadlink RM] Learn Code (ready)
[2020-1-7 20:25:54] [Broadlink RM] [INFO] Scan RF (scanning)
[2020-1-7 20:25:54] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-7 20:26:03] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-7 20:26:03] [Broadlink RM] [INFO] Learn Code (stopped)
[2020-1-7 20:26:15] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-7 20:26:16] [Broadlink RM] [INFO] Scan RF (stopped)
[2020-1-7 20:26:23] [Broadlink RM] [INFO] Scan RF (scanning)
[2020-1-7 20:26:23] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-7 20:26:25] [Broadlink RM] [INFO] Learn Code initializing (192.168.7.29)
[2020-1-7 20:26:25] [Broadlink RM] Learn Code (ready)
[2020-1-7 20:26:34] [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
[2020-1-7 20:26:35] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-7 20:26:35] [Broadlink RM] [INFO] Learn Code (stopped)
[2020-1-7 20:26:40] [Broadlink RM] [INFO] Learn Code initializing (192.168.7.29)
[2020-1-7 20:26:40] [Broadlink RM] Learn Code (ready)
[2020-1-7 20:26:44] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-7 20:26:45] [Broadlink RM] [INFO] Scan RF (stopped)
[2020-1-7 20:26:50] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-7 20:26:50] [Broadlink RM] [INFO] Learn Code (stopped)
[2020-1-7 20:26:52] [Broadlink RM] [INFO] Scan RF (scanning)
[2020-1-7 20:26:52] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-7 20:26:55] [Broadlink RM] [INFO] Learn Code initializing (192.168.7.29)
[2020-1-7 20:26:55] [Broadlink RM] Learn Code (ready)
[2020-1-7 20:27:05] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-7 20:27:05] [Broadlink RM] [INFO] Learn Code (stopped)
[2020-1-7 20:27:05] [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
[2020-1-7 20:27:13] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-7 20:27:14] [Broadlink RM] [INFO] Scan RF (stopped)
[2020-1-7 20:27:38] [Broadlink RM] [INFO] Scan RF (scanning)
[2020-1-7 20:27:38] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-7 20:27:39] [Broadlink RM] [INFO] Learn Code initializing (192.168.7.29)
[2020-1-7 20:27:39] [Broadlink RM] Learn Code (ready)
[2020-1-7 20:27:49] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-7 20:27:49] [Broadlink RM] [INFO] Learn Code (stopped)
[2020-1-7 20:27:55] [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
[2020-1-7 20:27:59] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-7 20:27:59] [Broadlink RM] [INFO] Scan RF (stopped)
[2020-1-7 20:28:04] [Broadlink RM] [INFO] Learn Code initializing (192.168.7.29)
[2020-1-7 20:28:04] [Broadlink RM] Learn Code (ready)
[2020-1-7 20:28:05] [Broadlink RM] [INFO] Scan RF (scanning)
[2020-1-7 20:28:05] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-7 20:28:14] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-7 20:28:14] [Broadlink RM] [INFO] Learn Code (stopped)
[2020-1-7 20:28:26] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-7 20:28:26] [Broadlink RM] [INFO] Scan RF (stopped)
[2020-1-7 20:28:30] [Broadlink RM] [INFO] Scan RF (scanning)
[2020-1-7 20:28:30] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-7 20:28:46] [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
[2020-1-7 20:28:47] [Broadlink RM] [INFO] Learn Code initializing (192.168.7.29)
[2020-1-7 20:28:47] [Broadlink RM] Learn Code (ready)
[2020-1-7 20:28:51] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-7 20:28:52] [Broadlink RM] [INFO] Scan RF (stopped)
[2020-1-7 20:28:57] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-7 20:28:57] [Broadlink RM] [INFO] Learn Code (stopped)`

**Comment by lprhodes** [comment]
Can you give 3.6.18 a go please and send more logs.

**Comment by stleeft** [comment]
Running latest RM Pro+ firmware v56 with this plugin v3.6.18.  Unfortunately no change for me.
IR works fine, but RF still times out as described by so many others.
The 2 RF remotes I tested with all scan (and work) fine in IOS apps "Broadlink", "e-Control" and "ihc For EU" but just cannot get it to work in homebridge as I cannot identify the correct HEX code.

Just FYI:
only app that allowed me to upgrade firmware was "Broadlink". Seems the most recent with ipad and limited Siri support via Shortcuts.
(https://apps.apple.com/app/broadlink/id1450257910)

I have the identical RF scanning issue using Broadlink Manager (https://sourceforge.net/projects/broadlink-manager/) so I do assume it is related to the new firmware.

Running minimal config for this testing:

{
            "platform": "BroadlinkRM",
            "name": "RM pro+",
            "debug": true,
            "accessories": [
                {
                    "name": "Learn RF",
                    "type": "learn-code",
                    "scanFrequency": true
                },
                {
                    "name": "Learn IR",
                    "type": "learn-ir"
                }
            ]
        }

Hope this helps.  If I can assist any further, please let me know. I would love to get this working :-)

[2020-1-8 12:57:32] [RM pro+] Initializing BroadlinkRM platform...
[2020-1-8 12:57:32] [RM pro+] [INFO] Automatically discovering Broadlink RM devices.
[2020-1-8 12:57:32] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:39756 (UDP)
[2020-1-8 12:57:32] [RM pro+] Initializing platform accessory 'Learn RF'...
[2020-1-8 12:57:32] [RM pro+] Initializing platform accessory 'Learn IR'...
[2020-1-8 12:57:32] [RM pro+] [INFO] Discovered Broadlink RM3 Pro Plus (279d) at 192.168.13.165 (77:0f:78:b9:32:4c)
[2020-1-8 12:57:33] [RM pro+]
[2020-1-8 12:57:33] [RM pro+] **************************************************************************************************************
[2020-1-8 12:57:33] [RM pro+] ** Welcome to version 3.6.18 of the Homebridge Broadlink RM Plugin!
[2020-1-8 12:57:33] [RM pro+] **
[2020-1-8 12:57:33] [RM pro+] ** Find out what's in the latest release here: https://github.com/lprhodes/homebridge-broadlink-rm/releases
[2020-1-8 12:57:33] [RM pro+] **
[2020-1-8 12:57:33] [RM pro+] ** If you like this plugin then please star it on GitHub or better yet
[2020-1-8 12:57:33] [RM pro+] ** buy me a drink using Paypal https://paypal.me/lprhodes or crypto https://goo.gl/bEn1RW.
[2020-1-8 12:57:33] [RM pro+] **
[2020-1-8 12:57:33] [RM pro+] ** Keep up to date with this plugin along with everything HomeKit and homebridge
[2020-1-8 12:57:33] [RM pro+] ** by signing up to my newsletter at http://workswith.io
[2020-1-8 12:57:33] [RM pro+] **
[2020-1-8 12:57:33] [RM pro+] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
[2020-1-8 12:57:33] [RM pro+] **
[2020-1-8 12:57:33] [RM pro+] **************************************************************************************************************
[2020-1-8 12:57:33] [RM pro+]
[2020-1-8 12:57:34] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:41405 (UDP)
[2020-1-8 12:57:36] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:50098 (UDP)
[2020-1-8 12:57:38] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:46056 (UDP)
[2020-1-8 12:57:40] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:59686 (UDP)
[2020-1-8 12:57:42] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:34767 (UDP)
[2020-1-8 12:57:44] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:60900 (UDP)
[2020-1-8 12:57:46] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:46473 (UDP)
[2020-1-8 12:57:48] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:40464 (UDP)
[2020-1-8 12:58:04] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:35088 (UDP)
[2020-1-8 12:58:06] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:45614 (UDP)
[2020-1-8 12:58:08] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:50503 (UDP)
[2020-1-8 12:58:10] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:43781 (UDP)
[2020-1-8 12:58:12] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:35591 (UDP)
[2020-1-8 12:58:14] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:37769 (UDP)
[2020-1-8 12:58:16] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:46643 (UDP)
[2020-1-8 12:58:18] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:52103 (UDP)
[2020-1-8 12:58:19] [RM pro+] [INFO] Learn Code initializing (undefined)
[2020-1-8 12:58:19] [RM pro+] Learn Code (ready)
[2020-1-8 12:58:20] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:38516 (UDP)
[2020-1-8 12:58:22] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:53897 (UDP)
[2020-1-8 12:58:23] [RM pro+] [RESULT] Learn Code (learned hex code: 260006016d350f0c0f0c0f27100c0f270f0c0f0d0f0b10270f270f0c100b100c0f270f27100b100c0f0c0f0c100b100c0f0c0f0c0f0c100c0f0c0f0c0f0c10270f0c0f0c0f0c100c0f0c0f0c0f0c10270f0c0f0c0f0c100c0f270f270f2710270f270f2710270f270f0c0f0c10270f0c0f0c0f0c100b100c0f0c0f0c100b10270f270f0c100b10270f0c0f0c100b100c0f270f27100b10270f270f0c100c0f0c0f0c0f0c100b100c0f0c0f27100b100c0f0c0f0c0f0c100c0f270f0c0f0c10270f0c0f0c100b10270f270f0c100c0f0c0f0c0f0c0f0c100c0f0c0f0c0f2710270f0c0f270f0c100c0f0c0f0c0f0c100c0f270f0c0f0c10270f270f0c0f280f270f0c0f2710270f000d050000)
[2020-1-8 12:58:23] [RM pro+] [INFO] Learn Code (complete)
[2020-1-8 12:58:23] [RM pro+] [INFO] Learn Code (stopped)
[2020-1-8 12:58:24] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:41759 (UDP)
[2020-1-8 12:58:26] [RM pro+] [INFO] Learn Code initializing (undefined)
[2020-1-8 12:58:26] [RM pro+] Learn Code (ready)
[2020-1-8 12:58:26] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:50105 (UDP)
[2020-1-8 12:58:28] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:47146 (UDP)
[2020-1-8 12:58:29] [RM pro+] [RESULT] Learn Code (learned hex code: 260076006e340f0c100c0f270f0c0f27100c0f0c0f0c0f271026100c0f0c0f0c0f271026100c0f0c0f0c0f0c100c0f0c0f0c0f0c100c0f0c0f0c0f0c100c0f270f0c0f0c0f0c100c0f0c0f0c0f0c10270f0c0f0c0f0c100b10270f0c0f0c0f0c100c0f0c0f0c0f27100c0f270f270f270f27102610270f000d050000)
[2020-1-8 12:58:29] [RM pro+] [INFO] Learn Code (complete)
[2020-1-8 12:58:29] [RM pro+] [INFO] Learn Code (stopped)
[2020-1-8 12:58:30] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:33218 (UDP)
[2020-1-8 12:58:32] [RM pro+] [INFO] Scan RF (scanning)
[2020-1-8 12:58:32] [RM pro+] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-8 12:58:32] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:46932 (UDP)
[2020-1-8 12:58:34] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:32986 (UDP)
[2020-1-8 12:58:35] [RM pro+] [INFO] Scan RF (found frequency - 1 of 2)
[2020-1-8 12:58:35] [RM pro+] [ACTION] Keep holding that button!
[2020-1-8 12:58:36] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:36165 (UDP)
[2020-1-8 12:58:38] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:60117 (UDP)
[2020-1-8 12:58:40] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:34754 (UDP)
[2020-1-8 12:58:42] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:38291 (UDP)
[2020-1-8 12:58:44] [RM pro+] [INFO] Listening for Broadlink devices on 192.168.13.24:48685 (UDP)
[2020-1-8 12:58:53] [RM pro+] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-8 12:58:53] [RM pro+] [INFO] Scan RF (stopped)
[2020-1-8 12:59:00] [RM pro+] [INFO] Scan RF (scanning)
[2020-1-8 12:59:00] [RM pro+] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-8 12:59:02] [RM pro+] [INFO] Scan RF (found frequency - 1 of 2)
[2020-1-8 12:59:02] [RM pro+] [ACTION] Keep holding that button!
[2020-1-8 12:59:21] [RM pro+] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-8 12:59:21] [RM pro+] [INFO] Scan RF (stopped)

**Comment by mbriney** [comment]
Seeing something similar with the RF and the 3.6.17 version.  It scans and it says it finds it but then doesn't log the code.  

[2020-1-8 21:48:52] [Broadlink RM] [INFO] Scan RF (scanning)
[2020-1-8 21:48:52] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-8 21:49:01] [Google Smart Home] Sending Sync Request
[2020-1-8 21:49:02] [Google Smart Home] Received SYNC intent
[2020-1-8 21:49:13] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-8 21:49:13] [Broadlink RM] [INFO] Scan RF (stopped)
[2020-1-8 21:49:16] [Broadlink RM] [INFO] Learn Code initializing (192.168.7.29)
[2020-1-8 21:49:16] [Broadlink RM] Learn Code (ready)
[2020-1-8 21:49:17] [Broadlink RM] [INFO] Scan RF (scanning)
[2020-1-8 21:49:17] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2020-1-8 21:49:26] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[2020-1-8 21:49:26] [Broadlink RM] [INFO] Learn Code (stopped)
[2020-1-8 21:49:38] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2020-1-8 21:49:38] [Broadlink RM] [INFO] Scan RF (stopped)

**Comment by ascl00** [comment]
@lprhodes this would be a whole lot easier if you had one of these devices. Do you have one on order? If not, maybe I can get one to you?

**Comment by lprhodes** [comment]
Thanks @ascl00 I do have one coming on Wednesday :)

**Comment by ghost** [comment]
v3.6.22 seems to have improved the RF scanning issue for me in combination with the Broadlink RM3 Pro Plus (279d).
It did however introduce a slew of other issues but I already see separate issues logged for them:
- install failing due to missing git
- start failing due to missing hap-nodejs
- "pingIPAddress" giving me constant false positive of 'up'
- constant loops "Broadlink RM device is no longer reachable" <-> "has been re-discovered"

The RF codes registered in the logs are huge though (>2400 characters).  They work but seem to cause a 5 to 10 sec delay between the sendhex command in homebridge log and actual broadcast by Broadlink device. Not sure if that is related to your device buffer remark...

Anyways, the progress is appreciated. Thank you!  I can start experimenting with my automations :-)

**Comment by NexGen-3D-Printing** [comment]
I'm also having this issue, I just updated from the old 2018 version, RF Code learning worked perfectly, now on 3.6.22 and it doesn't work, I have only one hub, and its firmware version is 20025 which is old, the Broadlink IOS app works and can learn codes.

[2/13/2020, 1:43:47 AM] [Broadlink RM] [INFO] Scan RF (scanning)
[2/13/2020, 1:43:47 AM] [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
[2/13/2020, 1:43:51 AM] [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
[2/13/2020, 1:43:51 AM] [Broadlink RM] [ACTION] Keep holding that button!
[2/13/2020, 1:43:59 AM] [Broadlink RM] [INFO] Scan RF (found frequency - 2 of 2)
[2/13/2020, 1:43:59 AM] [Broadlink RM] [ACTION] Press the RF button multiple times with a pause between them.
[2/13/2020, 1:44:48 AM] [Broadlink RM] [INFO] Scan RF (stopped - 20s timeout)
[2/13/2020, 1:44:49 AM] [Broadlink RM] [INFO] Scan RF (stopped)

**Comment by NexGen-3D-Printing** [comment]
v3.6.22 doesn't work
v3.6.21 doesn't work
v3.6.16 works!

I suggest anyone who is have this issue, wind back one version at a time and test, the the developer can see what he may have changed to cause the issue.

Hope this helps ;)

**Comment by grabarz1986** [comment]
v3.6.22 in combination of Broadlink RM Pro+ and RM3 Mini doesn't work on Hoobs. The first one on firmware v44. Word around mentioned in this thread is crushing HomeBridge. 

[Homebridge] [2/14/2020, 18:27:45] [Broadlink RM] Schowek LearnCode IR getSwitchState: undefined[Homebridge] [2/14/2020, 18:27:45] [Broadlink RM] Apple TV On getSwitchState: false[Homebridge] [2/14/2020, 18:27:50] [Broadlink RM] Schowek LearnCode RF getSwitchState: undefined[Homebridge] [2/14/2020, 18:27:51] [Broadlink RM]  [35m[INFO] [0m Scan RF (scanning)[Homebridge] [2/14/2020, 18:27:51] [Broadlink RM]  [35m[ACTION] [0m Hold down the button that sends the RF frequency.[Homebridge] [2/14/2020, 18:27:54] [Broadlink RM]  [35m[INFO] [0m Scan RF (found frequency - 1 of 2)[Homebridge] [2/14/2020, 18:28:11] [Camera ffmpeg] Snapshot from Kamera Dahua at 480x270[Homebridge] [2/14/2020, 18:28:12] [Broadlink RM]  [35m[INFO] [0m Scan RF (stopped - 20s timeout)[Homebridge] [2/14/2020, 18:28:12] [Broadlink RM]  [35m[INFO] [0m Scan RF (stopped)[Homebridge] [2/14/2020, 18:28:15] [Camera ffmpeg] Snapshot from Kamera Dahua at 480x270[Homebridge] [2/14/2020, 18:28:22] [Broadlink RM] Schowek LearnCode RF getSwitchState: undefined[Homebridge] [2/14/2020, 18:28:22] [Broadlink RM]  [35m[INFO] [0m Scan RF (scanning)[Homebridge] [2/14/2020, 18:28:22] [Broadlink RM]  [35m[ACTION] [0m Hold down the button that sends the RF frequency.[Homebridge] [2/14/2020, 18:28:24] [Broadlink RM]  [35m[INFO] [0m Scan RF (found frequency - 1 of 2)[Homebridge] [2/14/2020, 18:28:26] [Broadlink RM] Schowek LearnCode IR getSwitchState: undefined[Homebridge] [2/14/2020, 18:28:26] [Broadlink RM]  [35m[INFO] [0m Scan RF (scanning)[Homebridge] [2/14/2020, 18:28:26] [Broadlink RM]  [35m[ACTION] [0m Hold down the button that sends the RF frequency.[Homebridge] [2/14/2020, 18:28:30] [Air Quality] AirNow Polling...[Homebridge] [2/14/2020, 18:28:31] [Air Quality] AirNow air quality AQI is: 90[Homebridge] [2/14/2020, 18:28:43] [Broadlink RM]  [35m[INFO] [0m Scan RF (stopped - 20s timeout)[Homebridge] [2/14/2020, 18:28:43] TypeError: closeClient is not a function at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/homebridge-broadlink-rm-tv/helpers/learnRFData.js:135:7) at listOnTimeout (internal/timers.js:531:17) at processTimers (internal/timers.js:475:7) [Homebridge] [2/14/2020, 18:28:43] Got SIGTERM, shutting down service...

**Comment by mwkchan** [comment]
> v3.6.22 doesn't work
> v3.6.21 doesn't work
> v3.6.16 works!
> 
> I suggest anyone who is have this issue, wind back one version at a time and test, the the developer can see what he may have changed to cause the issue.
> 
> Hope this helps ;)

@Kung-Foo-Kamel You are totally correct, no matter how I tried, nothing works for versions post 3.6.16. I reinstall my plugin to 3.6.16 and it worked immediately.

**Comment by NexGen-3D-Printing** [comment]
Yes, I'm still using that version, if it aint broke, don't fix it :)

**Comment by silviungs** [comment]
> Yes, I'm still using that version, if it aint broke, don't fix it :)

If I install the v3.6.16 plugin from terminal, it will not recognize it from config file. Can you let me know how I can make this work?
Also, with v3.6.22 I was able in the end to get the hex code for RF but it doesn't do anything. I can see the broadlink flashing but that is it. Nothing else happens.
Here is also my config:

{
    "platform": "BroadlinkRM",
    "name": "Broadlink RM",
    "hideScanFrequencyButton": false,
    "hideLearnButton": false,
    "hideWelcomeMessage": false,
    "accessories": [
        {
            "name": "AC On/Off",
            "type": "switch",
            "data": {
                "on": "260068…",
                "off": "260068…"
            }
        },
        {
            "name": "Light On/Off",
            "type": "switch",
            "data": {
                "on": "aa009a0000012….",
                "off": "aa009a0000012…."
            }
        }
    ]
}

The first one is an IR and the second is the RF one. Maybe this is my problem....

**Comment by EricS1019** [comment]
Same here I get a code form the learning button but when entering that code nothing is working.

**Comment by NexGen-3D-Printing** [comment]
I dont think he maintains this branch much anymore, there is some newer forks of this plugin that I use now.

Maybe give this one a go: https://github.com/newt10/homebridge-broadlink-rm-enhanced

**Comment by EricS1019** [comment]
Yeah that one does not work either. I just need to find out how to Learn my RF codes and then I can input them in the config file the learn command learns the wrong code that does not work. The new broadlink iPhone app learns the code on first try works every time I try it. I wish there was a way I could look inside the broadlink app and see the codes.

**Comment by NexGen-3D-Printing** [comment]
Have you tried rolling back a few versions, this is what I did originally, I captured the codes I needed, saved them then installed the newer version.

Like others, most have moved away from these 433 products to Zigbee gear, Ive been slowly pulling mine out as cost wise, Zigbee is just as cheap now.
