### ISSUE TITLE
Socket error in 3.6.11

### ISSUE THREAD

**Issue by ashtonaut** [lprhodes/homebridge-broadlink-rm#522]
Hi, everything works fine with 3.6.10, but when I install 3.6.11, I get a few warnings when installing, and then a permissions error when trying to run homebridge.

Install output as follows:

```
pi@loungepi:~$ sudo npm install -g --unsafe-perm homebridge-broadlink-rm@3.6.11
> raw-socket@1.7.0 install /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
In file included from ../src/raw.h:23,
                 from ../src/raw.cc:6:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../src/raw.h:21,
                 from ../src/raw.cc:6:
../src/raw.cc: At global scope:
/root/.cache/node-gyp/12.14.0/include/node/node.h:566:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.cache/node-gyp/12.14.0/include/node/node.h:600:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/raw.cc:55:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(raw, InitAll)
 ^~~~~~~~~~~
In file included from /root/.cache/node-gyp/12.14.0/include/node/node.h:63,
                 from ../src/raw.h:21,
                 from ../src/raw.cc:6:
/root/.cache/node-gyp/12.14.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/12.14.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/12.14.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callbac ’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/12.14.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/12.14.0/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/raw.node
  COPY Release/raw.node
make: Leaving directory '/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/build'
+ homebridge-broadlink-rm@3.6.11
added 6 packages from 11 contributors, removed 1 package and updated 6 packages in 30.227s
```

Output when running homebridge:

```
pi@loungepi:~ $ homebridge
[1/2/2020, 7:19:49 PM] Loaded config.json with 4 accessories and 4 platforms.
[1/2/2020, 7:19:49 PM] ---
[1/2/2020, 7:19:49 PM] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-broadlink-rm' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-broadlink-rm'.
[1/2/2020, 7:19:49 PM] Warning: skipping plugin found at '/usr/lib/node_modules/homebridge-camera-ffmpeg' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-camera-ffmpeg'.
[1/2/2020, 7:19:49 PM] ====================
[1/2/2020, 7:19:49 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[1/2/2020, 7:19:49 PM] Error: Operation not permitted
    at new Socket (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:147:20)
    at new Session (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:545:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:4:34)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[1/2/2020, 7:19:49 PM] ====================
[1/2/2020, 7:19:51 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/2/2020, 7:19:51 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/2/2020, 7:19:51 PM] ---
[1/2/2020, 7:19:51 PM] Loaded plugin: homebridge-garagedoor-command
[1/2/2020, 7:19:51 PM] Registering accessory 'homebridge-garagedoor-command.GarageCommand'
[1/2/2020, 7:19:51 PM] ---
[1/2/2020, 7:19:51 PM] Loaded plugin: homebridge-ds18b20
[1/2/2020, 7:19:51 PM] Registering accessory 'homebridge-temperature-ds18b20.DS18B20'
[1/2/2020, 7:19:51 PM] ---
[1/2/2020, 7:19:51 PM] Loaded plugin: homebridge-filesensor
[1/2/2020, 7:19:51 PM] Registering accessory 'homebridge-filesensor.FileSensor'
[1/2/2020, 7:19:51 PM] ---
[1/2/2020, 7:19:51 PM] Loaded plugin: homebridge-tplink-smarthome
[1/2/2020, 7:19:51 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[1/2/2020, 7:19:51 PM] ---
[1/2/2020, 7:19:51 PM] Loading 4 platforms...
[1/2/2020, 7:19:51 PM] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[1/2/2020, 7:19:51 PM] [TplinkSmarthome] homebridge-tplink-smarthome v4.0.1, node v12.14.0, homebridge v0.4.50
[1/2/2020, 7:19:51 PM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[1/2/2020, 7:19:51 PM] Got SIGTERM, shutting down Homebridge...
```

Rolling back to 3.6.10 makes these errors go away.

I'm running Raspbian Buster with Nodejs v13.5.0.

**Comment by lprhodes** [comment]
Hey @ashtonaut ,

It's due to doing device discovery in a more performant way.

This command should give node the privileges it needs:

`sudo setcap cap_net_raw+ep /usr/bin/node`

**Comment by ashtonaut** [comment]
Thanks for the quick response. I updated to 3.6.11, then ran that command, but I still get the same permissions error when trying to start homebridge - permissions error when trying to create a socket. Happy to provide further diagnostics if that would help.

**Comment by okonet** [comment]
I tried that with docker setup but nothing worked for me. I had to downgrade to 3.6.10 which took the whole installation down unfortunately. After a half a day I managed to recover but still don’t know how to use the latest version with the setcap
