### ISSUE TITLE
After latest updates gets error  Error: The requested platform 'BroadlinkRM' was not registered by any plugin.

### ISSUE THREAD

**Issue by yuickey** [lprhodes/homebridge-broadlink-rm#523]
Here's logs

`[1/2/2020, 6:09:03 PM] Loading 3 platforms...
[1/2/2020, 6:09:03 PM] [eWeLink] Initializing eWeLink platform...
[1/2/2020, 6:09:03 PM] [eWeLink] Intialising eWeLink
[1/2/2020, 6:09:03 PM] [eWeLink] Found 0 group(s)
[1/2/2020, 6:09:03 PM] [Config] Initializing config platform...
[1/2/2020, 6:09:03 PM] [Config] Running in Standalone Mode.
[1/2/2020, 6:09:03 PM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[1/2/2020, 6:09:03 PM] Got SIGTERM, shutting down Homebridge...`

`        {
            "platform": "BroadlinkRM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "accessories": [
                {
                    "name": "Learn mini",
                    "type": "learn-code",
                    "host": "192.168.1.156"
                },
                {
                    "name": "Learn pro",
                    "type": "learn-code",
                    "host": "192.168.1.155"
                },
                {
                    "name": "Air Conditioner",
                    "type": "switch",
                    "host": "192.168.1.156",
                    "data": {
                        "on": "2600800...",
                        "off": "2600800..."
                    }
                },
                {
                    "name": "COLD 24",
                    "type": "switch",
                    "host": "192.168.1.156",
                    "data": {
                        "on": "2600800...",
                        "off": "2600800..."
                    }
                },
                {
                    "name": "COLD 23",
                    "type": "switch",
                    "host": "192.168.1.156",
                    "data": {
                        "on": "2600800...",
                        "off": "2600800..."
                    }
                },
                {
                    "name": "HEAT 25",
                    "type": "switch",
                    "host": "192.168.1.156",
                    "data": {
                        "on": "2600800...",
                        "off": "2600800..."
                    }
                },
                {
                    "name": "HEAT 23",
                    "type": "switch",
                    "host": "192.168.1.156",
                    "data": {
                        "on": "2600800...",
                        "off": "2600800..."
                    }
                },
                {
                    "name": "Epson Projector",
                    "type": "switch",
                    "host": "192.168.1.156",
                    "data": {
                        "on": "2600900...",
                        "off": [
                            {
                                "data": "2600900...",
                                "sendCount": 2,
                                "interval": 3
                            }
                        ]
                    }
                }
            ]
        }`

After removing broadlinkRM parts on config file, it works.
What have I done wrong?

**Comment by okonet** [comment]
I have the same issue and it looks like it's causing by usage of raw Socket. See a similar issue here https://github.com/AlexGustafsson/homebridge-wol/issues/8

So glancing the source code it seems that `net-ping` uses raw sockets that require root permissions: https://github.com/nospaceships/node-net-ping/blob/master/index.js#L4

I'm not sure I'm comfortable running homebridge with root, though. Is there any way to work around this?

**Comment by lprhodes** [comment]
No need to run as root. Check out this issue: https://github.com/lprhodes/homebridge-broadlink-rm/issues/522

**Comment by rgerr** [comment]
Running this in docker on synology. The command given in issue #522 does not work for me, neither does a rolback to 3.6.10. Am getting the same error as above.

**Comment by lprhodes** [comment]
The error above doesn't help indicate what the issue is. There's generally more logs prior to that, if you're able to push them here then I can help further.

**Comment by rgerr** [comment]
Just noticed I needed to upgrade node to >v12. Currently on v10. Was that also upgrade with 3.6.11?

**Comment by cilianospina** [comment]
Same problem after update I try 

> sudo setcap cap_net_raw+ep /usr/bin/node

but not work for me

**Comment by rgerr** [comment]
Installed version 3.6.8, which works well again.

**Comment by cilianospina** [comment]
> Installed version 3.6.8, which works well again.

How?

**Comment by rgerr** [comment]
> > Installed version 3.6.8, which works well again.
> 
> How?

Uninstall current version, then install with npm install -g homebridge-broadlink-rm@3.6.8

**Comment by cilianospina** [comment]
> > > Installed version 3.6.8, which works well again.
> > 
> > 
> > How?
> 
> Uninstall current version, then install with npm install -g homebridge-broadlink-rm@3.6.8

npm ERR! code ETARGET
npm ERR! notarget No matching version found for homebridge-broadlink-rm@3.6.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by rgerr** [comment]
> > > > Installed version 3.6.8, which works well again.
> > > 
> > > 
> > > How?
> > 
> > 
> > Uninstall current version, then install with npm install -g homebridge-broadlink-rm@3.6.8
> 
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for homebridge-broadlink-rm@3.6.8.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.

Oops, it’s .7, not .8

**Comment by cilianospina** [comment]
> > > > > Installed version 3.6.8, which works well again.
> > > > 
> > > > 
> > > > How?
> > > 
> > > 
> > > Uninstall current version, then install with npm install -g homebridge-broadlink-rm@3.6.8
> > 
> > 
> > npm ERR! code ETARGET
> > npm ERR! notarget No matching version found for homebridge-broadlink-rm@3.6.8.
> > npm ERR! notarget In most cases you or one of your dependencies are requesting
> > npm ERR! notarget a package version that doesn't exist.
> 
> Oops, it’s .7, not .8

After return 3.6.7 and node 10.18.0 work again perfect
Thank you 😊

**Comment by lprhodes** [comment]
You'll miss out on significant fixes by not keeping up to date.

To deal with that specific issue @cilianospina you should upgrade to node 12.14.0 then remove the plugin and re-install.

i.e. `npm r homebridge-broadlink-rm -g && npm i homebridge-broadlink-rm -g`

**Comment by rgerr** [comment]
> You'll miss out on significant fixes by not keeping up to date.
> 
> To deal with that specific issue @cilianospina you should upgrade to node 12.14.0 then remove the plugin and re-install.
> 
> i.e. `npm r homebridge-broadlink-rm -g && npm i homebridge-broadlink-rm -g`

Yes, but won’t that ruin the entire homebridge setup? By the way, how do you upgrade node within a docker container?

**Comment by okonet** [comment]
I'm on node `12.14.0` and it doesn't work either.

**Comment by okonet** [comment]
@lprhodes any suggestions on how to do this with a Docker setup? I'm using https://github.com/oznu/docker-homebridge

**Comment by NathanAMiller** [comment]
Same Error here. After updating to latest version, gets error Error: The requested platform 'BroadlinkRM' was not registered by any plugin

**Comment by lprhodes** [comment]
@okonet and @NathanAMiller  It's not clear what your issue is for me to be able to help properly.

>  Error: The requested platform 'BroadlinkRM' was not registered by any plugin

could mean several things, there's generally an error that appears before that.

**Comment by lprhodes** [comment]
I've released 3.6.12 which should give better error reporting.

**Comment by lprhodes** [comment]
It also removes. the need to update node

**Comment by baatten** [comment]
I updated to the latest but I now get error:

TypeError: Cannot read property 'pingHost' of undefined
    at Timeout.setInterval [as _onTimeout] (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:31:10)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by baatten** [comment]
> It also removes the need to update node

I updated to the latest but I now get error:

TypeError: Cannot read property 'pingHost' of undefined
at Timeout.setInterval [as _onTimeout] (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:31:10)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)

**Comment by lordnikkon1983** [comment]
after I have now updated to 3.6.12 the error now comes:

`[2020-1-2 11:28:34 PM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

**Comment by baatten** [comment]
> after I have now updated to 3.6.12 the error now comes:
> 
> `[2020-1-2 11:28:34 PM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin. at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13) at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45) at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36) at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10) at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

I had that error on 3.6.11, I uninstalled and updated to 3.6.12 and error was gone. try to remove and re install the plugin.

**Comment by lordnikkon1983** [comment]
> > after I have now updated to 3.6.12 the error now comes:
> > `[2020-1-2 11:28:34 PM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin. at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13) at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45) at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36) at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10) at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)`
> 
> I had that error on 3.6.11, I uninstalled and updated to 3.6.12 and error was gone. try to remove and re install the plugin.

have now uninstalled the plugin and installed 3.6.12 new

the error is still there :(

**Comment by baatten** [comment]
> > > after I have now updated to 3.6.12 the error now comes:
> > > `[2020-1-2 11:28:34 PM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin. at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13) at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45) at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36) at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10) at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)`
> > 
> > 
> > I had that error on 3.6.11, I uninstalled and updated to 3.6.12 and error was gone. try to remove and re install the plugin.
> 
> have now uninstalled the plugin and installed 3.6.12 new
> 
> the error is still there :(

I updated my pi software:
sudo apt update
sudo apt full-upgrade
sudo reboot

I no longer have any errors.

**Comment by lordnikkon1983** [comment]
I've also done now

the error is still there

here is my complete log:

`Started Node.js HomeKit Server.
[2020-1-2 11:49:30 PM] Loaded config.json with 1 accessories and 7 platforms.
[2020-1-2 11:49:30 PM] ---
[2020-1-2 11:49:30 PM] Plugin /usr/lib/node_modules/homebridge-platform-helper package.json does not contain the keyword 'homebridge-plugin'.
[2020-1-2 11:49:30 PM] Plugin /usr/local/lib/node_modules/homebridge-automation-bluetooth-presence does not contain a package.json.
[2020-1-2 11:49:30 PM] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-broadlink-rm' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-broadlink-rm'.
[2020-1-2 11:49:30 PM] Loaded plugin: homebridge-automation-random-choice
[2020-1-2 11:49:30 PM] Registering accessory 'homebridge-automation-random-choice.AutomationRandomChoice'
[2020-1-2 11:49:30 PM] ---
[2020-1-2 11:49:30 PM] ====================
[2020-1-2 11:49:30 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[2020-1-2 11:49:30 PM] Error: Homebridge plugins that use the "homebridge-easy-platform" library require your node version to be at least the v12.14.0 LTM. Current version: v10.16.0
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-platform-helper/platform.js:4:50)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-platform-helper/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
[2020-1-2 11:49:30 PM] ====================
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-calendar
[2020-1-2 11:49:31 PM] Registering platform 'homebridge-calendar.Calendar'
[2020-1-2 11:49:31 PM] ---
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-config-ui-x
[2020-1-2 11:49:31 PM] Registering platform 'homebridge-config-ui-x.config'
[2020-1-2 11:49:31 PM] ---
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-fritz-platform
[2020-1-2 11:49:31 PM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[2020-1-2 11:49:31 PM] ---
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-telegram
[2020-1-2 11:49:31 PM] Registering platform 'homebridge-telegram.Telegram'
[2020-1-2 11:49:31 PM] ---
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-cmdtrigger
[2020-1-2 11:49:31 PM] Registering accessory 'homebridge-cmdtrigger.CmdTrigger'
[2020-1-2 11:49:31 PM] ---
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-delay-switch
[2020-1-2 11:49:31 PM] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2020-1-2 11:49:31 PM] ---
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-delayed-switches
[2020-1-2 11:49:31 PM] Registering platform 'homebridge-delayed-switches.DelayedSwitches'
[2020-1-2 11:49:31 PM] ---
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-ping-hosts
[2020-1-2 11:49:31 PM] Registering platform 'homebridge-ping-hosts.PingHosts'
[2020-1-2 11:49:31 PM] Registering accessory 'homebridge-ping-hosts.PingHostsContact'
[2020-1-2 11:49:31 PM] ---
[2020-1-2 11:49:31 PM] Loaded plugin: homebridge-weather-plus
[2020-1-2 11:49:32 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[2020-1-2 11:49:32 PM] ---
[2020-1-2 11:49:32 PM] Loading 7 platforms...
[2020-1-2 11:49:32 PM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2020-1-2 11:49:32 PM] Got SIGTERM, shutting down Homebridge...
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service hold-off time over, scheduling restart.
homebridge.service: Scheduled restart job, restart counter is at 5.
Stopped Node.js HomeKit Server.
`

**Comment by lprhodes** [comment]
@baatten I introduced an issue in my haste to get the last version out, sorry. Try .13.

The part of the log that reads `The requested platform 'BroadlinkRM' was not registered by` isn't helpful in figuring out issues, please make sure you include entire logs.

**Comment by lprhodes** [comment]
@lordnikkon1983 you have a different error, I'm looking into it now.

**Comment by lprhodes** [comment]
@lordnikkon1983 can you please update to the latest version (3.6.13) and open up a new Github issue with any any issues you're seeing.

**Comment by lprhodes** [comment]
@lordnikkon1983 there looks to be a few different issues there:

1. You're not on the latest version of the plugin which no longer requires Node 12.14.0
2. It looks like you've install the plugin in two places, I'm unsure which is correct in your situation: 
> '/usr/local/lib/node_modules/homebridge-broadlink-rm' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-broadlink-rm'
3. Looks like you might have some issues in your config.json, please post it (in the new issue)

**Comment by lprhodes** [comment]
Locking this issue. For anyone else who comes here, please create new issues with error logs that include more than just the following bit:

> The requested platform 'BroadlinkRM' was not registered by...
