### ISSUE TITLE
version 3.6.12 ping error

### ISSUE THREAD

**Issue by baatten** [lprhodes/homebridge-broadlink-rm#524]
getting error:

[2020-1-3 00:25:46] TypeError: Cannot read property 'pingHost' of undefined
    at Timeout.setInterval [as _onTimeout] (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:31:10)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    at listOnTimeoutNT (timers.js:369:26)
    at _combinedTickCallback (internal/process/next_tick.js:136:11)
    at Immediate._tickCallback [as _onImmediate] (internal/process/next_tick.js:181:9)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by pax0707** [comment]
```
Jan 02 23:37:41 raspi homebridge[1951]: [1/2/2020, 11:37:41 PM] TypeError: Cannot read property 'pingHost' of undefined
Jan 02 23:37:41 raspi homebridge[1951]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:31:10)
Jan 02 23:37:41 raspi homebridge[1951]:     at listOnTimeout (internal/timers.js:531:17)
Jan 02 23:37:41 raspi homebridge[1951]:     at processTimers (internal/timers.js:475:7)
Jan 02 23:37:41 raspi homebridge[1951]: [1/2/2020, 11:37:41 PM] Got SIGTERM, shutting down Homebridge...
Jan 02 23:37:46 raspi homebridge[1951]: [1/2/2020, 11:37:46 PM] TypeError: Cannot read property 'pingHost' of undefined
Jan 02 23:37:46 raspi homebridge[1951]:     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:31:10)
Jan 02 23:37:46 raspi homebridge[1951]:     at listOnTimeout (internal/timers.js:531:17)
Jan 02 23:37:46 raspi homebridge[1951]:     at processTimers (internal/timers.js:475:7)
Jan 02 23:37:46 raspi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jan 02 23:37:46 raspi systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by baatten** [comment]
I updated my pi software:
sudo apt update
sudo apt full-upgrade
sudo reboot

I no longer have any errors.

**Comment by pax0707** [comment]
Not helping here.
I rolled back to .11.

**Comment by lprhodes** [comment]
@pax0707 sorry about that, I was in a bit of a rush. I fixed the issue in .12

**Comment by pax0707** [comment]
Working now in .13.
