### ISSUE TITLE
many problems please help

### ISSUE THREAD

**Issue by lordnikkon1983** [lprhodes/homebridge-broadlink-rm#526]
as requested i will post my log and my config here. the errors have only started since I updated the plugin:

My Computer is a Mac Mini
Operation System: Ubuntu 18.04.3 LTS

Homebridge an all Plugins up to date with homebridge-broadlink-rm v3.6.13

[log.txt](https://github.com/lprhodes/homebridge-broadlink-rm/files/4017772/log.txt)

[config.json.txt](https://github.com/lprhodes/homebridge-broadlink-rm/files/4017798/config.json.txt)

**Comment by lprhodes** [comment]
Please update the plugin then provided additional logs.

**Comment by lordnikkon1983** [comment]
after update to 3.6.16

`Started Node.js HomeKit Server.
[2020-1-3 4:46:09 AM] Loaded config.json with 1 accessories and 7 platforms.
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:09 AM] Plugin /usr/lib/node_modules/homebridge-platform-helper package.json does not contain the keyword 'homebridge-plugin'.
[2020-1-3 4:46:09 AM] Plugin /usr/local/lib/node_modules/homebridge-automation-bluetooth-presence does not contain a package.json.
[2020-1-3 4:46:09 AM] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-broadlink-rm' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-broadlink-rm'.
[2020-1-3 4:46:09 AM] Loaded plugin: homebridge-automation-random-choice
[2020-1-3 4:46:09 AM] Registering accessory 'homebridge-automation-random-choice.AutomationRandomChoice'
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:09 AM] ====================
[2020-1-3 4:46:09 AM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[2020-1-3 4:46:09 AM] Error: Homebridge plugins that use the "homebridge-easy-platform" library require your node version to be at least the v12.14.0 LTM. Current version: v10.16.0
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-platform-helper/platform.js:4:50)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-platform-helper/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
[2020-1-3 4:46:09 AM] ====================
[2020-1-3 4:46:09 AM] Loaded plugin: homebridge-calendar
[2020-1-3 4:46:09 AM] Registering platform 'homebridge-calendar.Calendar'
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:09 AM] Loaded plugin: homebridge-config-ui-x
[2020-1-3 4:46:09 AM] Registering platform 'homebridge-config-ui-x.config'
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:09 AM] Loaded plugin: homebridge-fritz-platform
[2020-1-3 4:46:09 AM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:09 AM] Loaded plugin: homebridge-telegram
[2020-1-3 4:46:09 AM] Registering platform 'homebridge-telegram.Telegram'
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:09 AM] Loaded plugin: homebridge-cmdtrigger
[2020-1-3 4:46:09 AM] Registering accessory 'homebridge-cmdtrigger.CmdTrigger'
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:09 AM] Loaded plugin: homebridge-delay-switch
[2020-1-3 4:46:09 AM] Registering accessory 'homebridge-delay-switch.DelaySwitch'
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:09 AM] Loaded plugin: homebridge-delayed-switches
[2020-1-3 4:46:09 AM] Registering platform 'homebridge-delayed-switches.DelayedSwitches'
[2020-1-3 4:46:09 AM] ---
[2020-1-3 4:46:10 AM] Loaded plugin: homebridge-ping-hosts
[2020-1-3 4:46:10 AM] Registering platform 'homebridge-ping-hosts.PingHosts'
[2020-1-3 4:46:10 AM] Registering accessory 'homebridge-ping-hosts.PingHostsContact'
[2020-1-3 4:46:10 AM] ---
[2020-1-3 4:46:10 AM] Loaded plugin: homebridge-weather-plus
[2020-1-3 4:46:10 AM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[2020-1-3 4:46:10 AM] ---
[2020-1-3 4:46:10 AM] Loading 7 platforms...
[2020-1-3 4:46:10 AM] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2020-1-3 4:46:10 AM] Got SIGTERM, shutting down Homebridge...
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
Stopped Node.js HomeKit Server.
`

**Comment by lordnikkon1983** [comment]
you can also talk to me about telgram 

[https://t.me/Lordnikkon](url)

**Comment by lprhodes** [comment]
Some how you've installed (the same) plugins in both `/usr/local/lib/node_modules/` and `/usr/lib/node_modules/` which is causing issues.

**Comment by lordnikkon1983** [comment]
Thank you so much after I deleted the plugin and then looked in the two folders and although I deleted the plugin it was still there I deleted it manually. 

then added the old config file. 
homebridge then started 

see us there ..  the 3.6.16 plugin works perfectly. 

thank you again 

greeting
