### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-broadlink-rm

### ISSUE THREAD

**Issue by gintonic4all** [lprhodes/homebridge-broadlink-rm#549]
Hi,
since my update to node v12.14.1 and to homebridge 0.4.50 yesterday, the broadlink-rm fails with the following log. Since when is hap-nodejs necessary? Can anyone figure out or help me figure out how to solve that problem? Thanks in advance. 

---
[1/21/2020, 18:08:33] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[1/21/2020, 18:08:33] Error: Cannot find module 'hap-nodejs'
Require stack:
- /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js
- /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/index.js
- /usr/local/lib/node_modules/homebridge-broadlink-rm/platform.js
- /usr/local/lib/node_modules/homebridge-broadlink-rm/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js:13:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)

**Comment by daitium** [comment]
[https://github.com/lprhodes/homebridge-broadlink-rm/issues/545#issue-551801442](https://github.com/lprhodes/homebridge-broadlink-rm/issues/545#issue-551801442
)
try this

**Comment by cmh-maker** [comment]
downgrading to 3.6.16 fixed the issue for me

**Comment by gintonic4all** [comment]
Jupp, downgrading to 3.6.18 as well.

**Comment by booshtukka** [comment]
I had to manually install hap-nodejs.
