### ISSUE TITLE
The requested platform 'BroadlinkRM' was not registered by any plugin.

### ISSUE THREAD

**Issue by danewallace** [lprhodes/homebridge-broadlink-rm#569]
Hello, 

I recently tried reconfiguring the Broadlink RM plugin after not using it for a period of time. I have verified that the plugin is installed (via npm install -g homebridge-broadlink-rm). Node is up to date. JSON is validated. However, I receive the error below whenever I try to start homebridge. 

 Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by danewallace** [comment]
Rolling back to an earlier version of the plugin resolved the issue.

**Comment by ema07cqc** [comment]
> Rolling back to an earlier version of the plugin resolved the issue.

Hello there. how do you rollback to a earlier version? thanks.

**Comment by danewallace** [comment]
I uninstalled the plugin via npm uninstall -g homebridge-broadlink-rm and then chose an older version and installed that via npm install -g homebridge-broadlink-rm@3.6.10 (though you can specify another version of your choice after the '@').

**Comment by Mattserati** [comment]
This process doesn’t work when using HOOBS.
Lprhodes - is there a new version without this issue on the way? I have lost all Broadlink accessories since updating, and my json file is gone.

**Comment by daven1985** [comment]
I'm in the same boat as Mattserati, I also can't rollback via HOOBS. Any thoughts?

`{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023RCC5CMF04",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "throwback-blue",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "AU",
        "postal_code": "2250",
        "latitude": "-33.390517",
        "longitude": "151.341377"
    },
    "bridge": {
        "name": "XXX",
        "port": 51826,
        "pin": "XXXXXX",
        "username": "XXXXXXXX"
    },
    "description": "XXX house-hold powered by HOOBS",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "username",
                "password": "password",
                "countryCode": "AU",
                "platform": "smart_life",
                "pollingInterval": 10
            },
            "plugin_map": {
                "plugin_name": "homebridge-tuya-web"
            }
        },
        {
            "platform": "Camera-ffmpeg",
            "plugin_map": {
                "plugin_name": "homebridge-camera-ffmpeg"
            },
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Backyard",
                    "videoConfig": {
                        "source": "-re -i rtsp://192.168.1.4:7447/h8GRIZn4OBj0qMRc",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30
                    }
                },
                {
                    "name": "Frontyard",
                    "videoConfig": {
                        "source": "-re -i rtsp://192.168.1.4:7447/JzMFOEip1dlqDRn1",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30
                    }
                }
            ]
        },
        {
            "platform": "Alexa",
            "plugin_map": {
                "plugin_name": "homebridge-alexa"
            },
            "name": "Alexa",
            "username": "username",
            "password": "password",
            "pin": "xxxxxxxxxxx",
            "routines": true,
            "debug": true,
            "refresh": 15,
            "oldParser": false
        }
    ]
}`

**Comment by kiwi-cam** [comment]
One thought for HOOBS users, does the fork [homebridge-broadlink-rm-tv](https://github.com/AlexanderBabel/homebridge-broadlink-rm) work for you?

**Comment by daven1985** [comment]
> One thought for HOOBS users, does the fork [homebridge-broadlink-rm-tv](https://github.com/AlexanderBabel/homebridge-broadlink-rm) work for you?

Maybe I can try tonight. But does that work with Air Con units?

**Comment by kiwi-cam** [comment]
> Maybe I can try tonight. But does that work with Air Con units?

The fork is built from here so supports everything this does. We've only extended the existing functionality.  IMO, it works [even better with Air Con units](https://github.com/AlexanderBabel/homebridge-broadlink-rm#aircon-accessory) than this does.

**Comment by josehipo** [comment]
> > Maybe I can try tonight. But does that work with Air Con units?
> 
> The fork is built from here so supports everything this does. We've only extended the existing functionality. IMO, it works [even better with Air Con units](https://github.com/AlexanderBabel/homebridge-broadlink-rm#aircon-accessory) than this does.

But the broadlink-rm-tv doesn’t work with the latest Broadlink mini 3 (device code 5f36)

**Comment by kiwi-cam** [comment]
Device support is dependant on the [broadlinkjs-rm module](https://github.com/lprhodes/broadlinkjs-rm) which both plug-ins use.  If you're having issues with the device on broadlink-rm-tv and not broadlink-rm then please raise and issue on that fork and I'll take a look.

**Comment by josehipo** [comment]
> Device support is dependant on the [broadlinkjs-rm module](https://github.com/lprhodes/broadlinkjs-rm) which both plug-ins use. If you're having issues with the device on broadlink-rm-tv and not broadlink-rm then please raise and issue on that fork and I'll take a look.

Thank you! 
No way to use broadlink-rm

`The requested platform 'BroadlinkRM' was not registered by any plugin`

And broadlink-rm-tv does not support my device 

`Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "5f36". The device is connected to your network with the IP address “x.x.x.x"`

I guess I should use the latest version of broadlink-rm which added support for “5f36”.

I tried to star from the beginning with a fresh install of the system with the same result.

**Comment by daven1985** [comment]
> > Device support is dependant on the [broadlinkjs-rm module](https://github.com/lprhodes/broadlinkjs-rm) which both plug-ins use. If you're having issues with the device on broadlink-rm-tv and not broadlink-rm then please raise and issue on that fork and I'll take a look.
> 
> Thank you!
> No way to use broadlink-rm
> 
> `The requested platform 'BroadlinkRM' was not registered by any plugin`
> 
> And broadlink-rm-tv does not support my device
> 
> `Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "5f36". The device is connected to your network with the IP address “x.x.x.x"`
> 
> I guess I should use the latest version of broadlink-rm which added support for “5f36”.
> 
> I tried to star from the beginning with a fresh install of the system with the same result.

Thanks for your advice. Got the most process with that link (using home bridge now). However now I am getting the following error when I link on 'Learn' in HOME.APP.

[2/28/2020, 10:05:23 PM] [Broadlink RM] [ERROR] Learn Code (Couldn't learn code, device not found)

**Comment by ema07cqc** [comment]
> I uninstalled the plugin via npm uninstall -g homebridge-broadlink-rm and then chose an older version and installed that via npm install -g homebridge-broadlink-rm@3.6.10 (though you can specify another version of your choice after the '@').

It worked. Thanks.

**Comment by kiwi-cam** [comment]
Sorry @josehipo, npm is a version or two behind github with the broadlink-rm-tv plugin so it's not pulling the latest broadlinkjs-rm module version. Hopefully we can get npm updated ASAP so the device support is the same.

**Comment by josehipo** [comment]
> Sorry @josehipo, npm is a version or two behind github with the broadlink-rm-tv plugin so it's not pulling the latest broadlinkjs-rm module version. Hopefully we can get npm updated ASAP so the device support is the same.

Bien! Now I understand! I will wait patiently
Thank you!

**Comment by josehipo** [comment]
Maybe I shouldn't ask this here, but there is something that I don't understand:
To be able to use the TV type I need to install broadlink-rm-tv and for other devices (Switch type) I need broadlink-rm... Can I install both or do I have to choose?
