### ISSUE TITLE
Error: The requested platform 'Broadlink RM' was not registered by any plugin.

### ISSUE THREAD

**Issue by Joost1985** [lprhodes/homebridge-broadlink-rm#575]
Hi everyone, I recently installed the Broadlink plugin but unfortunately I get an error. More people seem to get this error, but none of the mentioned solutions that I could find help me. That is why I hereby open a new issue. The error message is as follows:

 Error: The requested platform 'Broadlink RM' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

Does anyone have an idea how to fix this?

Homebridge version: 0.4.52
Node.js version: 12.16.1
NPM version: 6.14.2
Broadlink RM plugin version: 3.6.22

**Comment by Joost1985** [comment]
I don't know exactly what I did, but suddenly homebridge came online and it seems to be working. The plugin finds my RM 3. Only I don't see any IR codes in my log after I have activated the Learn function. So I'm going to play with that now. In any case, I close these issues.
