### ISSUE TITLE
Won't install :-(

### ISSUE THREAD

**Issue by soulcook** [lprhodes/homebridge-broadlink-rm#587]
Fails every time I try to install it. Command line output below.

It says "No Xcode or CLT version detected!" -- but Xcode and CLTools ARE installed and up to date.

Look:

media@Media-Mac ~ % xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

Any ideas?

Thanks

Paul

media@Media-Mac ~ % npm install -g homebridge-broadlink-rm
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

> raw-socket@1.7.0 install /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raw-socket@1.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raw-socket@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Media/.npm/_logs/2020-03-31T20_52_31_814Z-debug.log

**Comment by soulcook** [comment]
Ok panic over – seems like this is a fairly common problem under Catalina and can be solved be uninstalling and reinstalling CLT. Solution here:
https://link.medium.com/6bpV2BJlk5
Working now.
