### ISSUE TITLE
No response in Apple Home

### ISSUE THREAD

**Issue by Spanishu** [lprhodes/homebridge-broadlink-rm#607]
After having updated the broadlinkjs I am finally able to learn codes again which is a great step forward!

I have learned the on and off command of my Mitsubishi air conditioner. However when I add it to my config I am getting an error "No Response" in the Home App. 

my config.json has this entry 
`{
                    "name": "Air Conditioner",
                    "type": "air-conditioner",
                    "data": {
                        "on": "26004c0272360f280f28100c0f0c100c0f280f0c100c0f280f280f0d0f280f0c0f0d0f280f280f0d0f280f280f0c0f0d0f280f0c0f0d0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f0c0f0d0f0c0f0d0f0c0f28100c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f28100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f280f280f28100c0f280f280f0d0f280f0001a973360f281027100c0f0c100c0f280f0c100c0f280f28100c0f280f0c100c0f280f280f0c10280f280f0c100c0f280f0c100c0f280f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f280f0d0f0c100c0f0c0f0d0f280f0c100c0f0c100c0f0c1027100c0f280f0c100c0f0c100c0f0c100c0f0c100c0f281027100c0f0c100c0f0c100c0f0c100c0f0c1027100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f0c100c0f2810271027100c0f280f280f0c10280f000d0500000000000000000000",
                        "off": "26004c0272360f280f290f0c0f0d0f0c0f280f0d0f0c0f280f280f0d0f280f0d0f0c0f280f280f0d0f280f280f0d0e0d0f280f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f0d0f0c0f0d0f0c0f0d0f280f0d0f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f280f280f0c0f290e0d0f0d0e290f0001a972370f280f280f0d0f0c0f0d0f280f0c0f0d0f280f280f0d0e290f0c0f0d0f280f280f0c0f290e290f0c0f0d0f280f0c0f0d0f280f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f280f0c100c0f0c100c0f0c0f290f0c0f280f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f280f0d0f0c0f0d0f0c0f0d0f0c100c0f0c0f290f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f0d0f0c0f280f280f280f0d0f280f0d0f0c0f280f000d0500000000000000000000"
                    }
                }`
and of course since it says no response nothing happens. Any idea / suggestion is more than welcome.

**Comment by Faisalthe01** [comment]
Check logs, that might help

**Comment by Naqsaq** [comment]
You'll definitely need to set some addtional stuff for AC's. Especially with RM3 which doesn't report any temperature. Do note that Mitsubishi's (at least mine) always send all the remote settings at once, thus you will have no way to control the fan, swing, mode, etc. as a separate. You can only dump everything at once, which doesn't really fit in to the aircon logic of Homekit. These hexes dump the cooling setting, auto fan mode and fixed swing position for every temperature. I have a separate switch to turn on the Dry mode. Here's my setup, which might help you - looks like the hexes might work directly for you. Note that I have multiple devices, thus I need the "host" section and I live in the tropics so this is only for cooling.

```
{
                    "name": "Bedroom Aircon",
		     "host": "192.168.1.117",
                    "type": "air-conditioner",
					"turnOnWhenOff": false,
					"ignoreTemperatureWhenOff": true,
					"replaceAutoMode": "cool",
					"pseudoDeviceTemperature": 30,
					"defaultCoolTemperature": 23,
					"temperatureUpdateFrequency": 300,
					"minTemperature": 10,
					"maxTemperature": 30,
					"disableLogs": true,
                    "data": {
                        "on": "26004c026f3610280e2b100c110c0f0d10290e0e110d0e2a0f29100d1028110d0f0e0f2811280e0e11280e2b100d100d0e29110d0e0d10290e0e100e0f0d0f0e0f0d100d0f0d110c0e0e0f0d110c100d0f0c110c100d100d0f0d100c100d0e0e0d2b110c0f0e0f0d0d100f0d0f291128100d0d0f100d10270e2b0e2b100d100c110c100d0e0f0e0e0d2b0e2a100d11281028100d0e0f100c0e0f100d0d0e110d0e0e1028100d100d100c0f0e0f0d0f0e0f0d100c100d110c0e0e100d100c100d0e0e100c100d100d0f0d100c100d0e0d0e0f0e0f0f0d100d100c100d0e0e0f0d110c100d100c0d0f100d0f0d0e100e0d110c100d100c100c100d100c0e0f0d0f100d100c100d0f0e0d0e0e100f0d0f0d100d0f0d0f0e0f0d1028100d1028100d100d0e290e2b1100022c773710290e2b100d110c0f0d0f290f0e100c0e2b1028100d0f29100e0d0f0d2b10290f0e0f291028110c100d0d2b0e0e110d1027110d0e0d100e0f0d0f0e0d0e100d0e0e110c100d0d0f100d100c100d0d0f100c0e0f100d0d0f0f0e0e2a0f0e0f0d100d100c100d0f281128100d0d0f100c11280f290e2b100c0e100e0d0e0f100c110d0e291128100d10281028100e100c100d0e0e100d0e0e0f0d0f0e0d2b0f0e0d100f0c110c100d0f0d100c0f0d100e0f0d100c0d0f110c100d0f0d100c0e0f0f0e0e0d110d0e0d110c100c0e0e110d0f0d100c0f0e100c100d0f0e0f0d0d0f100d100d100c0f0d110c0d0f110b110d0f0d100c100d100c0f0d0e0f0d100e0e100d0f0d100d0e0e0f0e0f0d100d0f0d0d0f1028110c1028110d0e0e102811280d000d0500000000000000000000",
                        "off": "26004c02733610281128100c100d110c1028110c100c11281128100c1029100c110c10291028100d10281029100c110c1128100c110c1028110c100d100c100c110c0f0d100d100d100c110c0f0d100d100c100c110c100d0f0d100d100c100d0f0d100c100d100c100d0f0d10281029110c100c100d0f29100d0f0d1028100d100d0f0d100c100d10281028110c10281128110c100c1029100c100d100c100d0f0d1028110d100c100d0f0d100c110c100c110c100c110c0f0d100d100d100d0f0d0e0f0f0d0e0e0f0e0f0d0f0d100d100d0e0e100d0e0d100d0f0e0f0d0f0e0e0e0f0e0f0d0f0e0f0c100e0e0e100d0f0d100d0e0e0f0d100d0f0d100d0f0d0f0e0f0e0e0e0f0d100d0f0d0f0d0f0d110c0f0d110b1128100c11281128100c1128110c0f291000022d793610281128110b110d0f0e0f28110c100e0e291029100c1128100c100c10291128100c10291028110c100c1128110c100c1128100c100c110c100c110c110c100c100d100c100d100c100d100c100c100d100c110c100c110c100d100c100c110c100c110c110c10291028100c110c100c1029110b110c1128100c100d100c110b110c11281028110c11271128100c110c1029100c100c110c110b110c1028110c100c110c100c100d110b110c100c110c100c110b110c100c110c100c110c100c100d100c100d100c110c100c110c100c100d110b110c110b100d100c100d100c100c110c100c100d100c110c100c100d110b110c100c100d100c110c100c110c100c110b110c110c100c110b110c100c1128110b11281128100c1128110c0f2910000d0500000000000000000000",
						"temperature21":{
							"pseudo-mode":"cool",
							"data":"26004c026e3610291028110c100c110c1029100c100c11281028100d11280f0d100d10281029100c10291028110d0f0d0f29100c110c1029100c100d100d0f0d100d0f0d100d100c100d0f0d100c100c110c100c100d100d100c100c100d0f0d1028110c110b110c110b120b10291128100c100d0f0d10290f0d1029100c100d0f0d100d0f0d100c12271029100c112810290f0d100c110c100c110c100c100d100c1029100c110c100d100d0f0d100c100c100d100d100c100d100c100c110c100c110c110b110c100c100d110b100d100c110c100c100d100c100d100c100d100c100c110c100c100d100c100c110c100c110c100c100d100c100d0f0d110c100c100c110c100c110c100c110c0f0d110c100c100d100c100d0f0d1029100c100d102811280f000230773610291127110c0f0e100c1029100c110c10281128100c10290f0d110c10291028100d10281029110b100d0f29110c100c10290f0d110c0f0d100d0f0d100c110c100d0f0d110c100c110c100c100c110c100c100d100c100d100d0f29100d100c110c100c110c10281029100c100d0f0d1128100c1128110c100c100c110c100c100d0f291128100d10281128100c100d100c100d100d100c100c100d1028110c100c110c100c100d110b110c100c100c110c100c110c100c100d100c110c100c110c0f0d100d100c110c100c100c110c100c100d100c100c100d100c100d100c110c100c100d100c100d100c100c110c100c110c100c110c100c100d100c100c110c100c110c100c100d100c110c100f0e0c110b120b1029100c110c1028112810000d0500000000000000000000"
							},
						"temperature22":{
							"pseudo-mode":"cool",
							"data":"26004c026e3711281127110d0f0d0f0e0d2a100d0e0f10281128100d0d2b110c100d0d2a1029110c10280e2b0e0e0e100d2a0e0f0e0e11280f0e100d0e0e100c100d0f0e0c0f110c0d10100d0c10100c0d10100c0f0e100c0f0e0d0e120b100d0f290e0f0d0f0e0f0d0f100d10280f2a0f0d110d0f0d0d0f0d2b0f2a110c100d0f0d0d0f100d0d0f0f291128110c10280f2a0e0e100d0e0e0e0f100d0d0e0e0f0f0e10280f0d0e0f0f0d100e0e0d100d0e0f0d100d0f100d100c100d0d0f100c100c0e10100c100d100c100d0f0d0f0e0c0f100e100c100c0f0e100d0e0e100d0f0d100d0f0d0f0c0e100d0f100d0f0c100d110c0d0f0e0f100c110d0c10100c0d10100c100d0d0f0d10100c0d0f0f0e100d0f0d0f0e0f28100e0f0d0f29100d0d0f112711281000023076380d2b1128100d100d100c1029100b0e0f0f2a0f29110c0f290e0f0f0d0e2b10290f0d11281127110c110d0f28100d100d0d2b100d0f0e0f0d0d0f0d0f0e0f0d0f0f0e100d0d0f0d0f0f0e0d10100c0f0e100c100d0f0d100d0e0e0d2b0f0e0d10100c0f0e0d0e11280f29100d100d0d10100c10291029100c0d10100c100d0e0e0f0e102811280d0f11280e2a110d0e0e100d100c100c0e0e100d0e0f10280f0e100d100c0f0e0d0e100e0d0e110d0f0d100d0d0f0f0e100c100d0e0d110d0f0d0d0f0d10100c0d0f0f0e100d0f0d0f0e0f0d100c100d0e0e0f0e100c100d100c0d100f0d0f0e0f0e0e0e100c100c110c0d0f110c0d0f110c0d10100c0f0d100d0f0d0d0f0e0f100d0f0d100d100c0f0e0f28110d0d0e0e2b0e0f0d100f28102910000d0500000000000000000000"
							},
						"temperature23":{
							"pseudo-mode":"cool",
							"data":"26004c026f3610280e2b100c110c0f0d10290e0e110d0e2a0f29100d1028110d0f0e0f2811280e0e11280e2b100d100d0e29110d0e0d10290e0e100e0f0d0f0e0f0d100d0f0d110c0e0e0f0d110c100d0f0c110c100d100d0f0d100c100d0e0e0d2b110c0f0e0f0d0d100f0d0f291128100d0d0f100d10270e2b0e2b100d100c110c100d0e0f0e0e0d2b0e2a100d11281028100d0e0f100c0e0f100d0d0e110d0e0e1028100d100d100c0f0e0f0d0f0e0f0d100c100d110c0e0e100d100c100d0e0e100c100d100d0f0d100c100d0e0d0e0f0e0f0f0d100d100c100d0e0e0f0d110c100d100c0d0f100d0f0d0e100e0d110c100d100c100c100d100c0e0f0d0f100d100c100d0f0e0d0e0e100f0d0f0d100d0f0d0f0e0f0d1028100d1028100d100d0e290e2b1100022c773710290e2b100d110c0f0d0f290f0e100c0e2b1028100d0f29100e0d0f0d2b10290f0e0f291028110c100d0d2b0e0e110d1027110d0e0d100e0f0d0f0e0d0e100d0e0e110c100d0d0f100d100c100d0d0f100c0e0f100d0d0f0f0e0e2a0f0e0f0d100d100c100d0f281128100d0d0f100c11280f290e2b100c0e100e0d0e0f100c110d0e291128100d10281028100e100c100d0e0e100d0e0e0f0d0f0e0d2b0f0e0d100f0c110c100d0f0d100c0f0d100e0f0d100c0d0f110c100d0f0d100c0e0f0f0e0e0d110d0e0d110c100c0e0e110d0f0d100c0f0e100c100d0f0e0f0d0d0f100d100d100c0f0d110c0d0f110b110d0f0d100c100d100c0f0d0e0f0d100e0e100d0f0d100d0e0e0f0e0f0d100d0f0d0d0f1028110c1028110d0e0e102811280d000d0500000000000000000000"
							},
						"temperature24":{
							"pseudo-mode":"cool",
							"data":"26004c026f3610291028110c100d0f0d1029100c100c112810290f0d11280f0d100d10281029100c10291028110c100d0f29100d0f0e0f29100d0f0d100d0f0c110d0f0d100d100c100d0f0d100c100d0f0d100d0f0e0f0d100c100d0f0d0f0d1029100d0f0c110d100c110b10291128100c100d0f0e100c100d0f0d0f29100c110c100d0f0d100d0f2a0f28100d102810290f0e100c100d0f0d100d100d0e0e100d0f28110d0f0d0f0e0e0e100d0f0d100f0d0d100d0f0d100d0f0d100d0e0e100d0e0e100d0f0d0f0e0e0e100d0e0e100d0e0e0f0e0f0d0f0d100d0f0d100d0f0d100d0f0e0d0e0f0e100c0f0d100d110c100d0e0e100d0f0d100d0f0d100d0f0d100c100d0f0c100d100d0f0e100d0e0e100d0e0e10281028110d0f28110d0e0e0f290f2a0f00022e783611281028100d100c110d0f28110d0f0d10281029100d1028100c110d0f281128100d0f290f2a0f0d100d0f29110c100d0f29100d0f0d100d0e0e100c100c110d0f0d0f0e0e0e100c100c110d0f0d100c0f0e0f0d100c100c100e0f28110c100d0f0d100d0f0d10290f290f0e100c100d100d0e0e100d0e2a0f0e0f0d100d100c100d0f291028100d0f291029100d100d0f0d100d0f0c110d0f0d0f0e0f29100d0f0d0f0d100d0f0d100d0f0d0f0e0e0e100d0e0f0f0d100b110d0f0d100d0e0d110d0e0e100d100b100e0f0c110d0f0d100d0f0d100d0f0d0f0d100d0f0d100c100d100c100d0f0c110d0f0d0f0e0f0d0f0d100d100d0e0e0f0d100d0f0d100d0f0d100d0f0d100d0e0d110d0e0d100d10281029100d1028110c0f0d1029102810000d0500000000000000000000"
							},
						"temperature25":{
							"pseudo-mode":"cool",
							"data":"26004c026d380e2b0f290e0f0e0e0e0f0d2b0e0f0d100d2b10280e0f0e2a0e0f0e0e0e2b0e2b100d0e2a1128110b0e0f0e2a0e100f0c11280e0e0e0f0e0f100c0e0e0e0f0d0f0e0f0e0e0e0f0e0e0e0f0e0e0e0f0d100d0e0e0f0e0e0f0e0e0f10280e0e110c0e0e0e0f0d0f0e2b0e2b100c0e100f0d0d2b0d0f0e0e0e2b110c100c0e0e0e0f0e0e0e2b10280e0f0e2b0f29100d0d0f0e0f100c0e0f100d0d0f100c0e2a110d0f0c0e0f0f0e0d100e0e0e0e0e0f100d100c0d10100b0e100d0e0e100d0e0e0f0e0e0e0f0e0e0e100d0e0e0f0d100d0e0e0f0e0f0d0f0d0f0e0f0d100d0f0d0f100d0d0f0e0e0e100e0d0e0f100d0d0f0d100d0f0f0e0d0e100e0d0f100c0e0f0e0d0e100f0d100c0e0f0d0f0e0f0d0f100d0d0f0d2b0e2b110b0e0f0e2a10290e00022e77390d2b10290f0e0d0f0e0f0d2b100c100e0d2b1029100d0d2b100c120c102810290e0e10280e2b100d0e0e0d2b0e0f0e0e0e2b100c110d100c100c0d0f0e0f0d0f0e0f0d0f0e0e0e0f0e0f0d0f0e0e110c0d0f0e0f100c0e0f0d0f0e2b100d100c0e0f0d0f0e0e0e2b0e2b100c0e0e0e0f0e2a110c0e0e0e2b0d0f0e0e0e100d0e0e0f0e2a0f2a100d0e2b1029100c0d0f0e0e110c0f0e0e0e0f0e0e0e0e2b0e0e0e100f0c0e100f0d0d0f0d0f0e0f100c120b0e0f0e0e0e0e0e0f0d0f0e0e0e0f0e0f0d100d0f0d0f0d0f0e0f0d100d0f0d100d0e0e0f0e0e0e0f100d100c0e0e0e0f0e0f0d0f0e0f0d0f0e0e0e0f0e0e0e0f0e0f100c0d100d0f0e0e0e0e0e0f0f0e0d0f0e0f0f0e0d0e0e0f0e0f0d0f0e0f100c0d2c10280d100d0f0d2b0e2b10000d0500000000000000000000"
							},
						"temperature26":{
							"pseudo-mode":"cool",
							"data":"26004c026e3710281128100d100d0c0f10290f0e0d0f0d2b1128100c11280e0f100d0e2a10280e0f0d2b0e2b0f0d0f0e0d2b110d0f0d0d2b0f0e100d0f0d0e0f0f0d100c0d100f0d100d0e0e100d0f0d100d0f0d100c0f0e100c100d0e0e100c1029100d0f0d0f0e0d0f0f0d10281029110d0d0f0f100e0c10290e0d0e2b100d100d0e0e0f0e0e0d102911280f0e0f290f29110c100d100c100d100c0f0e100d0f0d10280e0f100d0e0e100d0e0d100e0c0f110c100d0f0e0f0c110c100d0e0e0d100d0e0e0f0f0e100c0d100e0d100d110d0f0d0d0f100d100c100d100c0f0e0e0e100d0d0e110d0d0f100c100d100c100d0d0f100d100c100d0f0d100d0e0e0f0e0f0c110d0f0d0f0e100c0f0e0f0d100d0f0d100d0f280e100f280e2b100d0f0e10280f2910000234773711281029100c110d0f0d1028100c110d0e291029110c10280e0f100d0d2b0f2a100d0e2a0d2b110c100d1028100d100c1028100e0f0d0f0e0e0e0d0f0f0e100c0f0e100c100d100b100e0d0f0d100d0e100e0f0d0d0f0f0e0f0d1029100d100d0f0d0f0e0f0d0f2910290f0d100d0d100f0d1028110c10280e0f100d0f0d0f0e0e0e0f2911280f0e10280e2b100c100d100d100c110c0f0d0f0e0f0e0f28100d100d100c0d0f0e0f0f0e0d0f100d0f0d100d0f0d0f0e100d0f0d0e0e100d0f0c0e100d0f100d0c0f100d100d0f0d0f0e100b110c100d0f0e0e0e100d0f0c110c0f0e100c0f0e100c100d100d0f0d100d0c10100c0d10100c0f0e100c0f0e0f0d0f0d0f0e0f0d110c0f0e0f0d100d0e0e1028100d0d2b0d2b100d100d0d2b0f290e000d0500000000000000000000"
							},
						"temperature27":{
							"pseudo-mode":"cool",
							"data":"26004c02713610291028100d100d0f0d1028110d0f0c11281028100d11280f0d100c11280f2a100c102910280e0f0f0e0f29100d0f0d1028110d0e0e0d100e0e0d0f100d100c110b100e0f0c110d0f0d0f0d100d100d0c100d0f100d0d0f0f0e0f28110c110b110d100b120c0e2a10290d0f100d0f0d10281029110c0d2b0f0e100d0e0e0f0d100d10281029100c10281128100d0d100f0d0d0f100d100d0f0c100d0d2b0f0e0d100d0f0f0e0f0e0f0d0e0e0f0e0f0d0f0e0d0f100c0f0e0d0f0f0e100c0f0e0f0d0f0d100d100d0e0e110b100d0f0e0f0d100d100d0f0d0e0e0f0e0d0f0d100e0d110d0d0e100e0e0e0f0e0f0d0f0d100d0f0e0f0d100c0f0e0f0e0f0d0d0f100d0d0e110c100c100e0f0d0e0f0f0d100d0f2810290f2a100d0f0e0c2b11280f00022f76380f291029100d100c100d0f290f0d0e100e291128110b1029100d100c11281028100d0f290f2a0f0d110d0e29110c0f0e0f29100c100d110b110c100d100d0e0e0f0d100c100d100d0e0d100e0f0d0d100f0d0d0f100d0f0d100d0f29100d0e0d0e100d0f0d0f0f2a0f29100d0f0e100d0f281128100c1029110c0f0d0e0f100c100c10291029100c102910290d0f100d0d100d0e110d0e0d110d0c101028100d0f0d100d0f0e0f0d0f0d100d100d0e0d100c110d0f0d100d0e0e0d0f0f0e0f0e0f0d100c100d0f0d100d0f0d0d0f100c100d0f0d100d0f0d100d100d0f0d100c100d0d0f0f0d100d100d0f0d100d0e0e0d10100d100b100e0f0d0f0d100d100d0e0e0d0f100d0d0f0f0d100d100d0e0d110d0f28112810280e0f100c10290f2910000d0500000000000000000000"
							},
						"temperature28":{
							"pseudo-mode":"cool",
							"data":"26004e02733610290f29110c100c100e0e29100d100d0f291028100d10290f0d100d10281029110c10281128110b110c1028110c100d10290f0c110c100d100d0f0c100e0e0d100e0e0d100e0f0c110d0f0d100d0f0d0e0e100d0f0d0f0d100d10290f0c100d110b100e0e0d112810290f0d100d100d0f0d0f0d10290f2a0f0d100c110d17060f0d0e2a1028110d0e2911280f0d110d0f0c110c100d100c100d0f0e0f28110d0e0d110c100d100c0f0e0f0d100d0f0d0f0d100c100e0e0e0f0d100d100c100d0f0d100d100d0f0d0f0d0f0e100c100d0f0d100d0f0d100c100d0f0d100d100c100c100d100d0f0d0f0e0e0e100c100e0f0d0f0d100c100d100d100c100c100c110d0f0d0f0e0f0d0f0e0e0e100c0f0e0f29102811280f2a0f0d110c102811281000016605c2773711281029100c100d0f0e0f29100c100d10290f29100d0f28100d100c10291028110c10291028110c0f0e1028100d100c1028110c110b100e0f0d0e0e100c100c100d100c100d110b110c100c110d0f0d100d0f0d100d0f0c110c1028110c100c100d0f0e0f0d10281128100c110d0e0d100e0f0d10280f2a100c100d0f0e0f0d100c10291028100d11281028110c0f0d110c100c110d0e0d110c100c1128100d0f0d100d0f0c100d100c100c110c100d100c100d100c100d0f0d100c110c100d100d0f0e0f0c100d100c100c110c100c100d100c100d100d0f0d0f0e100c0f0e0f0d110b110c100c110d0e0d110c100d100d0f0c100d100d0e0d110c100d0f0d100c100d100d0f0e0e0d100d100d0f0d0f290f2a10291028100d0f0d102911280f000d050000000000000000"
							}
```

**Comment by Spanishu** [comment]
Thanks a lot. I will give a look and see what I come up with. Stay tuned, I am quite sure that I have more questions!

**Comment by Spanishu** [comment]
Hi @Naqsaq I have used your config and got quite far. 
I am seeing in my log some error messages 

` UnhandledPromiseRejectionWarning: AssertionError: [CONFIG ERROR]  You need to provide a hex code for the following temperature:
        { "temperature30": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
        or provide the default temperature:
         { "temperature30": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } }
    at AirConAccessory.getTemperatureHexData (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:301:7)
    at AirConAccessory.sendTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:238:48)
(node:7219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

Also another question is how could I use the same temperatures as well for heating on the same device?

**Comment by Faisalthe01** [comment]
Have a look at this, it would help https://github.com/kiwi-cam/MyHomeBridge/blob/master/var/homebridge/config.json

**Comment by Naqsaq** [comment]
> Hi @Naqsaq I have used your config and got quite far.
> I am seeing in my log some error messages
> 
> ` UnhandledPromiseRejectionWarning: AssertionError: [CONFIG ERROR] You need to provide a hex code for the following temperature: { "temperature30": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } } or provide the default temperature: { "temperature30": { "data": "HEXCODE", "pseudo-mode" : "heat/cool" } } at AirConAccessory.getTemperatureHexData (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:301:7) at AirConAccessory.sendTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:238:48) (node:7219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`
> 
> Also another question is how could I use the same temperatures as well for heating on the same device?

That's error looks like the result of my config not haveing "temperature30" defined and you tried to set it to that temperature. Left the "maxTemperature" to 30 by mistake. Can't comment on the heating part - my units don't even have that functionality, but @Faisalthe01 linked a nice looking config template.

**Comment by Spanishu** [comment]
@Naqsaq thanks for the indications I got my Mitsubishi to work like a charm. All perfect. Where I am struggling right now is on my Daikin. 

I am able to turn it on with the codes I have, but then I am not able to change temperature (I do believe that I have the right codes scanned). The worst is that I cannot turn it off. I believe there must be something either on duration / repeat etc but I am not able to figure it out. Any guidance would be much appreciated
