### ISSUE TITLE
Unable to register plugin on Homebridge V1.1.0 but works with @Defensor7 fork

### ISSUE THREAD

**Issue by calvinyeap** [lprhodes/homebridge-broadlink-rm#632]
I've just done a fresh install using [Homebridge Raspberry Pi Image v1.0.4](https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started) and I'm getting the following error upon loading the plugin. I manage to get it to work fine with @Defensor7 fork [homebridge-broadlink-rm4 v3.6.23](https://github.com/Defensor7/homebridge-broadlink-rm#readme). Anyone encounter similar scenario?

Homebridge Version | 1.1.0
Node.js Version | v12.16.3
Npm Version | v6.14.5

Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)

**Comment by salacika** [comment]
+1
