### ISSUE TITLE
(node:1792) UnhandledPromiseRejectionWarning: Error: Operation not permitted

### ISSUE THREAD

**Issue by jakuba1212** [lprhodes/homebridge-broadlink-rm#635]
Hi,
Suddenly I've been getting this error while starting Homebridge app. I have the latest homebridge-broadlink-rm plugin installed (3.6.22). I've been trying to find a solution to this but to no avail. Any help is very appreciated. !
NodeJS version: v10.20.1

```
(node:1792) UnhandledPromiseRejectionWarning: Error: Operation not permitted
    at new Socket (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:147:20)
    at new Session (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/node_modules/net-ping/index.js:545:9)
    at pingIPAddress (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/helpers/ping.js:5:32)
    at SwitchAccessory.checkPing (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:70:5)
    at new SwitchAccessory (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/accessories/switch.js:13:34)
    at config.accessories.forEach (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/platform.js:71:32)
    at Array.forEach (<anonymous>:null:null)
    at BroadlinkRMPlatform.addAccessories (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/platform.js:63:24)
    at BroadlinkRMPlatform.accessories (/opt/nodejs/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/platform.js:28:20)
    at resolve (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:297:30)
    at new Promise (<anonymous>:null:null)
    at Server.loadPlatformAccessories (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:296:16)
    at config.platforms.forEach (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:285:36)
    at Array.forEach (<anonymous>:null:null)
    at Server.loadPlatforms (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:260:31)
    at Server.start (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:73:35)
    at cli (/opt/nodejs/lib/node_modules/homebridge/lib/cli.js:88:12)
    at Object.<anonymous> (/opt/nodejs/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

(node:1792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jakuba1212** [comment]
Following this fixed the problem: https://github.com/AlexanderBabel/homebridge-broadlink-rm/issues/70

`ls -al /usr/bin/node`
and then
`sudo setcap cap_net_raw+ep /opt/nodejs/bin/node`
