### ISSUE TITLE
Compiled againt a different Node.js version error on loading

### ISSUE THREAD

**Issue by felipesalomao** [lprhodes/homebridge-broadlink-rm#647]
I have node version v.14.4.0, i installed last version of homebridge UI X. I have raspberry pi running Raspbian OS.  When i try use Homebridge GUI (plugins tab) to search for broadlink-rm plugin (this repo), then clicked install. It execute `sudo -E -n npm install homebridge-broadlink-rm@latest`, then it install normally.. 

After that i restart homebridge to load plugin, then i got this error when it start.

```
[16/06/2020, 02:27:50] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[16/06/2020, 02:27:50] Error: The module '/usr/local/lib/node_modules/hap-nodejs/node_modules/mdns/build/Release/dns_sd_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
```

So homebridge broadlink plugin isnt working..

There is solution?

**Comment by gabriuelucho** [comment]
Hi 

I had the same, try to uninstall it and installing instead the the plugin named:
Homebridge Broadlink Rm4
(homebridge-broadlink-rm4 v3.6.23) 
which is from defensor instead of lprhodes (I think this one is abandoned)
