### ISSUE TITLE
Install homebridge-broadlink-rm from Homebridge Config UI X

### ISSUE THREAD

**Issue by maxxar79** [lprhodes/homebridge-broadlink-rm#654]
I'm trying to install this plugin using Homebridge Config UI X

But it's failing, read the log below

/home/homebridge/.npm/_logs $ cat 2020-06-22T10_11_15_836Z-debug.log | more
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'homebridge-broadlink-rm@latest'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose npm-session 6ca332485c89d099
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-broadlink-rm 1707ms
8 http fetch GET 200 https://registry.npmjs.org/homebridge-broadlink-rm/-/homebridge-broadlink-rm-3.6.22.tgz 208ms
9 silly pacote tag manifest for homebridge-broadlink-rm@latest fetched in 2018ms
10 timing stage:loadCurrentTree Completed in 2069ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 5ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule homebridge-broadlink-rm@3.6.22 checking installable status
18 silly fetchPackageMetaData error for homebridge-platform-helper@github:lprhodes/homebridge-platform-helper#feature/typescript Error while execut
ing:
18 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData spawn git ENOENT
19 http fetch GET 200 https://registry.npmjs.org/chai 470ms
20 http fetch GET 200 https://registry.npmjs.org/ping 416ms
21 http fetch GET 304 https://registry.npmjs.org/uuid 450ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/chai/-/chai-4.2.0.tgz 323ms
23 http fetch GET 200 https://registry.npmjs.org/ping/-/ping-0.2.3.tgz 329ms
24 silly pacote range manifest for chai@^4.2.0 fetched in 872ms
25 silly resolveWithNewModule chai@4.2.0 checking installable status
26 silly pacote range manifest for ping@^0.2.2 fetched in 795ms
27 silly resolveWithNewModule ping@0.2.3 checking installable status
28 http fetch GET 304 https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz 353ms (from cache)
29 silly pacote range manifest for uuid@^3.3.3 fetched in 834ms
30 silly resolveWithNewModule uuid@3.4.0 checking installable status
31 http fetch GET 200 https://registry.npmjs.org/broadlinkjs-rm 1106ms
32 http fetch GET 200 https://registry.npmjs.org/broadlinkjs-rm/-/broadlinkjs-rm-0.7.6.tgz 68ms
33 silly pacote range manifest for broadlinkjs-rm@^0.7.6 fetched in 1196ms
34 silly resolveWithNewModule broadlinkjs-rm@0.7.6 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/net-ping 1137ms
36 http fetch GET 200 https://registry.npmjs.org/find-key 1316ms
37 http fetch GET 200 https://registry.npmjs.org/github-version-checker 1320ms
38 http fetch GET 200 https://registry.npmjs.org/net-ping/-/net-ping-1.2.3.tgz 180ms
39 silly pacote range manifest for net-ping@^1.2.3 fetched in 1384ms
40 silly resolveWithNewModule net-ping@1.2.3 checking installable status
41 http fetch GET 200 https://registry.npmjs.org/find-key/-/find-key-2.1.3.tgz 132ms
42 http fetch GET 200 https://registry.npmjs.org/github-version-checker/-/github-version-checker-1.2.0.tgz 117ms
43 silly pacote range manifest for find-key@^2.0.1 fetched in 1485ms
44 silly resolveWithNewModule find-key@2.1.3 checking installable status
45 silly pacote range manifest for github-version-checker@^1.2.0 fetched in 1482ms
46 silly resolveWithNewModule github-version-checker@1.2.0 checking installable status
47 timing stage:rollbackFailedOptional Completed in 2ms
48 timing stage:runTopLevelLifecycles Completed in 3655ms
49 verbose stack Error: spawn git ENOENT
49 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
49 verbose stack     at onErrorNT (internal/child_process.js:469:16)
49 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
50 verbose cwd /usr/lib
51 verbose Linux 4.19.118-v7+
52 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "homebridge-broadlink-rm@latest"
53 verbose node v12.18.1
54 verbose npm  v6.14.5
55 error code ENOENT
56 error syscall spawn git
57 error path git
58 error errno ENOENT
59 error enoent Error while executing:
59 error enoent undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
59 error enoent
59 error enoent
59 error enoent spawn git ENOENT
60 error enoent This is related to npm not being able to find a file.
61 verbose exit [ 1, true ]

The command thats is executed from plugininstaller is

USER: homebridge
DIR: /usr/lib
CMD: sudo -E -n npm install homebridge-broadlink-rm@latest

**Comment by rickdhoy** [comment]
Hi 
maxxar79, did you get a resolution to this.

I am simply juts not getting anything  installed in the config file ! It says it is installed but nothing is happening once it is installed.

**Comment by ben-callaway** [comment]
@maxxar79 Did you get this working, getting the same using Homebridge Config UI X and also installing direct.

**Comment by ben-callaway** [comment]
I got this working by installing git first: https://linuxize.com/post/how-to-install-git-on-raspberry-pi/
