### ISSUE TITLE
dev.device is not a function

### ISSUE THREAD

**Issue by nitaybz** [lprhodes/homebridge-broadlink-rm#67]
I still see this error:
```
Apr 28 15:05:02 raspberrypi homebridge[14826]: /usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98
Apr 28 15:05:02 raspberrypi homebridge[14826]: dev.device();
Apr 28 15:05:02 raspberrypi homebridge[14826]: ^
Apr 28 15:05:02 raspberrypi homebridge[14826]: TypeError: dev.device is not a function
Apr 28 15:05:02 raspberrypi homebridge[14826]: at module.exports.Broadlink.genDevice (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:98:13)
Apr 28 15:05:02 raspberrypi homebridge[14826]: at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs/index.js:187:29)
Apr 28 15:05:02 raspberrypi homebridge[14826]: at emitTwo (events.js:106:13)
Apr 28 15:05:02 raspberrypi homebridge[14826]: at Socket.emit (events.js:194:7)
Apr 28 15:05:02 raspberrypi homebridge[14826]: at UDP.onMessage [as onmessage] (dgram.js:545:8)
Apr 28 15:05:02 raspberrypi flicd[16184]: Client EOF
Apr 28 15:05:02 raspberrypi flicd[16184]: A client was disconnected
Apr 28 15:05:02 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Apr 28 15:05:02 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
```

Even after I did the commands:
```
npm r broadlinkjs -g
npm i broadlinkjs@"git+https://github.com/lprhodes/broadlinkjs.git" -g
```

I'm using a lot of broadlink devices, I have S1C, MP1 SP2, along with the RMPRO & RMmini (that I'm trying to use with your plugin).
I want to keep using those not supported devices separately from your plugin., what should I do in order to fix that issue?

**Comment by lprhodes** [comment]
Try the following:

```
npm r homebridge-broadlink-rm -g
npm i homebridge-broadlink-rm -g
``

**Comment by eviewei** [comment]
[2017-4-29 14:57:14] [XiaomiMiio] miIO Plug 55197478 fetch status
[2017-4-29 14:57:14] [Broadlink RM] light getSwitchState: 0
[2017-4-29 14:57:14] [Broadlink RM] Music getSwitchState: 0
[2017-4-29 14:57:14] [Broadlink RM] Epson getSwitchState: 0
[2017-4-29 14:57:15] [My Broadlink SP2] power is on - false
[2017-4-29 14:57:15] [My Broadlink SP1] power is on - true
[2017-4-29 14:57:20] [Broadlink RM] light setSwitchState: 1
[2017-4-29 14:57:20] [Broadlink RM] [ERROR] The device at 192.168.31.175 (**********) doesn't support the sending of IR or RF codes.
[2017-4-29 14:57:22] [Broadlink RM] light setSwitchState: 0
[2017-4-29 14:57:22] [Broadlink RM] [ERROR] The device at 192.168.31.175 (***********) doesn't support the sending of IR or RF codes.

IR and RF don't work,others(wifi) ok!

Win10+Hyper-V+Ubuntn+RM pro

**Comment by lprhodes** [comment]
@eviewb please raise this as a separate issue

**Comment by lprhodes** [comment]
@nitaybz 

Updating to 2.3.0 will also fix the issue.
