### ISSUE TITLE
Problems connecting RM 3

### ISSUE THREAD

**Issue by ghost** [lprhodes/homebridge-broadlink-rm#673]
Hi everyone, I've been trying to connect for the first time my Broadlink RM 3 mini to my Homebridge based on Windows when the following error occurred:

[8/16/2020, 17:16:42] [RM Room1] Initializing BroadlinkRM platform...
[8/16/2020, 17:16:42] Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:568:3)
    at tryReadSync (fs.js:353:20)
    at Object.readFileSync (fs.js:390:19)
    at LocalStorage.parseFileSync (C:\Users\root\node_modules\node-persist\src\local-storage.js:661:35)
    at LocalStorage.parseStorageDirSync (C:\Users\root\node_modules\node-persist\src\local-storage.js:615:26)
    at LocalStorage.initSync (C:\Users\root\node_modules\node-persist\src\local-storage.js:142:14)
    at Object.nodePersist.initSync (C:\Users\root\node_modules\node-persist\src\node-persist.js:37:32)
    at Object.init (C:\Users\root\node_modules\homebridge-broadlink-rm\node_modules\homebridge-platform-helper\dist\helpers\persistentState.js:12:28)
    at new HomebridgePlatform (C:\Users\root\node_modules\homebridge-broadlink-rm\node_modules\homebridge-platform-helper\dist\platform.js:19:35)
    at new BroadlinkRMPlatform (C:\Users\root\node_modules\homebridge-broadlink-rm\platform.js:34:5)
    at C:\Users\root\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:280:30
    at Array.forEach (<anonymous>:null:null)
    at Server.loadPlatforms (C:\Users\root\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:260:31)
    at Server.start (C:\Users\root\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:73:35)
    at cli (C:\Users\root\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:88:12)
    at Object.<anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

To avoid stupid problems I've updated npm, chai and Node.js all of them to the latest release. I have C:\users\root\node_modules and .homebridge directories Full control on Everyone. But still no resolution what else could it be?

RM3 mini firmware: V44057
PID: some 0s 365f0000

Thanks in advance!

**Comment by ghost** [comment]
Edit: Using the original Broadlink app it connects and works perfectly, but still the same problem on Homebridge.

**Comment by ghost** [comment]
No one encountered this problem?

**Comment by vglucas** [comment]
I have the same problem with the second device RM 3 MINI (version 44057) in its original app working perfectly, but not in HOOBS hombridge (error 23/8/2020, 19:46:02 [Broadlink RM] [31m [ERROR] [0mTV-Studio sendData (no device found at xx: xx .....)

**Comment by ghost** [comment]
I guess we might need some expert's assistance.

**Comment by ghost** [comment]
Hi everyone, I solved the problem.
Basically I forgot to put -g parameter during installation via Cmd in 
**_npm install -g broadlink.....(etc)_**

I've manually deleted the plugin folder and reinstalled everything with this parameter. It all worked!

**Comment by vglucas** [comment]
hi dfergusson8, I keep having the same problem all the time
