### ISSUE TITLE
homebridge-broadlink-rm v3.6.22 and homebridge v1.1.2  - The requested platform was not registered by any plugin

### ISSUE THREAD

**Issue by ema07cqc** [lprhodes/homebridge-broadlink-rm#679]
Hi there. Thanks for this project. Been using for years.
Im having trouble with a fresh installation of Homebridge in my Raspberry.

homebridge --version 1.1.2
node --version v12.18.3
homebridge-broadlink-rm v3.6.22

This same config was working well on my previous build (i don't remember versions)

```
[9/4/2020, 13:29:49] Error loading platform requested in your config.json at position 2
[9/4/2020, 13:29:50] Error: The requested platform 'Broadlink RM' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
```

config.json extract:

            "platform": "Broadlink RM",
            "name": "Broadlink RM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "accessories": [
                {
                    "name": "Auto-off Switch",
                    "type": "switch",
                    "enableAutoOff": true,
                    "onDuration": 5,
                    "data": {
                        "on": "2600500000012...",
                        "off": "2600500000012..."
                        }
                    }
            ]

Thanks!!!

**Comment by fidel1228** [comment]
Same problem here, but no idea how to fix it

**Comment by kiwi-cam** [comment]
It looks like homebridge isn't able to find where homebridge-broadlink-rm is installed. Looks like homebridge has installed in `/usr/local/lib/node_modules`, is homebridge-broadlink-rm there too?  Did you install both with the `-g` (global) flag?

**Comment by fidel1228** [comment]
Problem solved:
Anyhow with a fresh homebridge installation hap-nodejs wasn’t installed correctly.
„sudo npm install -g hap-nodejs“ fixed the problem.

**Comment by ema07cqc** [comment]
> Problem solved:
> Anyhow with a fresh homebridge installation hap-nodejs wasn’t installed correctly.
> „sudo npm install -g hap-nodejs“ fixed the problem.

Not working here.

```
pi@homebridge:/var/lib/homebridge $ sudo npm install -g hap-nodejs
+ hap-nodejs@0.8.2
updated 1 package in 43.628s
```

```
[10/12/2020, 18:27:02] Error loading platform requested in your config.json at position 2
[10/12/2020, 18:27:04] Error: The requested platform 'BroadlinkRM' was not registered by any plugin.
```

homebridge --version 1.1.2
node --version v12.18.3
homebridge-broadlink-rm v3.6.22

Thanks.

**Comment by ema07cqc** [comment]
Reinstalled Homebridge from scratch and then installed this updated fork: https://github.com/kiwi-cam/homebridge-broadlink-rm from kiwi-cam
Now its working well with my Mini3 :D

Homebridge v1.0.12
Node.js v12.19.0
Npm v6.14.8
homebridge-broadlink-rm-pro v4.3.3
