### ISSUE TITLE
ERROR module loading

### ISSUE THREAD

**Issue by CameronVIE** [lprhodes/homebridge-broadlink-rm#693]
Hi! After having installed module I get following errors (HB Version 1.2.3)

[10/13/2020, 12:10:09 PM] Loaded config.json with 1 accessories and 8 platforms.
[10/13/2020, 12:10:09 PM] ---
[10/13/2020, 12:10:10 PM] Loaded plugin: homebridge-automower@1.3.2
[10/13/2020, 12:10:10 PM] Registering platform 'homebridge-automower.Automower'
[10/13/2020, 12:10:10 PM] ---
[10/13/2020, 12:10:10 PM] ====================
[10/13/2020, 12:10:10 PM] ERROR LOADING PLUGIN homebridge-broadlink-rm:
[10/13/2020, 12:10:10 PM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /homebridge/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/accessory.js
- /homebridge/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/dist/index.js
- /homebridge/node_modules/homebridge-broadlink-rm/platform.js
- /homebridge/node_modules/homebridge-broadlink-rm/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/src/accessory.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
[10/13/2020, 12:10:10 PM] ====================
[10/13/2020, 12:10:10 PM] Loaded plugin: homebridge-camera-ffmpeg@3.0.3

**Comment by CameronVIE** [comment]
did manually install hap-nodejs and after 2 times restart homebridge, it was recognized correctly

**Comment by CameronVIE** [comment]
did manually install hap-nodejs and after 2 times restart homebridge, it was recognized correctlydid manually install hap-nodejs and after 2 times restart homebridge, it was recognized correctly
