### ISSUE TITLE
sendData is not defined

### ISSUE THREAD

**Issue by lily148** [lprhodes/homebridge-broadlink-rm#91]
I updated the homebridge-broadlink-rm to latest version and found out this error message. So far it only happen to "FAN" mode. Other are okay. Seem like it is a function that missing in some of the file?

TV Area Fan setSwitchState: 0
setCharacteristicValue err ReferenceError: sendData is not defined
    at FanAccessory.performSetValueAction (/usr/lib/node_modules/homebridge-broadlink-rm/accessories/accessory.js:16:5)
    at FanAccessory.setCharacteristicValue (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:118:14)
    at emitMany (events.js:127:13)
    at Characteristic.On.emit (events.js:204:7)
    at Characteristic.On.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Service.Fan.Service.setCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:148:32)
    at Timeout.setTimeout [as _onTimeout] (/usr/lib/node_modules/homebridge-broadlink-rm/node_modules/homebridge-platform-helper/accessory.js:166:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by lprhodes** [comment]
I'll fix that in the next couple of hours
