### ISSUE TITLE
homebridge service termination caused by the highest temperature of the air conditioner

### ISSUE THREAD

**Issue by Guoer-xz** [lprhodes/homebridge-broadlink-rm#96]
If the maximum temperature exceeds 30 degrees, homebridge will report the termination of the service, I tried to change the maximum temperature of 40 degrees, homebridge can continue to work, but adjust the temperature of the upper part of the fader will become idle, or set a fixed temperature value of pseudoDeviceTemperature, but the interface temperature display is locked. I wonder if there is any more reasonable solution？

The following is a display of service termination.
——————————————————————————————————————————————
   if (state.currentTemperature > maxTemperature) throw new Error(`The current temperature (${state.currentTemperature}) must be less than the maxTemperature (${maxTemperature})`);
                                                   ^

Error: The current temperature (31.9) must be less than the maxTemperature (30)
    at AirConAccessory.processQueuedCallbacks (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:373:58)
    at device.onTemperature (/usr/local/lib/node_modules/homebridge-broadlink-rm/accessories/aircon.js:350:12)
    at emitOne (events.js:96:13)
    at device.emit (events.js:191:7)
    at device.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:384:22)
    at emitTwo (events.js:106:13)
    at device.emit (events.js:194:7)
    at Socket.cs.on (/usr/local/lib/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:207:18)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)

**Comment by Warden630** [comment]
I got the very same problem.

**Comment by lprhodes** [comment]
I just tried setting the maxTemperature to 40 and didn't see any issues. Can you expand on what the problem is with that solution please?

**Comment by Warden630** [comment]
when you dont set the maxTemperature value, and the currenttemperature go above 30, the homebridge process will crash. and now I have to delete the whole AIRCON from config.json to make the other stuff work.






At 2017-05-22 06:09:56, "Luke Rhodes" <notifications@github.com> wrote:


I just tried setting the maxTemperature to 40 and didn't see any issues. Can you expand on what the problem is with that solution please?

**Comment by lprhodes** [comment]
That doesn't explain why setting a maxTemperature of 40 or 50 doesn't fix this.

**Comment by lprhodes** [comment]
Feel free to re-open if this is still an issue after setting a maxTemperature of 40 or 50
